### ISSUE TITLE
Sidebar should include arrows

### ISSUE THREAD

**Issue by daniel-sanche** [google/docsy#100]
It can be difficult to read the hierarchy of the sidebar. Bold text is used both to highlight selected sections, and to emphasize folders over files. Drop down arrows would be very helpful to understand section groupings. More margin or coloring would also help.

<img width="244" alt="Screen Shot 2019-07-10 at 3 31 41 PM" src="https://user-images.githubusercontent.com/3914119/61009557-dab72b00-a327-11e9-9ee1-168b1a670e98.png">

**Comment by LisaFC** [comment]
Thanks for the feedback, I'll take a look at adding arrows as an option.

**Comment by asmacdo** [comment]
If anyone is interested in implementing this feature (@LisaFC?), I'd be happy to help test it. Maybe we can borrow this from Kubernetes docs? https://kubernetes.io/docs/concepts/overview/components/

**Comment by trauts2** [comment]
It would be very useful for users to be able to see when any menu topic has children.  Indicating with an arrow would do the trick, with its orientation indicating whether it is expanded or not.

**Comment by andreamussap** [comment]
**+1 for this issue**. Same problem in our site https://axway-open-docs.netlify.app/docs/ It's impossible to tell if a subsection has children. Looking forward to this enhancement. Thanks!!

![Docsy_100_Sidebarincludearrows](https://user-images.githubusercontent.com/10401080/79864936-38f25d80-83d2-11ea-98d5-e78bdac7131f.png)

**Comment by frodriguezsmartclip** [comment]
@andreamussap how have you configured the [NetlifyCMS admin backend](https://axway-open-docs.netlify.app/admin/) for creating new sections in your website? 

Do you have any link or guide to follow, install and configure by myself? 

Thanks!

**Comment by andreamussap** [comment]
@frodriguezsmartclip If I got your question right, every time we have a new section (submenu/ set of docs), we have to add it as a **collection** (link below) in our project [config.js file](https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.js) 

See https://www.netlifycms.org/docs/configuration-options/#collections

I hope this helps

**Comment by varun-khachane** [comment]
Hi, I would like to work on this issue. Can you assign it to me?

**Comment by huanlin** [comment]
Now we have site parameter `sidebar_menu_foldable`, so I think this issue should be closed.
See [Section menu options](https://www.docsy.dev/docs/adding-content/navigation/#section-menu-options).

**Comment by chalin** [comment]
I agree with @huanlin. Closing. Open a new issue if there is more to address. Thanks!
