### ISSUE TITLE
Add breadcrumbs to taxonomy result list

### ISSUE THREAD

**Issue by at055612** [google/docsy#1004]
When you click a taxonomy term, e.g. in the Tags cloud, you get the list of matching pages for that term.  It is possible to have multiple pages with the same name.  It would be clearer if each item had its breadcrumb displayed so the user can see where the page is.  The user also then has the option to select an ancestor of one of the matched pages.

I have done this on my site.  Happy to craft a PR for the change to `_default/taxonomy.html` if you feel it warrants being added into Docsy.  I also put each item in a card to make each item more distinct from each other.

It would need to respect the `breadcrumb_disable` config property or have its own, e.g. `taxonomy_list_breadcrumb_disable`.

The coloured tags are a local customisation so ignore that.

![image](https://user-images.githubusercontent.com/22818309/167154847-bf35237d-6dae-4e25-97c7-56964063d2f7.png)

The un-modified docsy theme looks like this for comparison:

![image](https://user-images.githubusercontent.com/22818309/167155063-743b2d3a-c3c1-4bc5-be06-3af42f82243c.png)

**Comment by raum51** [comment]
Great idea, also the cards. 
+1

**Comment by LisaFC** [comment]
I like it - @narrenfrei you added a lot of the taxonomy functionality, what do you think?

**Comment by narrenfrei** [comment]
I've already answered as @raum51 ;-)

**Comment by at055612** [comment]
Thanks @LisaFC and @narrenfrei / @raum51 .  Sounds like enough of a consensus for a PR.  I'll get on the case.
