### ISSUE TITLE
hugo build: warning '.File.UniqueID on zero object'

### ISSUE THREAD

**Issue by deining** [google/docsy#1007]
**How to reproduce**

* Create a new site from scratch as described [here](https://www.docsy.dev/docs/get-started/docsy-as-module/start-from-scratch/).
* Create a new page inside the `docs` folder: `hugo new content/docs/_index.md`
* Run `hugo -D` and you will get this warning:

```
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
WARN 2022/05/09 09:57:25 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
```

Using `hugo --panicOnWarning`, you can track down where the error originates:

```
Error: Error building site: failed to render pages: render of "section" failed:
execute of template failed: template: docs/list.html:12:11:
executing "main" at <partial "section-index.html" .>
: error calling partial: "...\layouts\partials\section-index.html:7:17":
execute of template failed: template: partials/section-index.html:7:17
: executing "partials/section-index.html"
at <where $pages "Parent.File.UniqueID" "==" $parent.File.UniqueID>:
error calling where:
Warning trapped. Remove the --panicOnWarning flag to continue.
```

So the offending code line is here:

https://github.com/google/docsy/blob/6fc622c3874b2af8d1d72a9212bf64acb41d9823/layouts/partials/section-index.html#L7

**Comment by LisaFC** [comment]
Let me take a look. That line was from an update in 2021 by someone who doesn't seem to still be on GitHub under that user name, but it didn't break anything at the time....

**Comment by richardsuematsu** [comment]
I had the same issue on Node v8.  Upgraded to Node v16 and it worked.

**Comment by chalin** [comment]
I followed your instructions but can no longer reproduce the error. Hugo 0.120.4 and Node 20. Can you still reproduce the error @deining?

**Comment by deining** [comment]
> I followed your instructions but can no longer reproduce the error. Hugo 0.120.4 and Node 20. Can you still reproduce the error @deining?

Yes, I can. Hugo v0.120.4 and Node 16.20.2, Ubuntu 22.04

**Comment by deining** [comment]
Oops, my description how to reproduce the error was imprecise, it is corrected now:
New content is disabled by default, so you have to run `hugo --buildDrafts` in order to be confronted with the error.
@chalin: pretty sure you can see the error once you run `hugo -D`.
