### ISSUE TITLE
Is there a preferred method for overriding partials?

### ISSUE THREAD

**Issue by jasonday** [google/docsy#1013]
Does docsy have a method to override partials?

**Comment by fekete-robert** [comment]
Hi, you can override partials by recreating them in your project, [Hugo's lookup order](https://gohugo.io/templates/lookup-order/) takes care of everything else.
For example, if you want to override `themes/docsy/layouts/partials/sidebar-tree.html`, just create the `layouts/partials/sidebar-tree.html` file in your project.

If you are layering themes (that is, you have more than one theme specified in your config file), then the layouts folder of the project is the strongest, then comes the first theme, then the second one.
