### ISSUE TITLE
Prepare Hugo modules and publish release v0.3.0

### ISSUE THREAD

**Issue by chalin** [google/docsy#1020]
- [x] Prepare Hugo modules for v0.3.0
- [x] Add / changes the steps in [Publishing a release](https://github.com/google/docsy/blob/main/CONTRIBUTING.md#publishing-a-release) if necessary explaining how to do the previous step
- [x] Publish v0.3.0

**Comment by chalin** [comment]
@deining or @geriom - is this something that you might have time for? I'll be out for a few weeks. /cc @LisaFC

**Comment by geriom** [comment]
Docsy v0.3.0 is out https://github.com/google/docsy/releases/v0.3.0
