### ISSUE TITLE
sidebar content list limited at 50 items? How to change that limit?

### ISSUE THREAD

**Issue by jasonday** [google/docsy#1026]
I have greater than 50 pages at the 3rd level:
```
- category
    - subcategory
        - pages greater than 50 in count
```
Docsy is limiting the number shown in the sidebar to 50. Where is this configurable?

Secondarily, how would I hide only this set of pages from the sidebar (but they still show up in list)?

**Comment by fekete-robert** [comment]
Hi, the sidebar-tree.html partial seems to have an undocumented parameter that I think governs this behavior.
Try setting the following in your config file in the [params.ui] section:
```
sidebar_menu_truncate = 100
```

**Comment by raum51** [comment]
You can find some info in #979 

Sorry, I thought I'had made the documentation already, but that isn't right.

**Comment by fekete-robert** [comment]
As for your second question about hiding pages, see the `toc_hide` option at https://www.docsy.dev/docs/adding-content/navigation/#section-menu

If you want to set it for an entire subsection, you can use the cascade feature of Hugo in the frontmatter of the _index.md of the subsection, like:
```
cascade:
  toc_hide: true
```

**Comment by jasonday** [comment]
Thank you. A fully baked `config.toml` with every option would be great for documentation purposes.
