### ISSUE TITLE
Adding external links in the menu removes right sidebar github actions and search bar

### ISSUE THREAD

**Issue by ajfriesen** [google/docsy#1032]
I have copied the docsy-example repo and changed a few things.

When adding a menu entry in the `config.toml` like so:
```
[[menu.main]]
    name = "Link"
    weight = 40
    url = "https://example.com"
```
the right side menu does not display the links for adding an issue, editing the site etc, and the search bar in the left menu and on the top navbar is gone.
If I remove the menu item everything is back to normal.

Any idea how I can debug this further?

**Comment by LisaFC** [comment]
Huh, that's weird. Where did you put the line in your config.toml? It needs to be before or after all the [params] or the Hugo parser gets confused and may not pick up all your site parameters inc your GitHub links etc.

See our userguide config for an example: https://github.com/google/docsy/blob/main/userguide/config.toml#L39

**Comment by LisaFC** [comment]
(I can dig into it further if that's not the problem!)

**Comment by LisaFC** [comment]
Did moving things around in config.toml fix the issue?

**Comment by ajfriesen** [comment]
Okay, after some testing I discovered my error.
I added this in the middle in the [params] section.

```
[params]
copyright = "gridscale GmbH"
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

[[menu.main]]
   name = "GitHub"
   weight = 50
   url = "https://github.com/google/docsy/"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false
```

Not used to writing `toml` I guess.
After moving it to its own section everything works as expected!

Will close this one then :)
