### ISSUE TITLE
Make "All Rights Reserved" easily changeable

### ISSUE THREAD

**Issue by stephanlachnit** [google/docsy#1039]
Currently the only way to change the "All Rights Reserved" note in the footer is by creating a new footer (e.g. Kuberflow), or by creating an artificial i18n file changing that parameter.

However I think it makes sense to have a parameter to change that text, since documentations are often provided under a CC-BY license. Similar to the `params.copyright` option there should be a `params.copyright_license` option or similar.
E.g.
```yaml
copyright = "A really cool programming group."
copyright_text = "Distributed under the CC-BY-4.0 license."
```
Should render to ` © 2022 A really cool programming group. Distributed under the CC-BY-4.0 license.`.

**Comment by fekete-robert** [comment]
Hi, you can do that by [overriding the related string in en.toml](https://www.docsy.dev/docs/language/#internationalization-bundles). 

1. In your project directory, create the `i18n` directory.
2. Add an empty file called `en.toml` to this directory.
3. Add the following to the file:
    ```
    [footer_all_rights_reserved]
    other = "Distributed under the CC-BY-4.0 license."
    ```

That way you can customize the text even if you have a multilingual site

**Comment by stephanlachnit** [comment]
> Hi, you can do that by [overriding the related string in en.toml](https://www.docsy.dev/docs/language/#internationalization-bundles). 
> 
> 1. In your project directory, create the `i18n` directory.
> 2. Add an empty file called `en.toml` to this directory.
> 3. Add the following to the file:
>     ```
>     [footer_all_rights_reserved]
>     other = "Distributed under the CC-BY-4.0 license."
>     ```
> 
> That way you can customize the text even if you have a multilingual site

I know, but I don't think that's a very nice solution.

**Comment by stephanlachnit** [comment]
Right, looking https://github.com/google/docsy/blob/main/i18n/en.toml it looks like that this is the recommended way of specifying these strings. Sorry for the inconvenience.
