### ISSUE TITLE
multiple blogs 

### ISSUE THREAD

**Issue by kiransk9** [google/docsy#1040]
I am trying to create 3 different blog tabs on docsy hugo website.

ie. blog, blog2, blog3

Is there any option i can do that or should i copy and paste blog layout multiple times in local layout folder.

**Comment by fekete-robert** [comment]
Hi, I'm not sure I understand exactly your question, but you can specify the type of a page (hence its layout) in the frontmatter.
So for example if you want to have two different blog sections of the site (like content/blog, content/blog2, and content/blog3), then I believe you can use the same blog layout, just specify something similar in the content/blog2/_index.md and content/blog3/_index.md files:
```
---
title: Second blog section
cascade:
    type: blog
---
```

**Comment by kiransk9** [comment]
@fekete-robert  Gothcha thank you..

**Comment by kiransk9** [comment]
issue resolved
