### ISSUE TITLE
Code blocks not full width on mobile

### ISSUE THREAD

**Issue by stephanlachnit** [google/docsy#1056]
The problem in a nutshell:

![Screenshot from 2022-06-15 22-11-35](https://user-images.githubusercontent.com/36662302/173919697-dd678bac-626b-4dfc-a606-fd61c0107832.png)

The culprit is [assets/scss/shortcodes/cards-pane.scss](https://github.com/google/docsy/blob/6769ab6e8f7d26aea222f02e86b576ee159f19c4/assets/scss/shortcodes/cards-pane.scss#L1-L5). The file hard-codes a `max-width`, which works on a desktop-like layout, but not on mobile. I think the correct fix is to change the linked lines to

```scss
.card-deck {
	@extend .td-max-width-on-larger-screens;
}
.card {
    @extend .td-max-width-on-larger-screens;
```

It looks correct on most things, but I haven't tried this with all possible card-pane configs so I'm not entirely sure. Please let me know if I should open a PR.

**Comment by LisaFC** [comment]
Yes, please do open a PR, thanks for spotting this problem! @deining can you comment/review?
