### ISSUE TITLE
target of href default search results list: set it to not open in a new window

### ISSUE THREAD

**Issue by aborruso** [google/docsy#106]
Hi,
the standard behavior is to open the href of one of the list in a new window.

It would seem more correct to me, that it worked like everything else, and that it opened in the same window.

Thank you

**Comment by LisaFC** [comment]
The default search results list is an embedded Google custom search and it opens in a new tab by default, but I think I can configure it to open in the same tab...

**Comment by LisaFC** [comment]
(also might add to the docs that if you use a Google custom search, that's the behaviour you'll get)

**Comment by aborruso** [comment]
@LisaFC thank you.

I know that it's Google custom search, but I think it should be better to open in the same tab.
This is only a suggestion, for a product that seems to me very well done.

Thank you

**Comment by LisaFC** [comment]
Thanks, and I've fixed it now! :)

**Comment by aborruso** [comment]
Thank you!

Which is the related commit?

**Comment by LisaFC** [comment]
There's none because it's actually configured in the Google Custom Search Engine UI rather than in the site that uses it. However, I've added some instructions to the Docsy docs so Docsy users can do the same thing in their sites in #109
