### ISSUE TITLE
swagger-ui DOM XSS

### ISSUE THREAD

**Issue by blockomat2100** [google/docsy#1076]
The swagger-ui which is used by docsy is outdated and prune to a DOM XSS vulnerability.

**Comment by theletterf** [comment]
Hi there! Sorry, I was on paternity leave.

I guess you'd have to update the swagger-ui dependency, or add it as a dependency even.

**Comment by chalin** [comment]
@theletterf - is this something you are name able to help with? Thanks!

**Comment by theletterf** [comment]
I think so. Let me have a look.
