### ISSUE TITLE
Check links in the user guide

### ISSUE THREAD

**Issue by chalin** [google/docsy#1089]

**Comment by deining** [comment]
Please note, that this [issue](https://github.com/google/docsy-example/issues/161) which was raised in the example site already, they suggest [hyperlink](https://github.com/untitaker/hyperlink) as link checking tool.
Another approach is to use the netflify's checklinks plugin. I experimented with this plugin in this [branch](https://github.com/deining/docsy/tree/link-check) a while ago. Results were promising, but the branch ist not fully ready for merging yet.

**Comment by chalin** [comment]
Thanks for the background info @deining. I'll look into that as soon as I can.
