### ISSUE TITLE
Update external documentation for Docsy

### ISSUE THREAD

**Issue by rionam** [google/docsy#11]
We need to have reviewed end to end documentation for Docsy in order to release.

**Comment by LisaFC** [comment]
Gotcha. That'll go on docsy.dev, but leave it as an issue here until we actually make that happen...

**Comment by LisaFC** [comment]
Related: https://github.com/google/docsy-example/issues/12

**Comment by LisaFC** [comment]
This should probably be assigned to me, as it's the stuff I've been working on for docsy.dev - the deliverable is basically a user guide, yes?

**Comment by LisaFC** [comment]
Related to #11

**Comment by LisaFC** [comment]
Will close this once the docs are reviewed.
