### ISSUE TITLE
Firefox for android: the collapsed menu disappears

### ISSUE THREAD

**Issue by aborruso** [google/docsy#110]
Hi,
as you can see below, in Firefox for android there is no menu.

I have a Moto G6 plus and the latest firefox for Android.

Thank you

![image](https://user-images.githubusercontent.com/30607/61435197-4147d480-a938-11e9-9632-5ac153982025.png)

**Comment by LisaFC** [comment]
Oh that's weird. It should have the main docs menu and it displays fine in Chrome/Android. I'll take a look.

**Comment by LisaFC** [comment]
Btw am not ignoring this but I'm on holiday so am only sporadically online - if anyone else wants to take a look too that would be great.

**Comment by biosmanager** [comment]
This is still present in the latest Firefox and Firefox Nightly on Android. The menu appears off-site.

![Screenshot_20201004-220946_Firefox.jpg](https://user-images.githubusercontent.com/9850952/95025996-62f0c100-068e-11eb-99f3-de1f2773144d.jpg)
