### ISSUE TITLE
Lunr search is broken in latest docsy release 

### ISSUE THREAD

**Issue by shanmydell** [google/docsy#1111]
https://github.com/dell/csm-docs

Please refer to the code above.

Locally also it is broken with GH pages also it is broken

Note: With 0.2.0 release only GH page is broken , as this is a major blocked , please look into this as soon as possible

**Comment by shanmydell** [comment]
@chalin @Marzal @arnaudlevy : Could you please look into this isseu

**Comment by coulof** [comment]
When doing a search the JS console errors:
```
main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '*')
    at o (main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1:3755)
    at HTMLInputElement.<anonymous> (main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1:1993)
    at HTMLInputElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at v.handle (jquery-3.6.0.min.js:2:41048)
```

**Comment by chalin** [comment]
I confirm that I'm seeing the same error. @shanmydell - thanks for the link to the website that you're seeing the problem with. I'll take a closer look shortly.

/cc @nate-double-u @thisisobate since we have a sit that is being switched over to Lunr

**Comment by Marzal** [comment]
With Gitlab Pages and docsy@v0.4.0 I see no error using Lunr

https://gitlab.com/Marzal/mundolibre

**Comment by chalin** [comment]
- Fixed via #1112
- Docsy project fixed via https://github.com/dell/csm-docs/pull/297

**Comment by chalin** [comment]
Thanks for the feedback @Marzal. Hopefully the fix in #1112 will leave your site fully functional -- I think it will, but in case it affects the styling of the close-search-results button, please let me know.

**Comment by shanmydell** [comment]
@chalin : thanks for the quick turnaround

**Comment by chalin** [comment]
Post-merge comments are still welcome @geriom.
