### ISSUE TITLE
Broken URLs since Hugo 101 due to leading slash and relURL

### ISSUE THREAD

**Issue by Marzal** [google/docsy#1114]
Since [Hugo 101](https://github.com/gohugoio/hugo/commit/a5a4422aaeffe0e9df713cf09c73a9cc423a2e1e), if you use a leading slash in a path with relURL, Hugo will not prepend the baseURL directory as documented in this issue https://github.com/gohugoio/hugo/issues/10049

For context, see:

- Commit https://github.com/gohugoio/hugo/pull/10002
-  Bug https://github.com/gohugoio/hugo/issues/9994

I only have seen problems in 101 with
- https://github.com/google/docsy/blob/main/layouts/partials/scripts.html#L27
- https://github.com/google/docsy/blob/main/layouts/partials/scripts.html#L31

But I suppose that at least these could have the same problem
https://github.com/google/docsy/blob/main/layouts/partials/scripts.html#L74
https://github.com/google/docsy/blob/main/layouts/partials/head.html#L41
https://github.com/google/docsy/blob/main/layouts/partials/community_links.html#L17
https://github.com/google/docsy/blob/main/layouts/404.html#L5
https://github.com/google/docsy/blob/main/layouts/swagger/baseof.html#L6
https://github.com/google/docsy/blob/main/layouts/swagger/baseof.html#L25
https://github.com/google/docsy/blob/main/layouts/swagger/baseof.html#L26

Tasks:

- [x] #1127
- [ ] #1134

**Comment by LisaFC** [comment]
Thanks for spotting that, does it look like this is a permanent breaking change in Hugo that we'll need to work around/update or something that's likely to go away in a future version?

**Comment by Marzal** [comment]
> Thanks for spotting that, does it look like this is a permanent breaking change in Hugo that we'll need to work around/update or something that's likely to go away in a future version?

As far as I understand from the conversation in the links above, the old behavior (Hugo <101) was an unwanted behavior now fixed.

Here is a good summary of how things are now implemented:
https://github.com/gohugoio/hugo/issues/9994#issuecomment-1153588586

**Comment by chalin** [comment]
Thanks for the detailed report @Marzal! I'm investigating.

**Comment by chalin** [comment]
From https://github.com/google/docsy/pull/1127#issuecomment-1197313702, @Marzal wrote:

> I only have doubts about this one: https://github.com/google/docsy/blob/main/layouts/404.html#L5 `<p>Oops! This page doesn't exist. Try going back to our <a href="{{ "/" | relURL }}">home page</a>.</p>` Some other projects put `""` in similar cases [toppers/hakoniwa@ccdd258#diff-42986cf40ad96f5b7ca39d9b71ba6a9f252656de24cfe82100892ff0f4400f90L4](https://github.com/toppers/hakoniwa/commit/ccdd25845d031ec74b3f188ccdd89474bcd4ce1c#diff-42986cf40ad96f5b7ca39d9b71ba6a9f252656de24cfe82100892ff0f4400f90L4)

From the tests that I've run, surprisingly "/" seems to still work, but that seems odd. Thanks for the reference, I'll give `""` a try.

**Comment by chalin** [comment]
I don't believe that there are any further changes necessary to address this issue. So I consider it closed by #1134.
