### ISSUE TITLE
Offer Docsy as a single Hugo Module

### ISSUE THREAD

**Issue by chalin** [google/docsy#1120]
The intent would be to **streamline use of Docsy for Hugo Module users**, something which (IMHO) makes sense to do now that [Git submodules]() were removed in [0.4.0](https://github.com/google/docsy/blob/main/CHANGELOG.md#040), and NPM-package support is available (#949).

@deining - I can't find the thread, but at some point we discussed the possibility of eliminating the `dependencies` module, which was introduced as a means of addressing:

- #848

This issue is to record that intent, and offer a place for discussing it.

### Tasks

- [x] Module rework: #1217
  - [x] #173 
- [x] #1730
- [ ] #1731
- [ ] User guide updates - #1743
- [ ] Changelog entry marking this as a breaking change for Hugo-module users of Docsy - #1743

### References

- https://github.com/golang/go/issues/37397

**Comment by chalin** [comment]
@deining @geriom - is this something that you might have time to do this quarter, or coach me on how to do it?

**Comment by deining** [comment]
> The intent would be to **streamline use of Docsy for Hugo Module users**, something which (IMHO) makes sense to do now

I agree.

> I'm ok at this point if there isn't a "smooth transition" moving forward for non-Hugo-module projects.

Great. that makes things a lot easier.

I worked on this issue (see PR #1217) and ended up with a consolidation of the two modules into one single `docsy` module, as proposed. With this PR applied, I can successfully run docsy from one single consolidated module. As expected, this single module isn't compatible and breaks existing installations based on npm or git submodules (see [log](https://app.netlify.com/sites/docsydocs/deploys/6311cc541c040b00088f66f2) of failed Netlify preview).

> This issue is to record that intent, and offer a place for discussing it.

I hope my PR can serve as a good starting point for our discussion.

**Comment by chalin** [comment]
> ### Tasks
> * [x]  Module rework: #127
> * [ ]  User guide updates
> * [ ]  Changelog entry marking this as a breaking change for Hugo-module users of Docsy

Now that #1217 is in, can you work on the other tasks too @deining?

**Comment by deining** [comment]
> Now that #1217 is in, can you work on the other tasks too @deining?

Yes, I try to find time during to work on that during the weekend.

**Comment by chalin** [comment]
@deining - FYI, I've address the remaining tasks for this issue, PTAL at:

- #1743
