### ISSUE TITLE
mermaid graphs not working with gitGraph type

### ISSUE THREAD

**Issue by lschierer** [google/docsy#1130]
The following document works as expected:
````
 +++
 title = "History"
 date = 2022-07-26T16:13:48-04:00
 +++
 
 ```mermaid
 graph TD
   commit1 --> commit2
   commit2 --> commit3
```
 
 [^modeline]: # vim: shiftwidth=2:tabstop=2:expandtab
````

this alternate document displays just the title and an otherwise blank page.  

````
+++
title = "History"
date = 2022-07-26T16:13:48-04:00
+++

```mermaid
gitGraph 
  commit 
  commit
  commit
```

[^modeline]: # vim: shiftwidth=2:tabstop=2:expandtab
````

as best I can tell, this implementation of mermaid does not support the gitGraph graph type.  If this is a true statement, consider that a feature request.  If it is something I am doing wrong, please consider it a bug against the documentation (please give an example of how). 

I am using docy by checking it out into my hugo themes directory as a sub repository.  I am currently at commit 1d126ab.  

Thanks!!

**Comment by LisaFC** [comment]
@gwatts you did the Mermaid integration if I remember correctly, do you have time to take a look at this?

**Comment by gwatts** [comment]
Opened PR  #1138 to upgrade Mermaid to the latest version; seems to fix the issue based on some quick local tests

**Comment by LisaFC** [comment]
Thanks Gareth!
