### ISSUE TITLE
Extending Prism to new language is not working

### ISSUE THREAD

**Issue by dorifr** [google/docsy#1139]
Extending Prism to a new language is not working.
I followed the documentation instructions:
1. I updated prism_syntax_highlighting = true in the config.toml file. 
2. I downloaded prism 1.28 with a new language. 
3. I copied the new prism.js and prism.css to static/js and static/css respectively.
4. I ran the command hugo server 
and nothing happens. The old prism 1.21 version was not replaced by the new version. 

I run macOS on M1 MacBook Air.

**Comment by LisaFC** [comment]
@alexearnshaw do you want to take a look at this? Anyone else done much with Prism? I can take a look myself as well.

**Comment by emckean** [comment]
hi! did #1149 fix the problem for you? 

this might also be a place where clearing the Hugo cache might help: https://gohugo.io/commands/hugo_mod_clean/

**Comment by dorifr** [comment]
Hi, 
I fixed it, long ago, by copy pasting the extended language code to the current 1.21 version.
Thanks

**Comment by emckean** [comment]
Thanks for the update!
