### ISSUE TITLE
zbxtable2.0 首页Linux任何资产都没显示,求解决

### ISSUE THREAD

**Issue by tyjin** [google/docsy#1153]
你好，目前安装了最新版zbxtable2.0.登陆进去看，看不到linux主机，日志报错如下：

2022/08/10 10:46:01.769 [C] [panic.go:1038]  the request url is  /v1/host/10
2022/08/10 10:46:01.769 [C] [panic.go:1038]  Handler crashed with error runtime error: index out of range [0] with length 0
2022/08/10 10:46:01.769 [C] [panic.go:1038]  /usr/local/go/src/runtime/panic.go:1038
2022/08/10 10:46:01.769 [C] [panic.go:1038]  /usr/local/go/src/runtime/panic.go:90
2022/08/10 10:46:01.769 [C] [panic.go:1038]  /opt/ss/zbxtable/models/host.go:207
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /opt/ss/zbxtable/controllers/host.go:80
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.3/controller.go:218
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /home/mygo/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:893
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /usr/local/go/src/net/http/server.go:2879
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /usr/local/go/src/net/http/server.go:1930
2022/08/10 10:46:01.770 [C] [panic.go:1038]  /usr/local/go/src/runtime/asm_amd64.s:1581
2022/08/10 10:46:01.771 [server.go:3158]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)

**Comment by LisaFC** [comment]
It looks like this issue was created in the wrong repo!
