### ISSUE TITLE
Google search console should be registered as an Open Source project

### ISSUE THREAD

**Issue by chalin** [google/docsy#1156]
Google search console account should be registered as ~nonprofit~ open source project so that we can turn off ads.

**Comment by LisaFC** [comment]
@emckean do you know how we can do this?

**Comment by emckean** [comment]
I think this is not search console but programmable search? 

Sounds like the 'no ads' option is only available for 501(c)3 orgs :( 
https://support.google.com/programmable-search/thread/76528883?hl=en

**Comment by emckean** [comment]
Filed a bug :)

**Comment by emckean** [comment]
And we are now allowlisted for no ads :)

**Comment by chalin** [comment]
I confirm that there are no more ads! Thanks!

**Comment by emckean** [comment]
filed bug!
