### ISSUE TITLE
card-code has excess margin at bottom

### ISSUE THREAD

**Issue by chalin** [google/docsy#1158]
Visit https://www.docsy.dev/docs/adding-content/shortcodes/#shortcode-card-code-for-programming-code and you'll see:

> <img width="754" alt="image" src="https://user-images.githubusercontent.com/4140793/184356171-d16fd1c1-d155-4d2f-a999-55d3ea822f8d.png">

There's an excess 32px margin at the bottom of the **C** card-code example.

/cc @deining

**Comment by chalin** [comment]
While working on this issue it might make sense to cleanup the excess generated whitespace.

**Comment by 03amir** [comment]
![Screenshot 2022-08-15 230537](https://user-images.githubusercontent.com/84488052/184686351-9c8b5e42-4f5a-466f-9c98-b3b6e4e161c7.png)

Is this is the desired design?

**Comment by chalin** [comment]
Yes, if by that you've removed the "excess 32px margin at the bottom" :).

**Comment by 03amir** [comment]
yes! @chalin can I work on this issue?

**Comment by chalin** [comment]
Sure. I'd like to give @deining some time to respond though, since this is his feature.

**Comment by adisagar2003** [comment]
Hello can I work on this issue?

**Comment by deining** [comment]
> Hello can I work on this issue?

Yes, go ahead, your PR is welcome. Apprecating your efforts, good luck!

**Comment by varun-khachane** [comment]
Hi, is this issue still open? If yes I would like to work on this. Can you assign it to me?

**Comment by chalin** [comment]
Hi @varun-khachane: We don't assign issues in this project. If you would like to contribute please check out our [Contributing Guidelines](https://www.docsy.dev/docs/contribution-guidelines/).
