### ISSUE TITLE
feature request: local search

### ISSUE THREAD

**Issue by roidelapluie** [google/docsy#116]
Hi,

It would be great if docsy could bring along search (e.g. with https://lunrjs.com/).

Other tools do this (https://squidfunk.github.io/mkdocs-material/getting-started/#site-search) and it is fast and useful for medium websites that are not available over the internet.

**Comment by LisaFC** [comment]
Duplicate of #45

**Comment by roidelapluie** [comment]
Sorry thatI missed it!
