### ISSUE TITLE
Ensure Docsy via Hugo module still works after Font Awesome upgrade

### ISSUE THREAD

**Issue by chalin** [google/docsy#1165]
Task of:

- #1171

**Comment by chalin** [comment]
@geriom @deining - could either of you confirm?

**Comment by deining** [comment]
> @geriom @deining - could either of you confirm?

I used HEAD of `docsy` repo, converted the `userguide`dir to module installation and could preview it without problems.

**Dependencies**:

```
$ hugo mod graph
hugo: collected modules in 1452 ms
hugo: collected modules in 1468 ms
github.com/deining/userguide github.com/google/docsy@v0.5.1-0.20221013201501-19ec7be59a8a
github.com/deining/userguide github.com/google/docsy/dependencies@v0.5.0
github.com/google/docsy/dependencies@v0.5.0 github.com/twbs/bootstrap@v4.6.2+incompatible
github.com/google/docsy/dependencies@v0.5.0 github.com/FortAwesome/Font-Awesome@v0.0.0-20220831210243-d3a7818c253f
```

Release 6.2.0 of FontAwesome translates to commit `d3a7818c253f``. 

So coming back to four initial question: yes, modules still work with FontAweSome 6.2. 😄

**Comment by roidelapluie** [comment]
It does not work for me:

```
GET http://127.0.0.1:1313/webfonts/fa-solid-900.woff net::ERR_ABORTED 404 (Not Found)
main.css:1 
```

![off_000](https://user-images.githubusercontent.com/291750/195803423-87a8f3c6-69b9-4b9f-b0c0-9227de01d2bf.png)

```
./hugo mod graph
github.com/o11ydev/prometheus-workshop github.com/google/docsy@v0.5.0
github.com/o11ydev/prometheus-workshop github.com/google/docsy/dependencies@v0.5.0
github.com/google/docsy/dependencies@v0.5.0 github.com/twbs/bootstrap@v4.6.1+incompatible
github.com/google/docsy/dependencies@v0.5.0 github.com/FortAwesome/Font-Awesome@v0.0.0-20210804190922-7d3d774145ac

```

**Comment by deining** [comment]
As stated in #1281, there are some issues I overlooked.
Reopening the issue and investigating ...

**Comment by deining** [comment]
I just submitted PR #1282. Once this PR is merged, module installation should work without any flaws.

**Comment by geriom** [comment]
Merging #1284 solved this issue for me. If no further problems are reported we can can close it.
