### ISSUE TITLE
Netlify build: select a newer build image

### ISSUE THREAD

**Issue by chalin** [google/docsy#1166]
Netlify build logs now contain the following notice:

> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
> All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
> 
> To avoid service disruption, please select a newer build image at the following link:
> https://app.netlify.com/sites/docsydocs/settings/deploys#build-image-selection
> 
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by emckean** [comment]
New build image is Ubuntu Focal 20.04 (default), just selected it, 🤞 nothing breaks ...

**Comment by chalin** [comment]
If you force a rebuild of the latest production build you'll be able to know right away if something breaks. Have you tried that yet?

**Comment by emckean** [comment]
I forced a new deploy of Goldydocs and things look ok? I'll do Docsy.dev now :)

**Comment by chalin** [comment]
The warning is gone from recent preview-build logs, so I think that this issue has been resolved. Thanks! Closing.
