### ISSUE TITLE
Use the gtag.js analytics library by default

### ISSUE THREAD

**Issue by chalin** [google/docsy#1177]
**Universal Analytics (UA) is [officially deprecated]**:

- Data collection will stop on July 1st, 2023
- Six months after that, historical data will be gone too

The sooner projects migrate to Google Analytics 4 (GA4), the better.

As a first step in supporting projects' migration from UA to GA4, Docsy should, by default, use the [gtag.js] analytics library -- the only library supported by GA4 -- for all site tags.

This is a proposed concrete step in support of:

- #1096

[officially deprecated]: https://support.google.com/analytics/answer/11583528
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs

**Comment by geriom** [comment]
PR reverted after seeing some errors. https://github.com/google/docsy/pull/1212

I'll take a closer look and try to figure out what went wrong.

**Comment by chalin** [comment]
In https://github.com/google/docsy/pull/1178#issuecomment-1258157495, @geriom wrote:

> Turns out this was not the issue, it was circumstantial evidence. I noticed the problem immediately after merging this but this did not introduce that problem. Sorry @chalin
> 
> Feel free re-submit this PR.

Ok, will do as soon as I can.
