### ISSUE TITLE
Ensure that versions of dependencies remain in sync

### ISSUE THREAD

**Issue by chalin** [google/docsy#1182]
We need to ensure that versions of dependencies remain in sync across installation options, namely:

- Hugo modules
- NPM packages
- CDN

**Comment by deining** [comment]
> We need to ensure that versions of dependencies remain in sync across installation options, namely:
> 
>     * Hugo modules
> 
>     * NPM packages
> 
>     * CDN

I agree.

Just created PR #1218 in order to achieve that for now.
