### ISSUE TITLE
drawio support should be opt-in not opt-out

### ISSUE THREAD

**Issue by chalin** [google/docsy#1185]
All of Docsy's other optional features are opt-in. The same should be true of draw.io.

- Support was added via #529

Tasks:

- [ ] Remove setting from Docsy config: 
  https://github.com/google/docsy/blob/215f68033bbc7bddf8dbec2bbabf8749d1998a17/config.yaml#L9-L10
- [ ] Add setting to UG config
- [ ] Update the docs to let users know how to opt-in: 
  https://docsy.dev/docs/adding-content/diagrams-and-formulae/#diagrams-with-diagramsnet

/cc @LisaFC @gwatts

**Comment by H20220009** [comment]
Hi, is this issue still open?
I want to work on this issue; please assign me to this.

**Comment by chalin** [comment]
Hi. We don't assign issues in this project. If you would like to contribute read through our [guidelines](https://www.docsy.dev/docs/contribution-guidelines/).
