### ISSUE TITLE
Blog pages should contain `page-meta-lastmod.html` too

### ISSUE THREAD

**Issue by chalin** [google/docsy#1196]
@LisaFC et all: are you aware of any reason why blog pages don't contain "last mod" info like regular doc pages do?

Some context:

- `_default`: https://github.com/google/docsy/blob/519930cf0d642c37941b74a25361e743165f94bc/layouts/_default/content.html#L19
- The blog [`content.html`](https://github.com/google/docsy/blob/main/layouts/blog/content.html) override omits `page-meta-lastmod.html`

If there's no reason that you're aware of to omit that info at the bottom of the page, I suggest that we add it. Thoughts?

**Comment by chalin** [comment]
I've quickly experimented with this and it looks best if we end the `<div>` in https://github.com/google/docsy/blob/main/layouts/blog/content.html with `page-meta-lastmod.html` last:

```
{{ partial "pager.html" . }}
{{ partial "page-meta-lastmod.html" . }}
```

For example:

> <img width="782" alt="image" src="https://user-images.githubusercontent.com/4140793/186265458-332ba00c-1958-445f-87dc-6848ec173316.png">

**Comment by LisaFC** [comment]
Happy to add it if you think it's useful - I think the main reason we didn't was that blog posts tend not to be updated (unless someone discovers an error post-publication) and have a publication date already. If they're being regularly updated they probably have content that should be in regular user docs. :)

Can't remember the issue/PR I commented on but I also think we should probably have a different "page meta links" for blog posts as most projects probably don't want to be inviting other users to edit guest blog posts. Thoughts?
