### ISSUE TITLE
Warning `Replace Autoprefixer browsers option to Browserslist config.`

### ISSUE THREAD

**Issue by aLekSer** [google/docsy#120]
# Steps to reproduce

Run `hugo --config config.toml` from the root of the project.

Results in the following output:
```
Building sites …
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
                   | EN
-------------------+-----
  Pages            |  7
  Paginator pages  |  0
  Non-page files   |  0
  Static files     | 36
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0
```
# What you expected to happen
No warning messages.

# Versions
Autoprefixer is at the latest version 9.6.1

**Comment by LisaFC** [comment]
I'll take a look, thanks for letting me know!

**Comment by LisaFC** [comment]
Looks like it's coming from Autoprefixer's latest release, the browsers option is deprecated: https://github.com/postcss/autoprefixer/releases/tag/9.6.0

I'll follow their instructions to update. Thanks for reporting this!

**Comment by LisaFC** [comment]
So I think this is an issue with your project, as I've checked, and I don't have the browsers option in either the Docsy guide or the Docsy example project's package.json, both of them build without this warning. If you follow the update instructions in the Autoprefixer doc I linked above to migrate your package.json you should be good. Feel free to reopen if it doesn't work.

**Comment by aLekSer** [comment]
Hello, I opened this issue based on clean Docsy repo.
https://github.com/google/docsy/blob/3ca22ac9a0b7e4b4faf54cd4f4ab272695f1516a/postcss.config.js#L20
You could see the outdated browserlist here above.

**Comment by LisaFC** [comment]
Aha, sorry about that, I was looking in the wrong file. Will update!

**Comment by aLekSer** [comment]
How to reproduce cd to Docsy repo:
```bash
$ pwd
/Users/a/go/src/github.com/docsy
$ hugo --config config.toml
Building sites …
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist



                   | EN
-------------------+-----
  Pages            |  7
  Paginator pages  |  0
  Non-page files   |  0
  Static files     | 36
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Total in 1444 ms

```

**Comment by LisaFC** [comment]
Thanks, I'll have a fix in shortly

**Comment by MattiaMontanari** [comment]
Hey @LisaFC, I'm having the same issue:
```
hugo --config config.toml
Building sites … 
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.
  Using browsers option can cause errors. Browserslist config 
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.
  If you really need to use option, rename it to overrideBrowserslist.
  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
                   | NO | EN  
-------------------+----+-----
  Pages            | 77 | 44  
  Paginator pages  |  0 |  0  
  Non-page files   |  1 |  3  
  Static files     | 36 | 36  
  Processed images |  2 |  7  
  Aliases          |  1 |  2  
  Sitemaps         |  2 |  1  
  Cleaned          |  0 |  0  
```
I'm trying to deploy with gitlab the [example project](https://github.com/google/docsy-example) using `klakegg/hugo:ext-alpine` as image.

**Comment by LisaFC** [comment]
Thanks for reminding me!

You shouldn't have a problem with your site until then, it's a deprecation warning rather than it actually not working, but I'll try to get something in that stops the warning.

**Comment by MattiaMontanari** [comment]
Actually, the whole site is not [rendering properly.](https://mmontanari.gitlab.io/testdocsy/). I'm not sure if I am doing something terribly wrong. The project is available [here](https://gitlab.com/mmontanari/testdocsy).

**Comment by LisaFC** [comment]
Hmm, that's odd, it's like you have no CSS. I'll have a look.

Just FYI my build command for continuous deployment with Netlify (used for the example site) is:
`cd themes/docsy && git submodule update -f --init && cd ../.. && hugo`

because I need Netlify to pull the theme submodules (including all the PostCSS stuff) before running hugo to build the site, so it might be something like that.

Any other users building from GitLab with a Docker file like Mattia?

**Comment by MattiaMontanari** [comment]
Thanks Lisa for looking into this. I found and forked a [project that does the same thing ](https://gitlab.com/mmontanari/rpi-droid.gitlab.io) with Gitlab (not with Netlify). While the template project renders properly, the one I forget doesn't.. could this be the result of a very recent change in one of the libraries?

**Comment by MattiaMontanari** [comment]
Solved. My bad: I didn't set the correct `baseURL` in `config.toml`. May be worth documenting it this as  with Gitlab Pages it's very easy to ignore this.

**Comment by LisaFC** [comment]
We don't have a specific deployment with GitLab Pages section so if anyone would like to add one to the Previews and Deployment page....? (hint hint)
