### ISSUE TITLE
Is there a default way to add Cookie conscent message when the website loads up for the first time?

### ISSUE THREAD

**Issue by Aravinda93** [google/docsy#1215]
Hello,

I am using the `Hugo` with `Docsy` theme to develop a simple website consisting of multiple pages. I would like to add a `Coockie Conscent` message which shows some message with button `ok`. The website does not use any coockie so I would like to show the message `website does not use any coockie` and a button `ok`.

I would like to show it only once when user opens the website and should not be displayed when user moves to different pages in the same session. Is there a out of the box approach from Docsy for the same? if not then can someone please provide some reference as I am new to Docsy and could not find something similar on the documentation.

Thanks a lot in advance.

**Comment by emckean** [comment]
There isn't a cookie-consent feature in Docsy, but there are some add-ons for Hugo -- check out https://discourse.gohugo.io/t/here-is-an-easy-to-install-cookie-consent-banner-for-gdpr-compliance/34411 which you may be able to modify for your needs.

Also check out the "customizing templates" section of the docs: https://www.docsy.dev/docs/adding-content/lookandfeel/#customizing-templates

Good luck!

**Comment by Aravinda93** [comment]
@emckean Thanks a lot for the response. I tried the approach you have mentioned above and followed the steps mentioned in the [Cookie consent | Hugo Codex](https://hugocodex.org/add-ons/cookie-consent/). I am facing some styling issues with `Cookie Consent Banner`.

Ideally, I would like the banner to be visible something like this:

[![enter image description here][3]][3]


But currently its looking something like this:
[![enter image description here][4]][4]



I have added it along with styles and `partials`. Maybe some style is messing up the child `cookie consent` styles but unable to figure out the same. Can you please let me know what am I doing wrong here?

I have added my complete code in following github project:
https://github.com/Aravinda93/hugo-docsy-learn

I am quite new to Hugo and Docy so getting bit confused on the folder and file structure hence unable to figure out which parent style is messing up my `Cookie consent` modal.


  [1]: https://github.com/gohugoio/hugo
  [2]: https://github.com/google/docsy
  [3]: https://i.stack.imgur.com/1gslp.png
  [4]: https://i.stack.imgur.com/cgXst.png
