### ISSUE TITLE
Create new site failed

### ISSUE THREAD

**Issue by qmhu** [google/docsy#1219]
I run this commends by following doc:https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/
```
git clone https://github.com/google/docsy-example.git my-new-site
cd  my-new-site
hugo server
```

but it failed 

```
Error: from config: failed to resolve output format "print" from site config
```

Meanwhile my other sites also start failed , the error is like 
```
/my-new-site/content/en/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

**Comment by Aravinda93** [comment]
I tried the same steps and everything seems to be running fine. Please ensure following things:

1. Hugo has been installed correctly and Extended version has been installed. Run `hugo version` and should see something like this `hugo v0.101.0+extended darwin/amd64 BuildDate=unknown`.

2. Ensure you do not have any other application running in port 1313 which is default for the hugo server, if occupied then change the port by `hugo server -p 9005`.

**Comment by qmhu** [comment]
retry the same steps in next day, it works...
