### ISSUE TITLE
Accessibility add alt to image

### ISSUE THREAD

**Issue by Arhell** [google/docsy#1253]
https://github.com/google/docsy/blob/main/layouts/shortcodes/imgproc.html#L15

**Comment by deining** [comment]
Looking at the shortcode, I realize that the `<img>` element is embedded into a `<figure>` element with a nested `<figcaption>` element. As stated [here](https://www.tpgi.com/short-note-alt/), it is valid to omit the `<alt>` tag in that case. Would be a nice addition to add the `<alt>` tag, though. Are you able to provide a PR for that?

*Additional note:* when looking at the shortcode source, I wonder why `Crop` isn't available as image processing command. That would be a nice addition to your PR IMHO.
