### ISSUE TITLE
Question: "index.xml" files and Google indexing issue

### ISSUE THREAD

**Issue by heinrich-ulbricht** [google/docsy#1254]
When looking in the Google search console for a docsy site dozens of entries in the category **Page Index** -> **Crawled - not indexed** appear. The all end with **index.xml** which in my understanding is there for RSS support.

Is there a recommendation on how to deal with that? Should all "index.xml" be excluded from the search index? I'd like to get rid of those errors and wonder if there is something in docsy that could generate the correct output, e.g. in a `robots.txt`.

**Comment by LisaFC** [comment]
Yes, they're XML RSS feed files and they're generated by default by Hugo, with a default template (also presumably you don't want them to be indexed, so RSS feed URLs being crawled but not indexed is a bit noisy but better than XML duplicates of your content showing up in search results)

If you don't want RSS feeds generated at all, you can just switch them off:
https://www.docsy.dev/docs/adding-content/content/#rss-feeds

**Comment by chalin** [comment]
Can this be closed?

**Comment by heinrich-ulbricht** [comment]
If there is no further official advice on how to  avoid the Google crawl warnings, yes.

**Comment by chalin** [comment]
Sorry, I hadn't read the details. I thought that @LisaFC had answered the question. Let me take a look ...

**Comment by chalin** [comment]
Which site is this for? (If you are able and willing to share.)

Looking at some of our sites, which are built with Hugo+Docsy and that have RSS feeds: I'm not seeing any error in the search console. As far as I know, we're not doing anything special w.r.t. the `robots.txt` file, for example.

**Comment by LisaFC** [comment]
So if I dig down I do see those warnings for the Docsy site itself in the search console - look under Page Indexing > Crawled: currently not indexed and there are a few RSS feed URLs (not sure if you can see this: https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.docsy.dev%2F&item_key=CAMYFyAC&hl=en)

I think one issue is that it's not strictly an error, the few things I've read about getting rid of warnings in the search console has said that RSS feed URLs showing up as "crawled but not indexed" is to a certain extent "working as intended" (as in you don't *want* RSS feeds to be indexed - while you might worry about your "real" site pages showing up with that error!). 

If you don't need the RSS feeds then the simplest way to get rid of the warning is by switching off generating the feeds. If you do want RSS feeds but don't want them crawled you can set up your own robots.txt - it's probably not something we should specify at Docsy level as some users may want them to be crawlable, I believe it certainly used to be the case that crawlable RSS feeds helped Search identify new content for frequently updated sites.   Does that help?

**Comment by heinrich-ulbricht** [comment]
Yes, thank you. I'll probably use a robots.txt then.
