### ISSUE TITLE
Support for Algolia Docsearch as alternative to GCSE?

### ISSUE THREAD

**Issue by alexearnshaw** [google/docsy#126]
Wondering if this project would be interested in offering support for an alternative search - [Algolia DocSearch](https://community.algolia.com/docsearch/) is free for public documentation projects and is an easy to implement alternative to Google GCSE which is not ad-supported.

You basically just sent a request to Algolia to be added to the program, and (if accepted) they email you back some Javascript code which you add to the head end and body end.

To get this working in my project I ended up adding a new config parameter to config.toml and then overriding the search-input partial in my own project. However, I think the same end result could be achieved by just adding an additional `with` statement to Docsy's search-input partial?

Also I wasn't able to get Algolia's search working with the Search box on the left nav/sidebar so I disabled this in config.toml but it works fine on the top nav search box.

You can see the changes I made to get this working (after getting the Javascript code for my site from Algolia) in this PR https://github.com/Axway/axway-open-docs/pull/113

You can see the end result and try out the Algolia search here https://axway-open-docs.netlify.com/

If there's interest I'd be happy to submit a PR to this project with the needed changes/doc.

**Comment by LisaFC** [comment]
Oh that's really nice! Yes, it would be great if we could provide this as an option.

**Comment by alexearnshaw** [comment]
@LisaFC I've had a go at this in PR #127, I'd appreciate your input.

**Comment by LisaFC** [comment]
Oh brilliant, I'll take a look!

**Comment by LisaFC** [comment]
Fixed in #127
