### ISSUE TITLE
Get Popper from Bootstrap bundle

### ISSUE THREAD

**Issue by chalin** [google/docsy#1265]
_Originally posted by @chalin in https://github.com/google/docsy/issues/1264#issuecomment-1272329319_

>  In fact, I don't think that we should be fetching and including Popper separately, we should use the Bootstrap bundle, which includes Popper (and more).

**Comment by smxwyb** [comment]
> _أرسلها في الأصل@chalinفي [# 1264 (تعليق)](https://github.com/google/docsy/issues/1264#issuecomment-1272329319)_
> 
> > في الواقع ، لا أعتقد أنه يجب علينا جلب Popper وتضمينه بشكل منفصل ، يجب أن نستخدم حزمة Bootstrap ، والتي تتضمن Popper (والمزيد).
