### ISSUE TITLE
Reactivate code-block copy feature

### ISSUE THREAD

**Issue by chalin** [google/docsy#1267]
- #1245 introduced a click-to-copy button for code blocks
- Due to the issues reported in #1264, the feature had to be disabled
- Once we upgrade Bootstrap (#470), consider reactivating the click-to-copy feature.
- Other points to consider:
  - Make the feature inclusion configurable via a config param, since some projects might have and prefer to continue using their own code-copy button.
  - Add a note to the changelog when the feature is added, so that projects are more likely to find out about this nifty new feature!

Related:

- Possible feature interaction?
  - #292
  - #325
- #1266

/cc @geriom

**Comment by kimberleybrown** [comment]
Looking forward to this once it's been finalized! :)

**Comment by jlian** [comment]
+1, would like to stick with Chroma

**Comment by chalin** [comment]
@geriom - could the JS code be simplified by using BootStrap's popovers (which are built atop of the Popper package)? I haven't looked at the code in detail.

**Comment by geriom** [comment]
I'm going to take a look and see what I can do.
