### ISSUE TITLE
Docsy v0.5.0 - Build error after auto update

### ISSUE THREAD

**Issue by kimberleybrown** [google/docsy#1273]
Hello,

We have followed the instructions found on migrating Docsy to a module in our project. However, today when building our project, we see that Docsy is automatically upgrading from v0.04.0 => v0.5.0 which is causing our builds to fail. The changelog from Docsy's most recent commit explains that there are breaking changes, which causes our projects to fail when running `hugo server`. We get the following error in our terminal:

`Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: docs/single.html:30:7: executing "docs/single.html" at <partial "scripts.html" .>: error calling partial: "C:\Users\user~1\AppData\Local\Temp\hugo_cache\modules\filecache\modules\pkg\mod\github.com\google\docsy@v0.5.0\layouts\partials\scripts.html:51:16": execute of template failed: template: partials/scripts.html:51:16: executing "partials/scripts.html" at <resources>: can't evaluate field GetRemote in type interface {}  `

Furthermore, the page in the documentation on [https://www.docsy.dev/docs/updating/convert-site-to-module/](url) doesn't make it clear that converting to a module forces users to take on every new release once it is active. Therefore, above the issue explained earlier, we see the following:

1. We want the power to be able to vet the Docsy releases on our own without being forced auto-update when there is a new release.
2. If we already ran `hugo server` and now being forced to run v0.5.0, we are not able to revert the go.mod file back to call v0.4.0, as each time we run `hugo server` the error above is being called from v0.5.0 release.

**Comment by kimberleybrown** [comment]
Update on issue findings: 

It doesn't seem to stem from the Hugo version.

The error seems to appear when you have the `_vendor` directory active but do not vendor Docsy. The issue, for us locally, is when you have vendor common modules but do not include Docsy in it.

**Comment by deining** [comment]
> The error seems to appear when you have the `_vendor` directory active but do not vendor Docsy.

Were you able to overcome your problems? Hard to judge what is/was going on here. If there is any `vendor` directory present, the contents of this dir will take precedence over the downloaded files in the module cache.

_Just as a note to readers of this issue_: When using module installation of `docsy` theme, there is **no** auto-update of docsy theme! Update only happens if you actively opt for it. Also, when using a module installation, you can always go back and forth between releases and even revisions, as documented [here](https://www.docsy.dev/docs/updating/updating-hugo-module/). Indeed, one of the strength of module installation is the flexibility in that regard.

**Comment by chalin** [comment]
Hi @kimberleybrown. I haven't read through all the details in this issue, but I thought that I'd drop a quick note: have you tried with 0.5.1, which is an official release. 0.5.0 was broken and never officially released. /cc @geriom

**Comment by kimberleybrown** [comment]
Hi @chalin, thanks for checking in. We have been able to successfully upgrade to v0.5.1 and it is running smoothly so far.

**Comment by chalin** [comment]
I'm glad that it is working smoothly now. I'll close this issue then. Feel free to open another if something arises.
