### ISSUE TITLE
Howto in Hugo/Docsy - Using FontAwesome Pro instead of free version?

### ISSUE THREAD

**Issue by kimberleybrown** [google/docsy#1283]
Hello!

Hoping this isn't too much of a basic question, but I was wondering how we could use a pro version of FA if we have access to one? 

I've seen some information on the FA website indicating that you could use npm and call your personal token, but the commands don't do anything when I've used them in a project (unless I'm using it wrong?). 

Has anyone here used a pro version instead of the free one and have gotten it successfully working?

Thanks!

**Comment by jmichelgarcia** [comment]
Hi, a better place for this question might be on https://github.com/google/docsy/discussions since this is not related to an issue with the theme. :

**Comment by nryberg** [comment]
See Discussion https://github.com/google/docsy/discussions/1446 for solution

**Comment by chalin** [comment]
Great, thanks @nryberg! I'll close this issue. Post to the discussion thread if there are further questions.
