### ISSUE TITLE
including tabpane content via readfile assigns duplicate HTML IDs

### ISSUE THREAD

**Issue by polarweasel** [google/docsy#1289]
If we include `tabpane` content from more than one file (in this case, using the `readfile` shortcode), every tab pane gets the same HTML ID, and the tabs don't work correctly. (Click a tab in one pane, and the _tab_ switches but not the _content_, but the content switches in another pane without switching its tab...)

Here's a [PR preview](https://deploy-preview-14425--infallible-bardeen-164bc9.netlify.app/preview/tabpane-include/) showing this. (Associated PR is https://github.com/yugabyte/yugabyte-db/pull/14425)

I don't think this is related to #1280, but maybe @deining or @chalin you have some ideas on how to fix this?

**Comment by deining** [comment]
Thanks for the clear description of your issue. 

> but maybe @deining or @chalin you have some ideas on how to fix this?

Yes, I do have some ideas already, and I'm pretty confident I can provide a fix for this issue in one way or the other.

> I don't think this is related to #1280,

No, #1280 and the issue raised by you are quite different.

Stay tuned, I will have a look at this shortly.

**Comment by polarweasel** [comment]
Thank you, @geriom and @deining! Looking forward to release 0.5.0, as it will solve several issues we're having. 👍

**Comment by polarweasel** [comment]
(Update: we are now using 0.5.1 in production. Thanks!)
