### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by geriom** [google/docsy#1290]
- [x] Prepare hugo modules
- [x] Update `package.json`
- [x] Update `config.yaml`
- [x] Update Changelog
- [x] Create and test new tags
- [x] Create and publish the new release 🎉
- [ ] https://github.com/google/docsy-example/pull/188

**Comment by geriom** [comment]
Docsy v0.5.1 released: https://github.com/google/docsy/releases/tag/v0.5.1

**Comment by deining** [comment]
@geriom: Can we please update the exampe site to the newly released version? A corresponding [PR](https://github.com/google/docsy-example/pull/188) exists already. Thanks.

**Comment by geriom** [comment]
Thanks for opening that PR. Approved and merged.
