### ISSUE TITLE
tabbed content broken with recent changes

### ISSUE THREAD

**Issue by samdulam** [google/docsy#1295]
With latest updates to `tab.html` and `tabpane.html` tabbed content looks like below
![image](https://user-images.githubusercontent.com/58716812/198185819-ef455ca3-e625-4bfa-ad54-6365cea359c6.png)

Manually creating those files in my project layouts/shortcodes using code from commit [1b10f6b](https://github.com/google/docsy/commit/1b10f6bebef9ad732e34a04f63ec7087d0ca1ee3) fixes the issue.

**Comment by polarweasel** [comment]
@deining @chalin this is a big regression on tabpanes, and is breaking what I was hoping to fix by upgrading to 0.5.1...

**Comment by polarweasel** [comment]
Further details:

When you render a tabpane **directly**, it looks like what @samdulam posted, and the tabs are functional.

When you include a tabpane **by reference** using `readfile`, the appearance is the same, but the tabs are non-functional.

I'm playing with this in yugabyte/yugabyte-db#14694 if you want a live example. (Can't do the upgrade until this is resolved anyway, so we may as well use it for experimentation!)

**Comment by deining** [comment]
I just investigated your case, thanks for providing the repo!

With version 0.5.1, a breaking change in tabpanes was introduced: the parameter `code` was replaced by `text`.

@polarweasel: In your case this means, inside `managed-quick-start-include.md` you have to replace line 3:

```
tabpane code=false
```

with

```
tabpane text=true
```

Then have a look at your site preview, your tab should display correct again!

**ToDo**: This breaking change is undocumented yet, I will add a paragraph to `CHANGELOG.md` shortly.

Sorry for any confusion caused!

**Comment by deining** [comment]
> **ToDo**: This breaking change is undocumented yet, I will add a paragraph to `CHANGELOG.md` shortly.

Done with PR #1298.

**Comment by polarweasel** [comment]
Thanks so much, @deining!

**Comment by chalin** [comment]
Yes, thanks! Can this issue be closed?
