### ISSUE TITLE
POSTCSS error: `GLIBC_2.27' not found (required by node)

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#1296]
Hi all,

I'm trying to deploy our docs to Amazon. I use the latest Node LTS. Getting this error as of today:

POSTCSS: failed to transform "scss/main.css" (text/css): node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)

Did anyone encounter this? Any ideas how to solve?

Thanks

Arnon

**Comment by emckean** [comment]
Hi! this seems like an AWS issue, does [this SO question](https://stackoverflow.com/questions/72022527/glibc-2-27-not-found-while-installing-node-on-amazon-ec2-instance) help?

**Comment by rkJun** [comment]
Amazon Linux 2 or some os includes Glibc 2.26 or under.
To use a higher glib version,
need to consider other AMI.
for example) Amazon Linux 2022.

reference : https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2

**Comment by arnonzooz** [comment]
Hi, 

Thanks for the replies! 

For now I had to revert to using an older Node version. That did the job, though admittedly it still concerns me a bit. Would have preferred to stay on the latest Node version.

Closing this issue.

Thanks again.

Arnon
