### ISSUE TITLE
docsy-users mailing list: how to subscribe to it?

### ISSUE THREAD

**Issue by aborruso** [google/docsy#130]
Hi,
when I try to subscribe to it from [here](https://www.docsy.dev/community/) I have

![image](https://user-images.githubusercontent.com/30607/65355816-207b5400-dbf3-11e9-920a-c46b5fa521ca.png)

Thank you

**Comment by LisaFC** [comment]
Ah, well spotted, I didn't have the permissions set up properly. Try again now and let me know if it works.

**Comment by aborruso** [comment]
Now it's possible to apply.

Thank you
