### ISSUE TITLE
Regression in offline search popover on v0.5.1

### ISSUE THREAD

**Issue by jmichelgarcia** [google/docsy#1304]
**v.0.5.1**
![search-hugo](https://user-images.githubusercontent.com/2745523/199637310-cdfae9e6-d669-404e-bb0f-b3123ace6d63.gif)

**v0.4.1-0.20220713143414-1b10f6bebef9**
![hugo-v0 4](https://user-images.githubusercontent.com/2745523/199637532-82670c96-0bbd-4be4-8db7-251b13a87e6f.gif)

**config.toml**
```
[params]
offlineSearch = true
offlineSearchSummaryLength = 200
offlineSearchMaxResults = 25
sidebar_search_disable = false
```

**Source**
https://github.com/jmichelgarcia/docsy-algolia

**To reproduce**
1. Go to https://sensational-chebakia-db2125.netlify.app/
2. Type `Test` in the search
3. Scroll down

**Comment by jmichelgarcia** [comment]
Between the two screenshots, there is no change beyond the below:

```
➜  my-new-site git:(main) hugo mod get -u github.com/google/docsy@1b10f6bebe
go: downgraded github.com/google/docsy v0.5.1 => v0.4.1-0.20220713143414-1b10f6bebef9
```

**Comment by tekezo** [comment]
Thank you for feedback.

I guess this is an issue with the bootstrap update.
I've created a PR for the fix. #1305 

@chalin @LisaFC Could you review the PR?

**Comment by chalin** [comment]
Thanks for the detailed report @jmichelgarcia. Let us know if this fix worked for you. Thanks for the fix @tekezo.

**Comment by tekezo** [comment]
@chalin Thanks for reviewing!

@jmichelgarcia I've confirmed the fix with the following version specification:

```shell
hugo mod get github.com/google/docsy@e6a44dff7eb73ee4abd058ca0ee6dc7d18a941f1
```

**Comment by jmichelgarcia** [comment]
It's puuuurfect. Thank you folks
