### ISSUE TITLE
Configuring search: Google CSE seems not work

### ISSUE THREAD

**Issue by aborruso** [google/docsy#132]
Hi,
I have added this variable to netlify (as I have read [here](https://www.docsy.dev/docs/adding-content/navigation/#setting-up-site-search)).

![image](https://user-images.githubusercontent.com/30607/65405659-1ddc5280-dddd-11e9-97e8-f2e3a123738c.png)

I have the `search.md` file, I have added my gcs_engine_id to `config.toml` file, but after 5 days I still have no results.
What could be the problem?

Thank you

**Comment by LisaFC** [comment]
That's very strange.

1)Double check that your pages don't have a NOINDEX on them - if you look at the source they should have:
<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
2)You can force a (re)crawl of your site by following the instructions here:
https://support.google.com/webmasters/answer/6065812?hl=en

Let me know if that doesn't work and I'll see if I can figure out what's going on

**Comment by aborruso** [comment]
Hi,
I have `<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">` (it's a website under construction https://arigadicomando.netlify.com/).

I will try with recrawl.

Thank you

**Comment by aborruso** [comment]
The problem was simple. I have had this useful reply:

> Your website contents has not been seen my Google bot yet and it's not serving in Google.com results. Since, it's not serving in Google.com results, CSE is also not serving results.
>
>Recommend you to please create a sitemap with all your website contents and submit the sitemap for indexing through Google Search Console: https://support.google.com/webmasters/answer/183668?hl=en
>
>Once indexed, your contents will start serving in your CSE results as per the "Sites to search" configuration.

**Comment by LisaFC** [comment]
Great, glad you got useful info!
