### ISSUE TITLE
failed to transform mermaid.js at jsonify

### ISSUE THREAD

**Issue by multun** [google/docsy#1321]
Hello there! While testing a patch, I found out that the website I'm working on (which only uses docsy) does not build anymore on the development branch. I use the latest [docker-hugo with ext-alpine](https://github.com/klakegg/docker-hugo) and a submodule workflow.

I ran a bisect and found out this error only happens since 90843e360b921ea8417995e0261a355f2f3aed7a (from #990, by @stephanlachnit)

## Symptoms

This warning (always)
```
.Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}
```

This error (when there's a rebuild server running)
```
Rebuild failed: EXECUTE-AS-TEMPLATE: failed to transform "js/mermaid.js" (text/javascript) at <jsonify>: error calling jsonify: json: error calling MarshalJSON for type page.Page: unsupported type: func() page.Pages
```

And when building from scratch, I get an horribly long strack overflow trace which recursively loops on `page.MarshalPageToJSON` / `MarshalJSON`

## Reproducer

```sh
# get the site source
git clone --recurse-submodules git@github.com:DGEXSolutions/osrd-website.git
cd osrd-website
# checkout the failing revision
(cd themes/docsy; git reset --hard 90843e360b921ea8417995e0261a355f2f3aed7a)
# npm install dependencies
docker run --rm -it -v $(pwd):/src -w /src/themes/docsy --entrypoint npm klakegg/hugo:ext-alpine install
# build the thing
docker run --rm -it -v $(pwd):/src -p 1313:1313 klakegg/hugo:ext-alpine server
```

**Comment by deining** [comment]
Most likely, this is due to a know bug addressed in (and hopefully fixed by) #1316.

**Workaround:**

Remove these two lines from your `config.toml`.

```
[params.mermaid]
enable = true
```
https://github.com/DGEXSolutions/osrd-website/blob/9e04989c0ebddd5d42bbbb7083db1362e3e5dc90/config.toml#L153-L154

And make sure you use a hugo version >= 0.93.0 (your `netlify.toml` specifies outdated hugo version 0.88.1).

Does this cure your problem?

**Comment by multun** [comment]
Yup, you're indeed correct, thanks!

**Comment by multun** [comment]
(to clarify, we're not using netlify, it's an artifact from the past, I closed the issue because the proposed workaround and fix both work)
