### ISSUE TITLE
Can't override community_join or community_introduce

### ISSUE THREAD

**Issue by andrewrynhard** [google/docsy#1331]
I can't seem to find a way to set/override community_join and community_introduce in https://github.com/google/docsy/blob/main/layouts/community/list.html.

**Comment by dfranco** [comment]
Hi @LisaFC ,

Could you provide a link to the documentation on how to override the community page layout please ?

Thanks for your feedback

**Comment by LisaFC** [comment]
Hi there - I've actually discovered an even neater way to override the strings, which is to create your own little English-language strings file with just your preferred community text in it - no need to override the entire page. See: https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-2-i18n-string-localization/#hugo-filesystem-and-string-localization

So for your use case, you'd create a file in your project called `i18n/en.toml` with something like just the following in it:

```
# Community
[community_join]
other = "My custom {{ .Site.Title }} community text"
[community_introduce]
other = "Even more custom text!"
```

Let me know if that works!

If you want to override the entire layout instead, you need to create your own `/layouts/community/list.html` file (and/or `/layouts/partials/community_links.html` if you want to do your own version of the links section) in your project - either copy and edit the Docsy version of the file(s) or build your own!

**Comment by dfranco** [comment]
> Let me know if we can close this now.

Hi @LisaFC,

I'll have a try this evening and let know how it goes.

Thanks for your precious feedback by the way, and happy new year too 🎉

**Comment by dfranco** [comment]
HI @LisaFC,

It doesn't seems to work for me :(

I'll have another try later today and keep you updated.

**Comment by LisaFC** [comment]
Can you let me know a bit more about what you're trying to do (ie are you just trying to customize the wording or some of the actual layout of the page?)

Here's a simple example I did in a test site for changing the wording:
* Added this file to my project: https://github.com/LisaFC/bimble/blob/master/i18n/en.toml
* Intro wording changes in the rendered site! https://statuesque-llama-927745.netlify.app/community/

**Comment by dfranco** [comment]
> Can you let me know a bit more about what you're trying to do (ie are you just trying to customize the wording or some of the actual layout of the page?)
> 
> 
> 
> Here's a simple example I did in a test site for changing the wording:
> 
> * Added this file to my project: https://github.com/LisaFC/bimble/blob/master/i18n/en.toml
> 
> * Intro wording changes in the rendered site! https://statuesque-llama-927745.netlify.app/community/

I'm just trying to change the link to the contribution guide on a "community" page type

I'll have another try later today and let you know

**Comment by LisaFC** [comment]
Aha, so you want the Contribution Guide link to point somewhere other than `/docs/contribution-guidelines` (the default)?

So that's actually hard-coded (maybe it shouldn't be), so you'll need to create a copy of this file in your project:
https://github.com/google/docsy/blob/main/layouts/partials/community_links.html

...and then edit this line:
https://github.com/google/docsy/blob/main/layouts/partials/community_links.html#L17

...replacing `<a href="/docs/contribution-guidelines/">` with `<a href="whatever/url/you/like">`.

For future use I can look into parameterizing it as possibly other users might have a non-default page location.

If you also/instead want to change the text that says Contribution Guidelines, you can use the approach I described in my previous post and override the `community_guideline` string.

**Comment by dfranco** [comment]
Hi @LisaFC,

I had another try using your last comment and I confirm it works fine

See https://www.bacula-web.org/community/

Thanks a million for your help !

**Comment by LisaFC** [comment]
Great news, glad we could help!

**Comment by chalin** [comment]
> Aha, so you want the Contribution Guide link to point somewhere other than `/docs/contribution-guidelines` (the default)?

See:

- #2065
