### ISSUE TITLE
Override specific *.js theme file?

### ISSUE THREAD

**Issue by jasonday** [google/docsy#1335]
Is there a method to override javascript files in `themes/docsy/assets/js`?

Specifically, I rewrote `offline-search.js` to be accessible, but I'd like my changes to not be at risk of overwrites as part of any upgrade process. 

I will be submitting my changes as a pull request, but it is a different approach than the current method of stuffing bootstrap's popover full of interactive content (which it wasn't designed for), so y'all may decide not to incorporate.

**Comment by fekete-robert** [comment]
I think if you put it into the assets/js folder in your project it will
override the one in the theme, but I haven't tested that recently

**Comment by LisaFC** [comment]
Yes, if you override any Docsy file with the same path in your project it should override it - so create an <your project root>/assets/js/offline-search.js file. Let me know if it doesn't work.
