### ISSUE TITLE
Drop / inline prepend() SCSS function

### ISSUE THREAD

**Issue by chalin** [google/docsy#1385]
Consider dropping `prepend()`, in favor of using `join()` directly: https://github.com/google/docsy/blob/c8530e3c891109a416c4ee1746608c33ae636d5e/assets/scss/support/_functions.scss#L3-L5

In doing so we can eliminate https://github.com/google/docsy/blob/main/assets/scss/support/_functions.scss.

AFAICT, there is only one instance of the call to `prepend()` in Docsy SCSS.

The other function that was in this file (`color-diff()`) was removed by:

- #1384

**Comment by mahi072** [comment]
Hi @chalin,
I would like to work on this issue
