### ISSUE TITLE
Homepage: drop or replace Download CTA button

### ISSUE THREAD

**Issue by chalin** [google/docsy#1389]
The homepage has a **Download** call-to-action (CTA) button. That doesn't make sense given that "downloading" Docsy is the least recommended of the installation options.

I'd like to suggest that we replace **Download** with [**Get started**](https://www.docsy.dev/docs/get-started/). Thoughts @LisaFC et al.?

**Comment by deining** [comment]
> I'd like to suggest that we replace **Download** with [**Get started**](https://www.docsy.dev/docs/get-started/).

Agreed. I would like to keep the button (with changed link + button text).

Two comments:
- Once we change the link, we should consider changing button text `Download`, too. The string is not localized (yet), so this is an easy change.
- If we change the link as proposed, the Github icon does not really make sense any more and should be replaced with some more meaningful icon.

**Comment by emckean** [comment]
+1 for "Get Started"

**Comment by LisaFC** [comment]
+1 for Get Started from me as well.
