### ISSUE TITLE
Offline search no longer works under Bootstrap v5

### ISSUE THREAD

**Issue by chalin** [google/docsy#1425]
I tried to figure out what might be broken. I think it is because the usage has changed, compare:

- https://getbootstrap.com/docs/5.3/components/popovers/#usage
- https://getbootstrap.com/docs/4.6/components/popovers/#usage

At a minimum, the JS file will need to be udpated:

- https://github.com/google/docsy/blob/main/assets/js/offline-search.js

**Comment by chalin** [comment]
@tekezo or @deining - might either of you be willing to work on this?

**Comment by chalin** [comment]
@tekezo et al.: I've made an update for the arrow class name:

- #1427

But I think that it might be necessary to change the template further. For example, maybe `popover-body` needs to be renamed to `popover-inner`? As I mentioned in the PR, for details, see:

- The `template` entry of https://getbootstrap.com/docs/5.3/components/popovers/#options.

**Comment by tekezo** [comment]
Offline search starts working partially with my local commits.
I'll make PR later.
<img width="1591" alt="Screenshot 2023-02-16 at 23 56 10" src="https://user-images.githubusercontent.com/659178/219399700-5b1d6e03-722c-4519-9abf-73e01091ed83.png">
