### ISSUE TITLE
Provide npm package for version 0.6.0

### ISSUE THREAD

**Issue by deining** [google/docsy#1430]
From discussion #1421:

Installing docsy from npm package is mentioned as one [option](https://www.docsy.dev/docs/get-started/other-options/#option-3-docsy-as-an-npm-package) in the user guide. Currently, we do have one single npm version only which points to HEAD of repo:

```
$ npm view google/docsy

docsy@0.6.0 | Proprietary | deps: 2 | versions: 1

dist
.tarball: file:git+ssh://git@github.com/google/docsy.git#2f297969ad25384ed6d7825964e98fdd245497d1
.shasum: undefined

dependencies:
@fortawesome/fontawesome-free: 6.3.0 bootstrap: 5.2.3                     

dist-tags:
latest: 0.6.0  
```

Currently branch `main` is unstable due to migration to bootstrap 5. This means that users installing docsy via npm now end up with an unstable version and may not even be aware of this.

We would provide additional npm packages, at least  a package of the latest official release version. In the future, new npm packages should be created for each officially released version.

**Comment by chalin** [comment]
Closed by:

- #1428
- #1439 - introducing the `npm install --save-dev google/docsy#semver:<vers>` syntax

If you think that more needs to be done @deining, let's open another issue. Thx
