### ISSUE TITLE
Mermaid diagrams fail to render

### ISSUE THREAD

**Issue by chalin** [google/docsy#1450]
Since the following change has been applied, some previously working Mermaid diagrams report "syntax error":

- #990

But nothing has changed in the diagrams and the live Mermaid editor are fine with the Mermaid code.

I believe that the problem stems from the decision to render the code block as a `<div>` rather than `<pre>`: https://github.com/google/docsy/blob/26d4d117a863fb55be71b624256cfd37f501c27f/layouts/_default/_markup/render-codeblock-mermaid.html#L3-L5

Ok, after some digging, I've found that `<pre>` is _required, see [Requirements for the Mermaid API](https://mermaid.js.org/intro/n00b-gettingStarted.html#requirements-for-the-mermaid-api):

> <img width="600" alt="image" src="https://user-images.githubusercontent.com/4140793/221899028-4976d927-c842-40ed-92b0-c288b2e98b91.png">

References:

- https://github.com/google/docsy/pull/990/files#r997232082
- Screenshot when rendering fails for page https://opentelemetry.io/docs/demo/architecture/:
  > <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/221901161-d67ce6e0-45e9-4870-a5b1-b95fe0e8939d.png">

/cc @stephanlachnit @deining

**Comment by deining** [comment]
Have a look at yesterday's commit to the hugDoc's repo:

https://github.com/gohugoio/hugoDocs/commit/eddd25ff4633d0b76e9f155e70de065d754aac4f

This commit does exactly does what you request: replacing `<div>` with `<pre>`. We should following and do the same in our repo.

From the commit message:

```
MermaidJS now specifies to write chart's markdown within a `pre` HTML tag to improve semantics.
```

**Side note**: hugoDocs are using ESM import for mermaid now:

https://github.com/gohugoio/hugoDocs/commit/b2a23b6f5d8651d163e8cf3e111ae41541424cfd

**Comment by chalin** [comment]
Oh great! Thanks for that reference.
