### ISSUE TITLE
Update mermaid

### ISSUE THREAD

**Issue by lschierer** [google/docsy#1484]
Docsy currently pulls in mermaid 9.3.0,  the latest mermaid is 10.0.2, and includes additional graph types including a timeline type.  Please update to the latest mermaid.js.

Thanks!!

**Comment by deining** [comment]
> Docsy currently pulls in mermaid 9.3.0, the latest mermaid is 10.0.2, and includes additional graph types including a timeline type. Please update to the latest mermaid.js.

There exists #1410, which addresses the issue raised. Feel free to upvote this issue with your emoji! With this PR is in place, you can specify a custom version for mermaid in your site config file. This means in future, you don't have to wait until the mermaid version is bumped by the docsy maintainers. :smile:

**Comment by lschierer** [comment]
Yes #1410 would fix this, thanks.
