### ISSUE TITLE
home page is showing horizontal scroller at bottom of site

### ISSUE THREAD

**Issue by MadhuSaini22** [google/docsy#1489]
When I visited home page of docsy, I've seen there's a need of UI fix. There's un-necessary horizontal scroller at bottom of page.
![image](https://user-images.githubusercontent.com/81684710/227754277-651ac5bf-2637-409e-a305-f72b44f36da6.png)

**Comment by kumarankit999** [comment]
I Can work on it.

**Comment by MadhuSaini22** [comment]
> I am Unable to find the file, in which I have to make changes. Can you help me in this

Hey Ankit, happy to see you here too :)
Always start working on the issue, once they're been assigned to you, so wait for that :)

**Comment by LisaFC** [comment]
@chalin is this a (temporary) artefact of the Bootstrap upgrade as the main Docsy site is getting the theme at head? It's not showing up on the example site which is using an actual release.

**Comment by chalin** [comment]
Oh, that's a subtle bug. I'll investigate as soon as I can.

**Comment by chalin** [comment]
- Thanks for reporting it @MadhuSaini22.
- Sorry @kumarankit999, we maintainers don't have the resources to help newcomers debug and resolve issues.
- @emckean - I thought that we can a note to that effect somewhere. If not, could we consider adding such a note to the CONTRIBUTING page?

**Comment by chalin** [comment]
Possible fix:

- #1502
