### ISSUE TITLE
Offline search does not use relative url

### ISSUE THREAD

**Issue by roidelapluie** [google/docsy#151]
request.open("GET", "/index.json", true);

That will only work when docsy is used at the root of a url.

**Comment by LisaFC** [comment]
OK, will take a look. @theletterf, @tekezo, any suggestions?

**Comment by roidelapluie** [comment]
```html
<script>
    var offlineSearchURL = "{{ "index.json"| relURL }}";
</script>
<script src="{{"js/offline-search.js"| relURL}}"></script>
```

then:

```js
request.open("GET", offlineSearchURL, true); // Request the JSON file created during build
```

However that does not work :)

**Comment by tekezo** [comment]
I fixed this issue on tekezo:feature/sidebar-search branch ( https://github.com/google/docsy/pull/150 ) at 
 https://github.com/google/docsy/pull/150/commits/77fd117d1d78437b8adaa4494df01439df4265d1

**Comment by LisaFC** [comment]
Ah fantastic! I saw the other improvements when I tested it but didn't notice that one.
