### ISSUE TITLE
If there a way to add a contact form to a Docsy site?

### ISSUE THREAD

**Issue by SamGreenwood1** [google/docsy#1514]

**Comment by fekete-robert** [comment]
Sure, for example, you can embed any external form provider using javascript.

**Comment by LisaFC** [comment]
We also have a very simple integration with one provider (Fabform) if you like: https://www.docsy.dev/docs/adding-content/feedback/#add-a-contact-form-with-fabform

**Comment by LisaFC** [comment]
Let me know if this solution worked for you and if I can close the issue.

**Comment by LisaFC** [comment]
Closing. Feel free to reopen if you need more information!
