### ISSUE TITLE
Docsy doesn't support rendering Swagger UI using OpenAPI 3.1.X

### ISSUE THREAD

**Issue by Luyao-Zhang-1** [google/docsy#1520]
We would like to render Swagger UI  using OpenAPI version 3.1.0 (which has been available since [February 2021](https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released)), but it is not supported.

**Comment by theletterf** [comment]
Yes! I plan to work on this in https://github.com/google/docsy/issues/1076

**Comment by Luyao-Zhang-1** [comment]
@theletterf  Thank you for picking this up! Looking forward!
