### ISSUE TITLE
Swagger support questions

### ISSUE THREAD

**Issue by alexearnshaw** [google/docsy#153]
I noticed that there is support for publishing OpenAPI/Swagger API documentation using a shortcode (https://www.docsy.dev/docs/adding-content/shortcodes/#swaggerui) but I'm a bit unclear as to how to get this to work?

Is there a default layout for swagger as that topic implies? As there is no mention of it here: https://www.docsy.dev/docs/adding-content/content/#content-sections-and-templates

Also if I were to create a folder under `content/en/` called `swagger`, where would this appear on the top-level navigation? Or would it?

Or should I just create a new topic in the `content/en/docs` folder and override the layout in the front matter to `swagger`?

Sorry if I'm missing something but it seems like the doc for swagger support is incomplete. Is there an example of a site using this support that I could reference? I'd happily improve the doc for this if I can figure out how to get it working?

**Comment by LisaFC** [comment]
There is indeed a swagger layout, it's the same as a docs layout (has left nav etc.) but also pulls in the Swagger CSS and JS: https://github.com/google/docsy/tree/master/layouts/swagger

So you need a swagger page to properly display the shortcode, which as you suggest you can create by overriding the layout in a docs page to "swagger".  I haven't got the local copy I tested it on on this machine but can check tomorrow. Will update the doc for more clarity.

@theletterf added this feature so may have an example!

**Comment by LisaFC** [comment]
So this works (I just checked and got lovely Swagger output!)

> ---
> title: "Swagger Test"
> linkTitle: "Swagger"
> type: swagger
> ---
> 
> Here is some Swagger output
> 
> {{< swaggerui src="/openapi/petstore.yaml" >}}

**Comment by theletterf** [comment]
Yep, that's it! The path is relative to the site root, I imagine?

**Comment by LisaFC** [comment]
Yep - I put the petstore.yaml in [site-root]/static/openapi/petstore.yaml and it's served when I run locally at localhost:1313/openapi/petstore.yaml. :)

**Comment by alexearnshaw** [comment]
@LisaFC @theletterf Thanks so much for confirming, I'll give it a try.

**Comment by omfgnuts** [comment]
> Yep - I put the petstore.yaml in [site-root]/static/openapi/petstore.yaml and it's served when I run locally at localhost:1313/openapi/petstore.yaml. :)

Hey @LisaFC, i just tried this and when i enter localhost:1313/openapi/petstore.yaml, it just downloads yaml file, how do i actually render it?

**Comment by LisaFC** [comment]
Heh, no problem. There are many many directories....
