### ISSUE TITLE
offline Search not working as suggested

### ISSUE THREAD

**Issue by misfir3** [google/docsy#154]
The docs here (https://www.docsy.dev/docs/adding-content/navigation/#configure-local-search-with-lunr) provide straightforward steps (turn on offlineSearch, create a `search-index.md` and turn off algolia/remove `gcse` references) for using offline search with lunr.  Those directions, however, do not seem to work in a local dev set up.   I have made other changes to themes (mainly css) prior to this, but none I believe that should have affected this.

Can anyone confirm or suggest what else might be affecting this?
TIA!

**Comment by misfir3** [comment]
more detail ... in my config.toml, I have:
```
# Enable local search
offlineSearch = true
...
# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "..."
# ^^ commented out
# Enable Algolia DocSearch
algolia_docsearch = false
...
```
... and a `content/en/search-index.md` file with:
```
---
type: "search-index"
url: "index.json"
---

**Comment by LisaFC** [comment]
Quick question before I dig in further - do you actually have a generated index? (it should be at `localhost:[whatever]/index.json`)  For some reason when you're running the local Hugo server you need to run `hugo` first (not `hugo server`) to build the index, I got caught by that the first time I tried testing the feature.

**Comment by misfir3** [comment]
Thanks 🙇  @LisaFC - I had run `hugo -D` earlier, but ran just straight hugo this time ... it appears to generate a number of files, but not `index.json` in the`/static/*` path.

In the meantime, I have started looking at a more custom lunr solution also in the meantime, but would prefer a "native" solution if possible. I offer that in interest of full disclosure, but don't believe that would interfere since I'm just generating my own index and wiring up a fetch for it in the page load etc. ...

**Comment by LisaFC** [comment]
Huh, that's very strange - it works fine for me. @tekezo has just added some improvements to the local search functionality in #152 , so maybe try it again with the latest Docsy version? Otherwise can you share your repo with us and we'll see if we can help.

**Comment by misfir3** [comment]
Thanks for checking it out @LisaFC. Will take out a fresh copy of docsy and see if I can replicate either way.

**Comment by misfir3** [comment]
closing this as offlineSearch works in a fresh clone from docsy-example. Will backtrack/integrate my content with that example.  Thanks for looking into it all the same!
