### ISSUE TITLE
Prepare and release Docsy 0.7.0

### ISSUE THREAD

**Issue by chalin** [google/docsy#1540]
- Closes #470

# Release checklist
- [x] Prepare hugo modules
  - [x] Update `package.json`
  - [x] Update Changelog
  - [x] Update the Docsy version in [userguide/hugo.yaml](https://github.com/google/docsy/blob/main/userguide/hugo.yaml)
- [x] Create and test new tags
- [x] Create and publish the new release 🎉

Docsy example followup:

- [ ] https://github.com/google/docsy-example/issues/207

**Comment by chalin** [comment]
@geriom - if you haven't submitted a PR already, maybe @deining is available to update the [docsy-example](https://github.com/google/docsy-example)?

**Comment by deining** [comment]
Two persons, same thought: just had the impression that updating the example site is the next logical step.

> @geriom - if you haven't submitted a PR already,

Indeed there exists this pull request: [Update docsy theme to docsy v0.6.0](https://github.com/google/docsy-example/pull/192) dating back to December 2022. Unfortuantely this was never merged 😢 .

> maybe @deining is available to update the [docsy-example](https://github.com/google/docsy-example)?

Yes, I will take the existing PR as starting point and will come up with a PR during the weekend.

**Comment by chalin** [comment]
Closing, since the release is out. Will track the example update via:

- https://github.com/google/docsy-example/issues/207
