### ISSUE TITLE
Does docsy support version control?

### ISSUE THREAD

**Issue by jievince** [google/docsy#156]
My tech docs need version control feature, it should give users a choice to select which version of docs to read. It's UI should like this:
![image](https://user-images.githubusercontent.com/38901892/70018821-48f3d700-15c2-11ea-9df8-cb5ec032a817.png)

**Comment by LisaFC** [comment]
Yes, there's an option to add a version drop-down to the top nav: https://www.docsy.dev/docs/adding-content/navigation/#adding-a-version-drop-down

The Kubeflow docs use Docsy and serve multiple archived versions of their site, so you can see it in action there: https://www.kubeflow.org/

**Comment by jievince** [comment]
Thanks very much, this solved my problem.

**Comment by LisaFC** [comment]
Great, glad we could help!
