### ISSUE TITLE
Page-meta spacing is off for some pages

### ISSUE THREAD

**Issue by chalin** [google/docsy#1573]
The screenshots below are from https://deploy-preview-1567--docsydocs.netlify.app/blog/.

Notice the spacing between the top nav and the page-meta links like **View page source**:

> <img width="1229" alt="image" src="https://github.com/google/docsy/assets/4140793/0cd3162b-0f0d-4d0c-a55c-84e028ffdaba">

The spacing is off for selected pages like this:

> <img width="1228" alt="Screen Shot 2023-06-15 at 19 03 19" src="https://github.com/google/docsy/assets/4140793/bb9cec6c-d8a0-425c-b95f-9490a01024e0">

**Comment by thequailman** [comment]
I solved this by adding:

```
main {
  min-height: 100vh;
}
```

Seems like a hack though, but the style of the layout is pretty bad to begin with.  Should replace all of it with a grid.

**Comment by chalin** [comment]
I believe that

- #1661

Fixed the problem, by ensuring that the height of the left-nav is properly computed.

As a demonstration of the problem, see preview of the last PR just before before the #1661: https://deploy-preview-1668--docsydocs.netlify.app/blog/.

If you make the page tall enough, you'll see the mis-formatting of the toc, like this:

> <img width="1325" alt="image" src="https://github.com/google/docsy/assets/4140793/de2c084e-ae41-456c-9d84-90bc3a1591b5">

Now make the window shorter and eventually the toc formatting issue disappears on its own:

> <img width="1323" alt="image" src="https://github.com/google/docsy/assets/4140793/8b4909b7-8fba-48e2-a244-67c8194352fb">

Since #1661, I can no longer reproduce the problem in that way! \o/

**Comment by chalin** [comment]
Until proven otherwise, I'm going to assume that this was closed by:

- #1661

**Comment by chalin** [comment]
Nope, the problem is still present, e.g. see: https://www.docsy.dev/docs/best-practices/

<img width=800 alt="Image" src="https://github.com/user-attachments/assets/0ba47397-7fdb-4414-9b34-a826d3c939fc" />
