### ISSUE TITLE
Automatically crawl markdown format documents on my github project and deploy them to my online documentation website built using hugo

### ISSUE THREAD

**Issue by jievince** [google/docsy#159]
I have a GitHub project about database, and I usually write docs in markdown format to the project. Also, I want to deploy an online document website built with Hugo to those who want to read docs on the web site instead of the GitHub project. So does Hugo can crawl the docs on my Github project automatically and update the corresponding content on the web site?

**Comment by jievince** [comment]
Another question: a classic post looks like this:
```
---
title: "Docsy Blog"
linkTitle: "Blog"
menu:
  main:
    weight: 30
---


This is the **blog** section. It has two categories: News and Releases.

Files in these directories will be listed in reverse chronological order.
```
Every post's header has something like `--- title linkTitle`, I tried to delete them, and then Hugo couldn't find those posts.
Because all the posts come from my Github project which doesn't have those headers, So how can I solve this?

**Comment by LisaFC** [comment]
So the easiest way I know to continuously deploy a Hugo site from GitHub is to use [Netlify](https://www.netlify.com/) - if you serve your site from Netlify it automatically updates from your GitHub repo when you make changes. Here are some instructions:
https://www.docsy.dev/docs/deployment/#deployment-with-netlify

There are other options but they usually involve having to set up some continuous deployment stuff yourself.

**Comment by LisaFC** [comment]
For your second question, Hugo will only recognize Markdown files with Hugo headers when building your site (otherwise it doesn't know what they are or where to put them).

If you want to reuse content from other non-Hugo Markdown files, it should be possible though you might need a custom shortcode, I don't think any of Hugo's built-in ones do it but I've found a couple of examples. I'll create a separate issue for adding the shortcode.

**Comment by RichieEscarez** [comment]
A file with the Hugo frontmatter can use the `readfile` shortcode to pull in content from another file, more info here: https://github.com/google/docsy/pull/8

**Comment by LisaFC** [comment]
Closing as `readfile` solves the problem for non-Markdown files.
