### ISSUE TITLE
Add warn message when running docsy v0.7.0 with hugo versions < v0.110

### ISSUE THREAD

**Issue by deining** [google/docsy#1591]
As of docsy version `v0.7.0`, hugo `v0.110.0` is required as minimum version (as mentioned in the [change log](https://github.com/google/docsy/blob/main/CHANGELOG.md)). This requirement might not be obvious to newbies and lead to frustration, as clearly stated in this [issue comment](https://github.com/google/docsy/discussions/1555#discussioncomment-6270479).

Proof of failure:

- Clone the example repo
- run ´hugo server` (with hugo version 0.100`)

This is what you get:

```
Start building sites … 
hugo v0.100.0-27b077544d8efeb85867cb4cfb941747d104f765+extended linux/amd64 BuildDate=2022-05-31T08:37:12Z VendorInfo=gohugoio
Error: Error building site: "/home/andreas/doscy-test/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
Built in 15 ms
```

This message is not helpful at all, so we should add additional an additional warn message (or even an throw an error) in case of older hugo versions.
To make things worse, folks using an older version of Hugo will **not** be able to use Hugo's --config flag to get around this:

```
$ hugo_0.100.0 server --config hugo
hugo: downloading modules …
hugo: collected modules in 16905 ms
WARN 2023/06/24 22:43:49 Module "github.com/google/docsy-example" is not compatible with this Hugo version; run "hugo mod graph" for more information.
WARN 2023/06/24 22:43:49 Module "github.com/google/docsy" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: from config: failed to resolve output format "print" from site config
```

Not sure what is the best way to tackle this issue, but IMHO, we should react on this in order to avoid frustration for docsy newbies.

@chalin: WDYT?

**Comment by chalin** [comment]
I don't think that we can resolve this in Docsy. I've tested various approaches and none of them work: that is, the error mentioned above "failed to extract shortcode: template for shortcode "blocks/cover" not found" gets hit first.

If this is to be resolved, for the benefit of newbies, I think it will need to be in the example repo.

/cc @geriom

**Comment by chalin** [comment]
@deining, if you agree, please close this issue. I've created the following:

- https://github.com/google/docsy-example/issues/228
