### ISSUE TITLE
Copyright year

### ISSUE THREAD

**Issue by ayaco-zg** [google/docsy#1592]
Shouldn't the copyright year (like ©2023) be the year the site was founded (or the year the company was founded) rather than the year the page was last updated?
Reference: https://www.copyrightlaws.com/copyright-symbol-notice-year/

I would like to specify the year in hugo.config.

----
layout\partials\footer.html l.21
```
          <span>&copy; {{ now.Year }} {{ . }} {{ T "footer_all_rights_reserved" }}</span>
```

**Comment by chalin** [comment]
Thanks for the ping regarding this issue. I'm going to close this in favor of #2.
