### ISSUE TITLE
The sidebar list is too long in default way, how can it collapse?

### ISSUE THREAD

**Issue by faystart** [google/docsy#160]
when people viewing /docs/ , the sidebar list is too long (much 2nd and 3rd level sub list).

How can I make it collapse as 2nd level sub list ?  Hate to bother, but can't find a way.

Please help

**Comment by LisaFC** [comment]
If you set sidebar_menu_compact = true in your config.toml (the default is false) you shouldn't get the fully expanded sidebar lists, let me know if that doesn't work.

**Comment by ec1warc1** [comment]
You read my mind!!! Many thanks for this quick solution! Awesome!
