### ISSUE TITLE
Using docsy example as cloned repo, dependencies are not imported.

### ISSUE THREAD

**Issue by mattomis** [google/docsy#1600]
Issue #833 seems to be the issue I am having. This is docsy running in hugo as a container in VS Code with a cloned docsy example repo from my github account. 
The docsy example repo does not contain a dependencies folder. 
The following modules generate an error as does the standard method of merely referencing docsy and docsy/dependencies as import modules.
```
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/mattomis/docsy-example"
    disable = false
[[module.imports]]
  path = "github.com/twbs/bootstrap"
  disable = false
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/bootstrap/scss"
[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
  source = "scss"
  target = "assets/vendor/Font-Awesome/scss"
```

```
$ hugo mod graph
Error: failed to load modules: module "github.com/FortAwesome/Font-Awesome" not found in "/workspaces/omis_docs_07_23/omis_docs_7_23/themes/github.com/FortAwesome/Font-Awesome"; either add it as a Hugo Module or store it in "/workspaces/omis_docs_07_23/omis_docs_7_23/themes".: module does not exist
```

**Setup:**

uname -a: 
Linux 0393979fe66f 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux

hugo version
hugo v0.115.1-857374e69358f788bd31ddc55255c5c8e3dcfd80+extended linux/amd64 BuildDate=2023-07-03T17:28:25Z VendorInfo=gohugoio

$ tree
.
├── archetypes
│   └── default.md
├── assets
├── content
├── data
├── hugo.toml
├── layouts
├── resources
│   └── _gen
│       ├── assets
│       └── images
├── static
└── themes
    └── docsy
        ├── assets
        │   ├── icons
        │   │   ├── logo.png
        │   │   └── logo.svg
        │   ├── js
        │   │   ├── anchor.js
        │   │   ├── base.js
        │   │   ├── click-to-copy.js
        │   │   ├── drawio.js
        │   │   ├── markmap.js
        │   │   ├── mermaid.js
        │   │   ├── offline-search.js
        │   │   ├── plantuml.js
        │   │   └── search.js
        │   ├── json
        │   │   └── offline-search-index.json
        │   ├── scss
        │   │   ├── _alerts.scss
        │   │   ├── blocks
        │   │   │   ├── _blocks.scss
        │   │   │   └── _cover.scss
        │   │   ├── _blog.scss
        │   │   ├── _boxes.scss
        │   │   ├── _breadcrumb.scss
        │   │   ├── _buttons.scss
        │   │   ├── _code.scss
        │   │   ├── _colors.scss
        │   │   ├── _content.scss
        │   │   ├── _drawio.scss
        │   │   ├── _main-container.scss
        │   │   ├── main.scss
        │   │   ├── _nav.scss
        │   │   ├── _pageinfo.scss
        │   │   ├── rtl
        │   │   │   ├── _main.scss
        │   │   │   └── _spacing.scss
        │   │   ├── _search.scss
        │   │   ├── section-index.scss
        │   │   ├── shortcodes
        │   │   │   ├── cards-pane.scss
        │   │   │   └── tabbed-pane.scss
        │   │   ├── shortcodes.scss
        │   │   ├── _sidebar-toc.scss
        │   │   ├── _sidebar-tree.scss
        │   │   ├── _styles_project.scss
        │   │   ├── support
        │   │   │   ├── _bootstrap_vers_test.scss
        │   │   │   ├── _functions.scss
        │   │   │   ├── _mixins.scss
        │   │   │   └── _utilities.scss
        │   │   ├── _table.scss
        │   │   ├── _taxonomy.scss
        │   │   ├── _variables_forward.scss
        │   │   ├── _variables_project.scss
        │   │   └── _variables.scss
        │   └── stubs
        │       └── new-page-template.md
        ├── CHANGELOG.md
        ├── CONTRIBUTING.md
        ├── dependencies
        │   ├── assets
        │   │   └── bootstrap
        │   │       ├── README.txt
        │   │       └── scss
        │   │           └── _vendor
        │   │               ├── README.txt
        │   │               └── _rfs.scss
        │   ├── config.toml
        │   ├── go.mod
        │   └── go.sum
        ├── docker-compose.yaml
        ├── Dockerfile
        ├── go.mod
        ├── go.sum
        ├── hugo.yaml
        ├── i18n
        │   ├── ar.toml
        │   ├── bg.toml
        │   ├── bn.toml
        │   ├── de.toml
        │   ├── en.toml
        │   ├── es.toml
        │   ├── et.toml
        │   ├── fa.toml
        │   ├── fi.toml
        │   ├── fr.toml
        │   ├── hu.toml
        │   ├── it.toml
        │   ├── ja.toml
        │   ├── ko.toml
        │   ├── nl.toml
        │   ├── no.toml
        │   ├── pl.toml
        │   ├── pt-br.toml
        │   ├── ru.toml
        │   ├── sv.toml
        │   ├── tr.toml
        │   ├── uk.toml
        │   ├── zh-cn.toml
        │   └── zh-tw.toml
        ├── images
        │   ├── screenshot.png
        │   └── tn.png
        ├── layouts
        │   ├── 404.html
        │   ├── blog
        │   │   ├── baseof.html
        │   │   ├── baseof.print.html
        │   │   ├── content.html
        │   │   ├── list.html
        │   │   ├── section.print.html
        │   │   └── single.html
        │   ├── community
        │   │   └── list.html
        │   ├── _default
        │   │   ├── baseof.html
        │   │   ├── content.html
        │   │   ├── list.html
        │   │   ├── list.rss.xml
        │   │   ├── _markup
        │   │   │   ├── render-codeblock-chem.html
        │   │   │   ├── render-codeblock-math.html
        │   │   │   └── render-codeblock-mermaid.html
        │   │   ├── search.html
        │   │   ├── single.html
        │   │   ├── taxonomy.html
        │   │   └── terms.html
        │   ├── docs
        │   │   ├── baseof.html
        │   │   ├── baseof.print.html
        │   │   ├── list.html
        │   │   ├── list.print.html
        │   │   └── single.html
        │   ├── home.html
        │   ├── _internal
        │   │   └── google_analytics_gtag.html
        │   ├── partials
        │   │   ├── breadcrumb.html
        │   │   ├── community_links.html
        │   │   ├── disqus-comment.html
        │   │   ├── favicons.html
        │   │   ├── featured-image.html
        │   │   ├── feedback.html
        │   │   ├── footer.html
        │   │   ├── head-css.html
        │   │   ├── head.html
        │   │   ├── hooks
        │   │   │   ├── body-end.html
        │   │   │   └── head-end.html
        │   │   ├── navbar.html
        │   │   ├── navbar-lang-selector.html
        │   │   ├── navbar-version-selector.html
        │   │   ├── outputformat.html
        │   │   ├── page-description.html
        │   │   ├── page-meta-lastmod.html
        │   │   ├── page-meta-links.html
        │   │   ├── pager.html
        │   │   ├── print
        │   │   │   ├── content-blog.html
        │   │   │   ├── content.html
        │   │   │   ├── page-heading.html
        │   │   │   ├── render.html
        │   │   │   ├── toc-li-blog.html
        │   │   │   └── toc-li.html
        │   │   ├── reading-time.html
        │   │   ├── scripts.html
        │   │   ├── search-input.html
        │   │   ├── section-index.html
        │   │   ├── sidebar.html
        │   │   ├── sidebar-tree.html
        │   │   ├── taxonomy_terms_article.html
        │   │   ├── taxonomy_terms_article_wrapper.html
        │   │   ├── taxonomy_terms_cloud.html
        │   │   ├── taxonomy_terms_clouds.html
        │   │   ├── toc.html
        │   │   └── version-banner.html
        │   ├── shortcodes
        │   │   ├── alert.html
        │   │   ├── blocks
        │   │   │   ├── cover.html
        │   │   │   ├── feature.html
        │   │   │   ├── lead.html
        │   │   │   ├── link-down.html
        │   │   │   └── section.html
        │   │   ├── card-code.html
        │   │   ├── card.html
        │   │   ├── cardpane.html
        │   │   ├── conditional-text.html
        │   │   ├── figure.html
        │   │   ├── iframe.html
        │   │   ├── imgproc.html
        │   │   ├── pageinfo.html
        │   │   ├── readfile.html
        │   │   ├── redoc.html
        │   │   ├── swaggerui.html
        │   │   ├── tab.html
        │   │   └── tabpane.html
        │   └── swagger
        │       ├── baseof.html
        │       ├── list.html
        │       └── single.html
        ├── LICENSE
        ├── netlify.toml
        ├── package.json
        ├── postcss.config.js
        ├── README.md
        ├── static
        │   ├── css
        │   │   ├── prism.css
        │   │   └── swagger-ui.css
        │   ├── favicons
        │   │   ├── android-144x144.png
        │   │   ├── android-192x192.png
        │   │   ├── android-36x36.png
        │   │   ├── android-48x48.png
        │   │   ├── android-72x72.png
        │   │   ├── android-96x96.png
        │   │   ├── apple-touch-icon-180x180.png
        │   │   ├── favicon-1024.png
        │   │   ├── favicon-16x16.png
        │   │   ├── favicon-256.png
        │   │   ├── favicon-32x32.png
        │   │   ├── favicon.ico
        │   │   ├── pwa-192x192.png
        │   │   ├── pwa-512x512.png
        │   │   ├── tile150x150.png
        │   │   ├── tile310x150.png
        │   │   ├── tile310x310.png
        │   │   └── tile70x70.png
        │   └── js
        │       ├── deflate.js
        │       ├── prism.js
        │       ├── swagger-ui-bundle.js
        │       ├── swagger-ui-standalone-preset.js
        │       └── tabpane-persist.js
        ├── theme.toml
        └── userguide
            ├── assets
            │   └── scss
            │       └── _variables_project.scss
            ├── content
            │   └── en
            │       ├── about
            │       │   ├── featured-background.jpg
            │       │   └── index.md
            │       ├── blog
            │       │   ├── 2022
            │       │   │   └── hello.md
            │       │   ├── 2023
            │       │   │   └── bootstrap-5-migration.md
            │       │   └── _index.md
            │       ├── community
            │       │   └── _index.md
            │       ├── docs
            │       │   ├── adding-content
            │       │   │   ├── content.md
            │       │   │   ├── diagrams-and-formulae
            │       │   │   │   ├── docsy-diagrams.svg
            │       │   │   │   └── index.md
            │       │   │   ├── feedback.md
            │       │   │   ├── iconsimages.md
            │       │   │   ├── _index.md
            │       │   │   ├── lookandfeel.md
            │       │   │   ├── navigation.md
            │       │   │   ├── print.md
            │       │   │   ├── repository-links.md
            │       │   │   ├── shortcodes
            │       │   │   │   ├── flags
            │       │   │   │   │   ├── de.png
            │       │   │   │   │   ├── tz.png
            │       │   │   │   │   └── uk.png
            │       │   │   │   ├── includes
            │       │   │   │   │   ├── config.yaml
            │       │   │   │   │   └── installation.md
            │       │   │   │   ├── index.md
            │       │   │   │   └── spruce.jpg
            │       │   │   ├── taxonomy.md
            │       │   │   └── versioning.md
            │       │   ├── best-practices
            │       │   │   ├── _index.md
            │       │   │   ├── organizing-content.md
            │       │   │   └── site-guidance.md
            │       │   ├── contribution-guidelines
            │       │   │   └── _index.md
            │       │   ├── deployment
            │       │   │   └── _index.md
            │       │   ├── examples
            │       │   │   └── _index.md
            │       │   ├── get-started
            │       │   │   ├── basic-configuration.md
            │       │   │   ├── docsy-as-module
            │       │   │   │   ├── example-site-as-template.md
            │       │   │   │   ├── _index.md
            │       │   │   │   ├── installation-prerequisites.md
            │       │   │   │   └── start-from-scratch.md
            │       │   │   ├── _index.md
            │       │   │   ├── known_issues.md
            │       │   │   ├── other-options.md
            │       │   │   └── quickstart-docker.md
            │       │   ├── _index.md
            │       │   ├── language
            │       │   │   └── _index.md
            │       │   └── updating
            │       │       ├── convert-site-to-module.md
            │       │       ├── _index.md
            │       │       ├── updating-hugo-module.md
            │       │       └── updating-submodules.md
            │       ├── featured-background.jpg
            │       ├── _index.md
            │       └── search.md
            ├── CONTRIBUTING.md
            ├── hugo.yaml
            ├── layouts
            │   └── sitemap.xml
            ├── LICENSE
            ├── Makefile
            ├── package.json
            └── static
                ├── google6a6ae8b5b016a20d.html
                └── images
                    ├── feedback.png
                    ├── no.png
                    ├── version-banner.png
                    └── yes.png

**Comment by deining** [comment]
> The docsy example repo does not contain a dependencies folder.

That's perfectly fine. The example site pulls in docsy and docsy in turn pulls in dependencies, so there is absolutely no need for the example site to have a `dependencies` folder.

```
> [module]
>   # uncomment line below for temporary local development of module
>   # replacements = "github.com/google/docsy -> ../../docsy"
>   [module.hugoVersion]
>     extended = true
>     min = "0.110.0"
>   [[module.imports]]
>     path = "github.com/mattomis/docsy-example"
>     disable = false
> [[module.imports]]
>   path = "github.com/twbs/bootstrap"
>   disable = false
> [[module.imports.mounts]]
>   source = "scss"
>   target = "assets/vendor/bootstrap/scss"
> [[module.imports]]
>   path = "github.com/FortAwesome/Font-Awesome"
> [[module.imports.mounts]]
>   source = "scss"
>   target = "assets/vendor/Font-Awesome/scss"
 ```

This given config is ways too complicated!
And looking at your file tree: you are **not** supposed to have a folder `docsy` in you site. Also no folder `themes` is needed!

Please follow the [instructions](https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/) given in the user guide:
These three commands should be enough to get you up and running:

```
git clone --depth 1 --branch v0.7.1 https://github.com/google/docsy-example.git my-new-site
cd my-new-site
hugo server
```

**Comment by mattomis** [comment]
Just following [the instructions](https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/) generates the error:
`Error: command error: failed to load modules: failed to download modules: binary with name "go" not found`

If I were to take a stab as to why I might guess the docker package.json file has some issue with not downloading golang successfully or not successfully installing it. The devcontainer package.json file is:

```
{
  "scripts": {
    "get:submodule": "git submodule update --init --depth 1",
    "_prepare:docsy": "cd themes/docsy && npm install",
    "prepare": "npm run get:submodule && npm run _prepare:docsy"
  },
  "dependencies": {
    "nvm": "20.3.1"
  }
}
```

Checking the devcontainer log now...

**Comment by mattomis** [comment]
**UPDATE:**
Adding the following to the devcontainer.json file resolve this issue and installed roughly 2 craploads of software:

`	"postCreateCommand": "sudo apt update && sudo apt-get install -y nodejs npm golang && npm install autoprefixer postcss postcss-cli && npm list"`

**Comment by chalin** [comment]
This seems to be resolved, so closing it.
