### ISSUE TITLE
add expand/collapse icon.

### ISSUE THREAD

**Issue by glepnir** [google/docsy#1603]
any plan to add expand/collpase icon on left section ? I can make a pr for this.

**Comment by LisaFC** [comment]
We already have one! See [Section menu options](https://www.docsy.dev/docs/adding-content/navigation/#section-menu-options) - if you set ui.sidebar_menu_foldable = true in your hugo config, you get toggly arrows to expand and collapse. Let me know if this doesn't work for you or if it isn't what you mean.

I think we should possibly use this in our own docs...

**Comment by glepnir** [comment]
yep . no expand /collapse icon but you can click the title in right is wired behavior.
