### ISSUE TITLE
Tabpane formatting issue in narrow views when part of a list etc

### ISSUE THREAD

**Issue by chalin** [google/docsy#1660]
Visit https://www.docsy.dev/docs/adding-content/search/#adding-the-search-page, and you'll see:

> <img width="619" alt="image" src="https://github.com/google/docsy/assets/4140793/2ceae501-69de-4ab5-b807-e6edaaf903d5">

It's the same problem as the previously reported issue (#1309), but when the tabbed pane is inside an HTML element rather than at the top level.

**Comment by Nadine2016** [comment]
I am seeing the exact same issue! We need the tabpane to work within steps (ordered list) to show different commands depending on the environment that you are in.

**Comment by chalin** [comment]
Here's a fix, PTAL:

- #1671

**Comment by chalin** [comment]
- Closed by #1671
