### ISSUE TITLE
favicons don't show up when placed in project's static/favicons folder

### ISSUE THREAD

**Issue by mattomis** [google/docsy#1675]
Hi folks,
Using the instructions at: https://www.docsy.dev/docs/adding-content/iconsimages/#add-your-favicons I am unable to generate the expected output in Chrome/Firefox/Edge even when cache and images have been emptied and hugo and hugo server run without error the local server used generic favicon instead of my custom one.
This is Docsy v0.7.1 and hugo_extended 0.115.1

**Comment by fekete-robert** [comment]
Make sure that your filenames match the ones in the docsy template: https://github.com/google/docsy/blob/841b9a0f38635488bad6b1617405b705cc39cb44/layouts/partials/favicons.html#L5

**Comment by mattomis** [comment]
aha, but they do! I mean one of the filenames was favicon.ico and I didn't think docsy required the full compliment of favicon formats to display a simple favicon in chrome/firefox/edge

**Comment by mattomis** [comment]
outrageous
