### ISSUE TITLE
Does offlineSearch not working again?

### ISSUE THREAD

**Issue by xiangma0510** [google/docsy#1689]
I use the [docsy-example](https://github.com/google/docsy-example) with docsy 0.7.1 to build my site, but when I enable `offlineSearch = true`, It seems doesn't work , please ensure if bug appear again? 
<img width="1181" alt="image" src="https://github.com/google/docsy/assets/86297429/1b5fca32-9c43-47e9-9408-563c67b4f877">

**Comment by xiangma0510** [comment]
Does it not sending any request?
<img width="1869" alt="image" src="https://github.com/google/docsy/assets/86297429/35d78935-b8db-4c37-a78a-814d04969641">

**Comment by xiangma0510** [comment]
`go.mod`：
```mod
module github.com/google/docsy-example

go 1.12

require (
	github.com/FortAwesome/Font-Awesome v0.0.0-20230327165841-0698449d50f2 // indirect
	github.com/google/docsy v0.7.1 // indirect
	github.com/twbs/bootstrap v5.3.2+incompatible // indirect
)
```

**Comment by tekezo** [comment]
offline search works well on my machine.

diff from main branch:

```diff
diff --git a/hugo.toml b/hugo.toml
index 19ebd53..8ce7be3 100644
--- a/hugo.toml
+++ b/hugo.toml
@@ -141,13 +141,13 @@ github_project_repo = "https://github.com/google/docsy"
 github_branch= "main"
 
 # Google Custom Search Engine ID. Remove or comment out to disable search.
-gcs_engine_id = "d72aa9b2712488cc3"
+# gcs_engine_id = "d72aa9b2712488cc3"
 
 # Enable Algolia DocSearch
 algolia_docsearch = false
 
 # Enable Lunr.js offline search
-offlineSearch = false
+offlineSearch = true
 
 # Enable syntax highlighting and copy buttons on code blocks with Prism
 prism_syntax_highlighting = false
```

<img width="1600" alt="Screenshot 2023-10-13 at 8 13 15" src="https://github.com/google/docsy/assets/659178/ebac4b0b-2d6d-49e8-bb2e-2e9115c4bd02">

**Comment by xiangma0510** [comment]
What versions of these modules are you using? I found a new environment, and it really didn't work.
<img width="1343" alt="image" src="https://github.com/google/docsy/assets/86297429/a4ec5448-897f-45f1-90e1-00ee09ecd590">

**Comment by xiangma0510** [comment]
I only turn on `offlineSearch = true`, and other params keep default

**Comment by xiangma0510** [comment]
I changed two machines, it's the same phenomenon.

**Comment by tekezo** [comment]
Did you disable `gcs_engine_id` in hugo.toml?

**Comment by xiangma0510** [comment]
No, If I comment it out, it seems to run correctly.

I review your [document](https://www.docsy.dev/docs/adding-content/search/#local-search-with-lunr), but I didn’t read it carefully enough. The description in the document says to comment out this parameter, rather than using a code block.

It's my fault, thank you so much
