### ISSUE TITLE
Create a new GH project

### ISSUE THREAD

**Issue by chalin** [google/docsy#1721]
I don't seem to have the necessary permissions to create a project under https://github.com/google/docsy/projects, can you @emckean or @LisaFC? Hopefully once it's created I'll have the permissions necessary to update it :).

**Comment by emckean** [comment]
I added a project, can you see if you can edit it?
It looks like GitHub now has "new Projects" which is at the org (so, top-level, aka github/google) level, so I created a "classic" project

**Comment by chalin** [comment]
Yes I can see it. Can you create a new (better than classic) project please? I'd prefer that. TY

**Comment by emckean** [comment]
I may not have permissions to do that at the org level, let me figure that out :)

**Comment by emckean** [comment]
Okay, one is made and you can write to it! Let me know if that is not enough access :) 
It's not public yet but I can make it public anytime

**Comment by chalin** [comment]
I confirm that I can access it and add issues. TY! ✨
