### ISSUE TITLE
Support: How to disable landing page section?

### ISSUE THREAD

**Issue by guiadco** [google/docsy#173]
It would be great to use the docsy docs section without the landing page.

I  try to force `layout: docs` at top level, but i think `layout/_default` apply before docs layout.

- If i keep the docs section in the folder docs i have a blank page at top-level
- If i push the docs layout at top-level i have a page without docs layout style.
  - no navbar / no right menu

Could you help me?

**Comment by LisaFC** [comment]
Hi! So just to clarify, do you want a site that doesn't have a landing page like docsy.dev but has the docs section at the root so you land straight on it?

You need to force not layout: but type: and then it works (I've just tried it) - have your content index page with frontmatter like:

---
title: "Goldydocs"
linkTitle: "Goldydocs"
type: docs
---

**Comment by LisaFC** [comment]
Just playing around with it a bit more, you'd also probably want to remove any other folders from the example site (if you cloned it) and just have your docs sections as subsections of content. You'd then need to add type:docs to those pages too as they're not in a docs/ folder.

Alternatively you could make the docs layout your default layout - in your own project, add a layouts/ directory that overrides the theme one and add your own _default/ directory with the list.html, baseof.html and single.html from the Docsy docs/ layout directory. Then pages by default will get the left nav and right menu.

**Comment by guiadco** [comment]
Hi, many thanks for your help.

I try to move my subsection from `docs/` to `.`

I add the `type: docs` on any page ans subsection pages, but i look this:

![image](https://user-images.githubusercontent.com/34829865/72454305-e39a2500-37c0-11ea-9085-e902edcd66a8.png)

and when i go to section `getting started`, i see that:

![image](https://user-images.githubusercontent.com/34829865/72454354-f90f4f00-37c0-11ea-89da-b9c114f96aff.png)

but i want to keep the left-menu as he looks like in the `docs/` folder.

Do you know, how i could do?

**Comment by guiadco** [comment]
If i create a `layout/_default`, i have the same effect.

**Comment by guiadco** [comment]
I see i loose this too:

![image](https://user-images.githubusercontent.com/34829865/72455610-658b4d80-37c3-11ea-83cf-cd8390364170.png)

**Comment by LisaFC** [comment]
I'll take a look!

**Comment by LisaFC** [comment]
Just to let you know I haven't forgotten about this, I just need to find a bit of time to see if I can get my test site to do what you want and then let you know how I did it. :) Hopefully have something by the end of the week.

**Comment by shahidhk** [comment]
I am also trying this, very new to Hugo and Docsy, tried copying the `partials` as well, doesn't seem to work. Any help is appreciated.

Thanks for the project, it works really well.

**Comment by LisaFC** [comment]
Nearly there! Creating your own layouts/_default/ and copying the baseof.html, list.html, and single.html from the theme's layouts/docs/ into it is the way to go anyway, as then you don't need to specify any special types for your docs pages even if they're not in a docs folder - they get the "docs" type layout with the side nav by default. I've already got it working for a site that just has a Documentation section.

Just checking if you also want your site to have the About, Blog, and Community pages? If so I'll need to keep tweaking things a bit to make sure the menus work, and you may need to create your own layout type for About and Community too so that they *don't* get the side nav....

**Comment by guiadco** [comment]
Hi thanks for your help :)

I tried this method but i still have some problems

When you look at the menu:
![image](https://user-images.githubusercontent.com/34829865/73063518-38aff800-3e9f-11ea-9775-579c6dc1efa6.png)

It's ok on the first page, but the right-menu still reset on each submenu:
![image](https://user-images.githubusercontent.com/34829865/73072229-fbeefb80-3eb4-11ea-9da8-eff9a975af78.png)

And i still lose this section:
![image](https://user-images.githubusercontent.com/34829865/73072318-250f8c00-3eb5-11ea-9604-60e25af15ebf.png)

Thanks for your help :)

**Comment by LisaFC** [comment]
Ah yes, I see what's happening. Let me see if I can fix it.

**Comment by shahidhk** [comment]
Thanks @LisaFC! Really appreciate it. 

> Just checking if you also want your site to have the About, Blog, and Community pages?

I am only interested in the docs part of it. So no About, Blog and Community :smile:

**Comment by LisaFC** [comment]
I've now fixed the sidebar menu so it stops showing just the subsection when you change pages, just need to figure out why the section index on the main landing page isn't working and we're ready to go. 

Once I have it all working I'll push my layout modifications to a copy in my own repo and you can have a look!

**Comment by LisaFC** [comment]
Nearly there, just have to stop the search results page showing up in the sidebar. I'll have something up later today.

**Comment by LisaFC** [comment]
Annnnnnd finally! https://docsyjustdocs.netlify.com/

Repo is here: https://github.com/LisaFC/justdocs

Main differences are the overrides in layouts/,  a much cut-down content/en/ with just our docs/ sections, and the search results page (search.md) has a nomenu page param so we can hide it from the menu (might be a useful feature for other sites who want to hide pages?)

Hope you find it useful!  I can share it on the mailing list and see if anyone else would like to use it as a reference.

**Comment by aslafy-z** [comment]
Thank you @LisaFC, that's awesome!

**Comment by guiadco** [comment]
This is perfect :+1: Really thanks for your help.

**Comment by shahidhk** [comment]
Thanks a lot @LisaFC!

**Comment by guiadco** [comment]
I test on my documentation, and it work perfectly.

Becareful with the option `sidebar_menu_compact`:
 - keep it at value `false`

**Comment by LisaFC** [comment]
Glad it works for you!  I'll close the issue for now, as I think switching the landing page on and off with a config flag would need significant refactoring (as I said, it changes the entire default layout and site hierarchy).

**Comment by mojave27** [comment]
@LisaFC Thank you so much for your efforts on this.  Was fumbling around trying to make this work, and found this issue.  Works great!
