### ISSUE TITLE
Extra </div> tag showing up on home page

### ISSUE THREAD

**Issue by ec1warc1** [google/docsy#174]
The `</div>` tag shows up on the homepage. I did a fresh install with no changes, and it is there too. Am I not completing a step?
![docsy-homepage-extra-div](https://user-images.githubusercontent.com/23389201/72471513-cd846880-37b0-11ea-8eb6-2126d6e95e03.jpg)

**Comment by ec1warc1** [comment]
Might be important:
`hugo version
Hugo Static Site Generator v0.62.2-83E50184/extended linux/amd64 BuildDate: 2020-01-05T18:57:23Z`

**Comment by ec1warc1** [comment]
When I use an older version:
`hugo version
Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: 2019-08-18T05:29:32Z`
I don't get that bad </div> on the homepage. This must be an issue with hugo program.

**Comment by ec1warc1** [comment]
I created an issue with hugo:
https://github.com/gohugoio/hugo/issues/6759
Thanks!

**Comment by guiadco** [comment]
Hi,

on `index.html` in your root directory, you have:

```
	<div class="mx-auto mt-5">
		{{< blocks/link-down color="info" >}}
	</div>
```

If you delete `<div class="mx-auto mt-5">	</div>` the `</div>` disapears on your landing page.

he doesn't affect the landing page rendering:

![image](https://user-images.githubusercontent.com/34829865/72521991-e8141b80-385c-11ea-98e8-6a85540456b2.png)

**Comment by LisaFC** [comment]
Hi! Hugo switched to a different Markdown processor (Goldmark) in the most recent major release and it's not 100% compatible with the old one (Blackfriday). I *thought* I'd fixed all the artefacts from the change in our example project and docs - I'll take a look at this one and get it fixed.

**Comment by LisaFC** [comment]
This is really odd because it's the same syntax as the user guide landing page and that works fine. Markdown processors are peculiar.
