### ISSUE TITLE
i18n of page feedback

### ISSUE THREAD

**Issue by tobiaskohlbau** [google/docsy#175]
Currently the `feedback.html` partial is not internationalized as the values are hardcoded into English. 
https://github.com/google/docsy/blob/1b46d71fe3c1894cc17e0b2be066dc5345cbb616/layouts/partials/feedback.html#L17-L19

I've changed the files in my local repo to resolve this issue. If you the maintainers are happy to accept a PR for this I would like to submit it. If you wanna have a look at the current state see here: https://github.com/tobiaskohlbau/docsy/commit/ed57f05f89fe38837a69418e2cb5b33c54d1ee26

**Comment by LisaFC** [comment]
Oh I really like this - this will be very useful for other Docsy users!  Please do submit a PR.

**Comment by chalin** [comment]
@cjyabraham - support has just landed in Docsy (FYI) /cc @nate-double-u
