### ISSUE TITLE
Add option to reference different github branch

### ISSUE THREAD

**Issue by tobiaskohlbau** [google/docsy#176]
Docsy has the feature to link to different edit options within github. This feature does not support the usage of another branch as `master`.

https://github.com/google/docsy/blob/1b46d71fe3c1894cc17e0b2be066dc5345cbb616/layouts/partials/page-meta-links.html#L8-L14

I would like to propose adding a `github_branch` parameter which enables the user to use another branch.  If this feature is from interest I would like to open a PR. My current suggestion could be viewed on: https://github.com/tobiaskohlbau/docsy/commit/ddd4270976df7c98e0a04c94876cbd5e71c4ceeb

**Comment by LisaFC** [comment]
This looks useful! As long as the default value for github_branch is master, as that's what most users use. Please send the PR!
