### ISSUE TITLE
Deploy failed with Netlify and Hugo

### ISSUE THREAD

**Issue by frodriguezsmartclip** [google/docsy#177]
Hi there,

First of all, thanks for this awesome theme. I liked it so much 😍 

I configured the Hugo + theme docsy following this step: [using the github ui](https://www.docsy.dev/docs/getting-started/#using-the-github-ui)  It's working fine in localhost, with "hugo server" and that stuff.

After customizing the template, make commits and push to [my clone repo, this one](https://github.com/frodriguezsmartclip/help-adtopy)

I followed the [guide to deployment with Nelify here](https://www.docsy.dev/docs/deployment/#deployment-with-netlify),

BUT, the deploy on netlify fail 😢 

![Anotación 2020-01-21 103006__8](https://user-images.githubusercontent.com/59822855/72792306-13ba4b80-3c39-11ea-91ef-95e2aa475a61.png)
![Anotación 2020-01-21 103006__9](https://user-images.githubusercontent.com/59822855/72792307-13ba4b80-3c39-11ea-9ed2-fd821a2c3f0e.png)

I attach the deploy log for more information:

> 9:54:55 AM: Build ready to start
9:54:57 AM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
9:54:57 AM: build-image tag: v3.3.5
9:54:57 AM: buildbot version: 6067c60f3bc043bb6b9ee9b57c85b10029c65bfd
9:54:57 AM: Fetching cached dependencies
9:54:57 AM: Failed to fetch cache, continuing with build
9:54:57 AM: Starting to prepare the repo for build
9:54:57 AM: No cached dependencies found. Cloning fresh repo
9:54:57 AM: git clone https://github.com/frodriguezsmartclip/help-adtopy
9:54:58 AM: Preparing Git Reference refs/heads/master
9:55:00 AM: Error checking out submodules: Submodule 'themes/docsy' (https://github.com/google/docsy) registered for path 'themes/docsy'
Cloning into '/opt/build/repo/themes/docsy'...
error: Server does not allow request for unadvertised object 69b41295a946f35fe8b09da648e54c55cf8d9a57
Fetched in submodule path 'themes/docsy', but it did not contain 69b41295a946f35fe8b09da648e54c55cf8d9a57. Direct fetching of that commit failed.
9:55:00 AM: Failing build: Failed to prepare repo
9:55:00 AM: failed during stage 'preparing repo': Error checking out submodules: Submodule 'themes/docsy' (https://github.com/google/docsy) registered for path 'themes/docsy'
Cloning into '/opt/build/repo/themes/docsy'...
error: Server does not allow request for unadvertised object 69b41295a946f35fe8b09da648e54c55cf8d9a57
Fetched in submodule path 'themes/docsy', but it did not contain 69b41295a946f35fe8b09da648e54c55cf8d9a57. Direct fetching of that commit failed.
: exit status 1
9:55:00 AM: Finished processing build request in 3.809179636s

May you help me to fix the issue? Thanks!!!

Hugo Static Site Generator v0.62.2/extended windows/amd64 BuildDate: unknown

Edit:  added screenshots related to git bash and example live in localhost running well:

![Anotación 2020-01-21 113256__10](https://user-images.githubusercontent.com/59822855/72797832-27b67b00-3c42-11ea-821f-45e97f6ae3b1.png)
![Anotación 2020-01-21 113401__11](https://user-images.githubusercontent.com/59822855/72797834-27b67b00-3c42-11ea-90e3-6c8e4affd139.png)

**Comment by LisaFC** [comment]
Thanks for all the information! I'll take a look and see if I can figure out what's going wrong.

**Comment by frodriguezsmartclip** [comment]
Ok Lisa, perfect!! Thanks for your help. I await your recommendations to fix it.  Have a nice day 😉

**Comment by LisaFC** [comment]
Can you do a clean deploy again and see if you get the same error, because I think I just followed your exact steps (forked repo in the UI, made a local copy, pushed some changes back up to my forked repo, deployed from Netlify) and it worked fine. Go to your Deploys page in Netlify and click Trigger Deploy with the "clear cache" option.

If you get the same error I'll have a look at your repo and see if anything's happening there. The error you're getting is a Git error and it's something to do with not being able to find the theme submodule.

**Comment by frodriguezsmartclip** [comment]
Hello Lisa,

Yes, you were right. Something was doing wrong and that's why Netlify failed. I think the reason was that I modified git files from "docsy" (yours from Google), and there were conflicts when netlify wanted to deploy the entire project... 😓 

The steps I have taken to solve it have been: 📝 

1. Remove and delete old fork that I had made.
2. Make new forked repo throught the UI.
3. Move the files from "./themes/docsy/layouts" to "./layouts". Being able here to modify files of the templates without problem of language or conflicts.
4. Make modifications, commit and push to the new own forked repository.
5. Follow your steps to deploy Netlify with hugo
6. Taraaaaaaa. **IT'S WORKS. Magic!!!** hehe 🎉 

That said, thank you very much for your help. I am very happy to be able to use the Hugo combination with your fantastic Docsy theme. 😄 

Have a wonderful day. Regards!
Philip

**Comment by LisaFC** [comment]
Ah great, glad you got it sorted out! And yes, if you want to customize any of the theme layouts, you need to do it in your site's own layouts directory (which overrides the themes/docsy/layouts version) or Netlify will get confused as it's trying to fetch the theme files from GitHub.

And thanks, glad you like the theme (from me and everyone else who's contributed to it!)
