### ISSUE TITLE
sitemap.xml contains relative paths to all pages

### ISSUE THREAD

**Issue by mountaindude** [google/docsy#1774]
Probably missing something obvious here..

_Edit:
Using macOS btw, with Brew-installed `hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended`_

I followed the [instructions for cloning the Docsy example site](https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/).
Building my own site works great, including publishing to GitHub Pages.

I've been using Docsy in the past too, but then without the modules approach. 

Building the site is done using `env HUGO_ENV="production" hugo`
This has worked well in the past, generating correct sitemap.xml files.

The problem now is that the generated sitemap file contains relative paths, rather than full URLs:

```xml
  <url>
    <loc>/docs/command/app-script/</loc>
    <lastmod>2023-11-19T21:28:22+01:00</lastmod>
  </url>
```

The `loc` should instead be something like `https://mysite.some.domain/docs/command/app-script/`.

I've also tried all kinds of variants of the command, like just a simple `hugo` (as per [this page](https://www.docsy.dev/docs/deployment/#build-environments-and-indexing)), deleting the docs folder first etc. 
Same thing, only relative paths for all pages.

Any ideas?

**Comment by fekete-robert** [comment]
Hi,

what does it do if you remove the public folder (or where your output is),
and then run: `hugo --env production --baseURL https://example.com`
?

**Comment by mountaindude** [comment]
Tadaaa!

That was easy.

Guess the create-production-command has changed in recent Hugo versions, did I miss those docs on Hugo or Docsy sites?
Thought I checked it pretty carefully... 
Anyways, works now and maybe this ticket will help someone else in the future.

Thanks!
