### ISSUE TITLE
Smoke tests: feedback

### ISSUE THREAD

**Issue by deining** [google/docsy#1796]
Thanks for providing the smoke tests! They proved to be useful already!
Here comes some feedback:

1. Synopsis, retrieved via `./make-site.sh -h`

    ```
    Creates a Docsy-themed site under SITE_NAME using the Hugo new command.
     Docsy is fetched as an NPM package from google/docsy in GitHub,
     unless the -l or -d HUGO_MOD flags are used.
    ```

    I don't see a `-d` flag, however. I guess this should be `-s`?
    This is now addressed in #1800.

2. Small nit:

    ```
    ./make-site.sh -s foo
    ERROR: invalid argument to -s flag: FOO`
    ```
    This should be `foo`, not `FOO`. Can be fixed easily.
    This is now addressed in #1800.
3. After the hugo build, there is this line on STDOUT:
    ```
    + [[ -n 1 ]]
    ```
    What does that mean?
4. After the npm install, there is this line on STDOUT:
    ```
    + [[ NPM == HUGO* ]]
    ```
    What is that meant for?
4. Running this command fails
    ```
    ./make-site.sh -fv v0.5.1 -s HUGO
    ```
   This was to be expected, since module depencendies were altered in v0.8.0 (#1120). Can we check the version given here and raise and error of below v0.8.0 with module installation? An alternative would be to mention this limitation in the synopsis.

5. Inside the smoke tests there is a matrix defined so that tests can be reused and executed on Linux and Windows machines and for NPM and hugo module build. This seems logical, it comes with one disadvantage, though: as soon as a smoke test for Linux fails, the corresponding smoke test on Windows is cancelled. For me this turned out to be unfortunate, so I decided to create individual action files for the different environments (see this [commit](https://github.com/deining/docsy/commit/9184e12440970983a49be220711573f03f115555) in my docsy fork). Separate workflow also do have the advantage that individual smoke tests now can be easily enabled/disabled without touching the code.

**Comment by chalin** [comment]
Thanks for the detailed feedback, I'll get to it as soon as I'm back at the office the week of the 29th.

**Comment by chalin** [comment]
(1) & (2) Thanks for the fixes you made in #1800. They LGTM once the `name` field changes are reverted.

(3) & (4) As for the output starting with `+`, this is subcommand trace output that comes from `set -x`. This helps diagnose issues when tests fail. If you'd rather not see that, use the `-q` flag. I'd rather keep logging verbose by default in CI jobs though.

(5) The script is meant for internal use. I'd rather not add a version check at the moment, but if it's clean to add, then a PR would be welcome.

(6) At the moment, I'd rather keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), and kind of prefer the abort early.

**Comment by chalin** [comment]
Do you consider that #1800 closes this issue @deining?

**Comment by chalin** [comment]
I'll assume we're good here. If not, feel free to reopen or create another issue.
