### ISSUE TITLE
Offline search does not work with Hugo "relativeURLs" config parameter

### ISSUE THREAD

**Issue by chrvo** [google/docsy#181]
With the Hugo relativeURLs param, hugo replaces all relative urls by urls relative to the current content. (https://gohugo.io/content-management/urls/#relative-urls)
However, this does not work with the search index file which is always "/offline-search-index.HASH.json"

**Comment by LisaFC** [comment]
@tekezo do you have any ideas here?

**Comment by tekezo** [comment]
Thank you for feedback and notifying me!
I confirmed this issue. I'll make a PR.
