### ISSUE TITLE
Header self-link: improve style, ux, customizability, and reusability

### ISSUE THREAD

**Issue by chalin** [google/docsy#1813]
- Followup to:
  - #1460
  - #1463
- [ ] Always show header anchor links on mobile and touch devices
- [ ] Ensure that the anchor can be easily customized
- [ ] Ensure that the anchor can be reused

**Comment by chalin** [comment]
Hmm, I'm no longer sure that using a render hook is a good idea, unless projects can easily opt out of the Docsy heading render hook override. I don't know if that can be easily done. I've posted on the Hugo discourse to see if anyone might know how: [Theme render-hook override: how to fall back to Hugo default?](https://discourse.gohugo.io/t/theme-render-hook-override-how-to-fall-back-to-hugo-default/48101?u=chalin). Thoughts @LisaFC @deining @fekete-robert?

**Comment by fekete-robert** [comment]
I'm not aware of an opt-out solution, other than replacing the render hook
with your own on the project. I don't think we can provide a configurable
option for that, but I'm sure the hugo devs will reply soon.
