### ISSUE TITLE
copyright text is missing in the page footer in 404.html

### ISSUE THREAD

**Issue by adlerzei** [google/docsy#1872]
### Environment

- [x] Version of Docsy you are using: 0.9.1
- [x] How are you using Docsy? As a:
  - [ ] Hugo module
  - [ ] NPM module
  - [ ] Git submodule
  - [x] Other: Fork
- [x] Version of Hugo you are using (output of `hugo version`): 0.122.0
- [ ] OS:
  - [x] Linux
  - [ ] macOS
  - [x] Windows
  - [ ] Other:

### Problem

On the page footer of the 404.html page, the copyright text is missing. This can also be seen on the Docsy user guide: 

![image](https://github.com/google/docsy/assets/9946699/5c111ba4-3fe4-4b4b-8ed9-510210506247)
https://www.docsy.dev/docs/adding-content/notfound/

I would expect the exact same text as on every other page. For the Docsy user guide I would expect to see "Docsy Authors | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0) |" in addition to the text shown.

**Comment by chalin** [comment]
Thanks, I just noticed that too as I was testing Hugo v0.123.3, which fixes the issue, thankfully. I'm marking this "blocked" on:

- https://github.com/google/docsy/issues/1873
