### ISSUE TITLE
Mermaid graph with no parameters defined in hugo config results in 'Uncaught TypeError'

### ISSUE THREAD

**Issue by chulcher** [google/docsy#1882]
https://github.com/google/docsy/blob/a72c57c9398b9795daaeac6f6944369cb76d5adb/layouts/partials/scripts/mermaid.html#L21

If nothing is defined in hugo.toml for [params.mermaid] then the referenced code results in `var params = null` being generated.

https://github.com/google/docsy/blob/a72c57c9398b9795daaeac6f6944369cb76d5adb/layouts/partials/scripts/mermaid.html#L29

Then when attempting the if statement a call is made against a null value, resulting in the browser console error.

`Uncaught TypeError: Cannot read properties of null (reading 'hasOwnProperty')`

**Comment by chulcher** [comment]
The error in the script results in per-diagram theme settings breaking and no diagram being generated.  An empty set of parameters in hugo.toml (i.e., simply adding `[params.mermaid]` with no further parameters) assigns an empty set to `params` and allows successful execution of the script.

**Comment by chalin** [comment]
@deining - could you take a look?
