### ISSUE TITLE
Site param .Site.Author was deprecated in Hugo 0.124.0

### ISSUE THREAD

**Issue by deining** [google/docsy#1899]
We should address the following deprecation warning:

```console
$ npx hugo --logLevel info | grep deprecate
INFO  deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release.
```

According to this [comment](https://github.com/gohugoio/hugo/pull/11569#issue-1946296332), it should be replaced with `.Site.Params.Author`.

**Comment by chalin** [comment]
Closed by:

- #1948
