### ISSUE TITLE
Add a template for an "unmaintained snapshot" banner on archived doc sets

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#190]
Many doc sets create archived snapshots of docs for older versions, and maintain only the latest version of the docs. It would be nice to be able to add a note at the top of every page in the archived docs, to let readers know that they’re seeing a snapshot and give them a link to the latest version.

I've recently done this in the Kubeflow docs. You can see an example in the archived docs for [Kubeflow v0.6](https://v0-6.kubeflow.org/docs/):
![image](https://user-images.githubusercontent.com/6138251/73601084-85cf4200-450f-11ea-8f34-a87f4ffee47a.png)

------

For this pattern in another doc set, see a [Kubernetes example](https://v1-14.docs.kubernetes.io/docs/tasks/tools/install-kubectl/).

**Comment by LisaFC** [comment]
Oh that's very nice! Yes, definitely one to share!
