### ISSUE TITLE
Drop `card-code` in 0.10.0

### ISSUE THREAD

**Issue by chalin** [google/docsy#1921]
`card-code` was deprecated in 0.7.0 -- [CHANGELOG#070](https://github.com/google/docsy/blob/main/CHANGELOG.md#070), I think that we should consider dropping it in 0.10.0.

(I believe that this matches Hugo's new deprecation policy.)

WDYT @deining?

I don't know if the UG would also need to be udpated if we drop the `card-code` shortcode?

**Comment by deining** [comment]
> `card-code` was deprecated in 0.7.0 -- [CHANGELOG#070](https://github.com/google/docsy/blob/main/CHANGELOG.md#070), I think that we should consider dropping it in 0.10.0.
> 
> WDYT @deining?

That's fine for me.

> I don't know if the UG would also need to be udpated if we drop the `card-code` shortcode?

No.

I addressed this issue in #1923.
