### ISSUE TITLE
Revert to using Hugo's `rss.xml` template

### ISSUE THREAD

**Issue by chalin** [google/docsy#1926]
Back in 2019, Hugo's RSS template had a hard-coded Hugo-specific title (#53), which lead to the creation of

- https://github.com/google/docsy/blob/main/layouts/_default/list.rss.xml

via:

- #93

Since then, Hugo's RSS template has been cleaned up, and it actually matches the customization brought in via #93 (and has further improvements).

Related:

- #1900
- https://github.com/gohugoio/hugoDocs/issues/2520

/cc @LisaFC

**Comment by deining** [comment]
+1 for reverting to hugo's default template.

**Comment by LisaFC** [comment]
+1 from me as well, makes sense!
