### ISSUE TITLE
Light/dark mode: display of tags/categories

### ISSUE THREAD

**Issue by deining** [google/docsy#1927]
Out of interest, I enabled a preview of the newly added  light/mode for one of my sites (thanks Patrice, great job!).
With dark mode enabled, I had a look at the right sidebar and realized that we don't really have a dark display here:

![grafik](https://github.com/google/docsy/assets/18169566/befe3555-12ed-4541-ac60-0810a7783eff)

@chalin: can you please have a look and check whether we can alter the background and text color of the tags used here? AFAICS, the tags remain unchanged in dark mode which doesn't really give a great user experience here! Thanks!

**Comment by chalin** [comment]
Thanks for the feedback.

Is it possible that you have custom styling for your project? Here's what I see when I visit https://www.docsy.dev/docs:

- Dark mode:
  > <img width="208" alt="image" src="https://github.com/google/docsy/assets/4140793/1c167cfa-a818-4ea8-a9fa-33537e6d03af">
- Light mode (the same as it has been for a while):
  > <img width="202" alt="image" src="https://github.com/google/docsy/assets/4140793/aadf4997-c772-4e39-b7fc-a4208295c928">

IMHO, the color contrast in dark mode seems ok in what is shown above. WDYT @deining @LisaFC @emckean et al.?

The tag text of your project does seem lighter, but that also seems to be specific to your project.

**Comment by deining** [comment]
> Thanks for the feedback.
> 
> Is it possible that you have custom styling for your project? Here's what I see when I visit https://www.docsy.dev/docs:
> 
>     * Dark mode:
>       > <img alt="image" width="208" src="https://private-user-images.githubusercontent.com/4140793/320447791-1c167cfa-a818-4ea8-a9fa-33537e6d03af.png?jwt=eyJhbGciBiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI5ODcsIm5iZiI6MTcxMjU3MjY4NywicGF0aCI6Ii80MTQwNzkzLzMyMDQ0Nzc5MS0xYzE2N2NmYS1hODE4LTRlYTgtYTlmYS0zMzUzN2U2ZDAzYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTAzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAyMTk1ZGJmZjMxMTE1YjZhODYyM2U0NGZkMjg3YWJlNjcwNTY3ZWUxOTgzMWZhZGRmOWFmNWE1YTA1ZDhjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sPLfDHFQIBbMvn73DHQN3zGNvo7okLz3htxZA6PELIM">
> 
>     * Light mode (the same as it has been for a while):
>       > <img alt="image" width="202" src="https://private-user-images.githubusercontent.com/4140793/320447986-aadf4997-c772-4e39-b7fc-a4208295c928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzI5ODcsIm5iZiI6MTcxMjU3MjY4NywicGF0aCI6Ii80MTQwNzkzLzMyMDQ0Nzk4Ni1hYWRmNDk5Ny1jNzcyLTRlMzktYjdmYy1hNDIwODI5NWM5MjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMTAzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAwOWFjMzY1MmM3OTA5ZmI4ZDYxOWU1OWRkMTY1NTBhNWEzYWI5OGMxNzg4M2M3NmNjMDM0MDRlMzIyN2Q5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QAQcQxaRD0gSopwnvIKDXCF2fXGPRqS4mMdNMikiKOY">
> 
> 
> IMHO, the color contrast in dark mode seems ok in what is shown above. WDYT @deining @LisaFC @emckean et al.?

I just checked: no I don't have custom styling in place here, I'm using the css that comes with docsy by default:

https://github.com/google/docsy/blob/b95a4948ee42e601d2685a334e0b2362e31820ef/assets/scss/_taxonomy.scss#L111-L115

Background and text color of the tags are fix, they do not change with color mode. For a small cloud of categories/tags, this looks o.k., but with a larger tag cloud in place, I woudn't call this a *dark* theme any more. Just my two cents.
