### ISSUE TITLE
How can i add Korean font?

### ISSUE THREAD

**Issue by youngraekim911** [google/docsy#193]
I cannot find how to add the font (KOREAN)

Would you tell me the way to add the font?

it shows break Korean fonts in website if i run the server

**Comment by amzrk2** [comment]
The theme uses Open Sans(English only font) as its primary font.
First you need to disable Google Fonts, add the variable below to your project SCSS `assets/scss/_variables_project.scss`
```
$td-enable-google-fonts: false;
```

Then to use custom `font-family` like this
```
/* Custom font example for my own site(Simplified Chinese) */
$font-family-sans-serif: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", "Arial", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
$font-family-monospace: "Cascadia Code", "SFMono-Regular", "Consolas", "Liberation Mono", "Courier New", monospace !default;
```
You can also set `font-family-base`
```
$font-family-base: $font-family-sans-serif !default;
```

**Comment by youngraekim911** [comment]
@amzrk2 
thank you
actually the main problem i found was UFF-8 code from my text
I've solved the problem thanks
