### ISSUE TITLE
Landing page cover image doesn't work with Hugo 0.64.0

### ISSUE THREAD

**Issue by briankintz** [google/docsy#194]
I installed Hugo extended 0.64.0 and cloned the example site as documented [here](https://www.docsy.dev/docs/getting-started/#using-the-command-line).

The site builds without error using `hugo server`, but `featured-background.jpg` doesn't show as the cover image on the landing page.

Downgrading to Hugo 0.63.2 fixed the problem.

**Comment by TimSiefert** [comment]
Same on my side.

With the exact same code base I tried
0.63.2 -> works
0.64.0 -> doesnt work

**Comment by aborruso** [comment]
The same for me

**Comment by aborruso** [comment]
Solved for me using the last hugo 0.64.1

**Comment by LisaFC** [comment]
That is very weird. Must be a bug in 0.64.0

**Comment by briankintz** [comment]
Looks like it could be this one:

gohugoio/hugo#6851

**Comment by LisaFC** [comment]
Yes, looks like that's the one. I'll close this as it's fixed in the next release.
