### ISSUE TITLE
git first steps to deploy to Netlify

### ISSUE THREAD

**Issue by aborruso** [google/docsy#196]
Hi all,
after installation steps

```
git clone https://github.com/google/docsy-example.git
cd docsy-example
git submodule update --init --recursive
```

I know I must create a new repo on github. To pushing my local files to the newly created repo, I think I should run something like

```
git remote add origin https://github.com/user/myNewRepo.git
```

But I have `fatal: remote origin already exists.` because I already have `https://github.com/google/docsy-example.git`.

Is it the right way to solve to run `git remote rm origin` and than add the new origin? If no, what's the way to do it?

Thank you

**Comment by LisaFC** [comment]
You can do but I think this is quicker (and only one step):
git remote set-url origin https://github.com/MY-SITE/EXAMPLE.git

then check you have the right origin configured:
git remote -v

Hope that helps!

**Comment by aborruso** [comment]
@LisaFC thank you. I think it's important to add it in docsy documentation https://github.com/google/docsy/pull/200
