### ISSUE TITLE
How can i add the color???

### ISSUE THREAD

**Issue by youngraekim911** [google/docsy#198]
When i add the colors in assets/scss/_variables.scss

$covalt: #E0E6F8 !default;

like this

there's no change

**Comment by LisaFC** [comment]
Hi! So the only look and feel values you can change using variables are Bootstrap theme variables: https://getbootstrap.com/docs/4.0/getting-started/theming and https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

You can see the ones we use in the theme in:
https://github.com/google/docsy/blob/master/assets/scss/_variables.scss

In your example it looks like you're trying to define a new colour variable, which Bootstrap doesn't understand. 

You can either override one of the existing variables (eg specify a new secondary colour) in your project's /_variables_project.scss
https://github.com/google/docsy-example/blob/master/assets/scss/_variables_project.scss

...or if that doesn't work for your needs, you can override an entire SCSS file. Hugo will try the project before the theme for any SCSS, so you can – as one example – create your own _assets/scss/_content.scss and get full control over how your Markdown content is styled.
