### ISSUE TITLE
The footer should allow a more flexible copyright statement

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#2]
The Docsy footer should allow copyright statements of the following form:

Copyright 2018 The <product_name> Authors | Documentation Distributed under CC BY 4.0

Also, we should allow the site to specify a fixed copyright date - the date should not adjust to the current calendar year.

**Comment by dltj** [comment]
Agreed and #436.

**Comment by yann-soubeyrand** [comment]
Hello, this is not exactly fixing your issue, but this should allow for an easier footer override: https://github.com/google/docsy/pull/1500.

**Comment by chalin** [comment]
From #1592, which I'm closing in favor of this issue:

> Shouldn't the copyright year (like ©2023) be the year the site was founded (or the year the company was founded) rather than the year the page was last updated? Reference: https://www.copyrightlaws.com/copyright-symbol-notice-year/
> 
> I would like to specify the year in hugo.config.
> 
> layout\partials\footer.html l.21
> 
> ```
>           <span>&copy; {{ now.Year }} {{ . }} {{ T "footer_all_rights_reserved" }}</span>
> ```

**Comment by emckean** [comment]
+1 to copyright not being automatically updated to current year.
If you wanted to make sure the footer was always up to date you could do $originYear – {{ now.Year }}
