### ISSUE TITLE
Sidebar search support and search with Lunr.js

### ISSUE THREAD

**Issue by aborruso** [google/docsy#201]
Hi,
I'm testing docsy, it's great.

My testing site is [this one](https://festive-bohr-4ac225.netlify.com/ricette/) and the repo is [this](https://github.com/opendatasicilia/tansignari-md).

I'm deploying it using netlifly using

```
cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
```

and `HUGO_VERSION` `0.64.1`.

Lunr.js is a great feature, but it works only in 1) and not in 2). For me [150](https://github.com/google/docsy/pull/150) does not work.

Is there something wrong on my repo/files?

Thank you

![image](https://user-images.githubusercontent.com/30607/74373627-214c9680-4ddd-11ea-8fea-66aa0d54d521.png)

**Comment by LisaFC** [comment]
@tekezo, can you think of any reason why this isn't working?

I'll have a look myself as well.

**Comment by aborruso** [comment]
@LisaFC @tekezo is there some demo site and repo where it works? In this way I can try to study it.

Thank you

**Comment by tekezo** [comment]
@aborruso My site uses sidebar search with lunr.js.

- web site: https://tinkle.pqrs.org/docs/
- source: https://github.com/pqrs-org/pqrs.org/tree/master/sites/tinkle

**Comment by aborruso** [comment]
Hi,
I have opened the URL using a mobile browser and nothing happens if I write
something in the form.

Is it normal?

Thank you

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il sab 15 feb 2020, 13:34 Takayama Fumihiko <notifications@github.com> ha
scritto:

**Comment by tekezo** [comment]
@aborruso 
Your docsy submodule is too old. Please update it.
https://github.com/opendatasicilia/tansignari-md/tree/master/themes

You have to hide the keyboard to show search result if your keyboard is too large on mobile device.

**Comment by aborruso** [comment]
hi @tekezo ,
I have updated it in local and it works.

But now the netfly deploys does not work.

How to solve it'

```
2:21:02 PM: Error checking out submodules: Submodule 'themes/docsy' (https://github.com/google/docsy) registered for path 'themes/docsy'
Cloning into '/opt/build/repo/themes/docsy'...
error: Server does not allow request for unadvertised object c96f3204ed027cdc74ec31ad14974fc33fdd3fbb
Fetched in submodule path 'themes/docsy', but it did not contain c96f3204ed027cdc74ec31ad14974fc33fdd3fbb. Direct fetching of that commit failed.
2:21:02 PM: Failing build: Failed to prepare repo
2:21:02 PM: failed during stage 'preparing repo': Error checking out submodules: Submodule 'themes/docsy' (https://github.com/google/docsy) registered for path 'themes/docsy'
Cloning into '/opt/build/repo/themes/docsy'...
error: Server does not allow request for unadvertised object c96f3204ed027cdc74ec31ad14974fc33fdd3fbb
Fetched in submodule path 'themes/docsy', but it did not contain c96f3204ed027cdc74ec31ad14974fc33fdd3fbb. Direct fetching of that commit failed.
: exit status 1
2:21:02 PM: Finished processing build request in 4.173936123s
```

**Comment by tekezo** [comment]
@aborruso I don't know well about netfly, sorry. I think the issue should be filed as another issue.

About mobile browser UX, I made a PR that the on-screen keyboard will be hidden automatically after search keyword is entered.
https://github.com/google/docsy/pull/202

**Comment by aborruso** [comment]
thank you @tekezo

**Comment by aborruso** [comment]
hi @tekezo @LisaFC  , 
I started from a new installation, following the installation instructions:

```bash
git clone https://github.com/google/docsy-example.git

cd docsy-example

git submodule update --init --recursive

hugo server
```

and once again it does not work.

How to make an installation that has the updated submodule?

I think it's important, because reading the official docs every new user will have a version that does not work.

Thank you

**Comment by LisaFC** [comment]
That's very odd. I'll check that the example project is pointing to the most recent version of Docsy (I thought it was) and fix it if so.

Regardless, you can always get the most recent version of Docsy by doing this:
https://www.docsy.dev/docs/updating/#update-a-docsy-submodule

**Comment by aborruso** [comment]
Thank you @LisaFC . When you will do the check I'll do again a test.

**Comment by LisaFC** [comment]
Ok, it was slightly out of date so may have just missed that update, it's now pointing to the current head version so should work fine "out of the box". :)

**Comment by aborruso** [comment]
Thank you @LisaFC 

Now I have an old version: how to update to your update?

Is it `git submodule update --remote --recursive`

Thank you

**Comment by aborruso** [comment]
Ok, I have updated it.

It works all
