### ISSUE TITLE
Unable to use swagger UI short code

### ISSUE THREAD

**Issue by alexandre-touret** [google/docsy#2017]
### Environment

- [X] Version of Docsy you are using: 0.10.0
- [x] How are you using Docsy? As a: 
  - [X] Hugo module
  - [ ] NPM module
  - [ ] Git submodule
  - [ ] Other:
- [x] Version of Hugo you are using (output of `hugo version`): ``hugo v0.125.6-69ede10edcd539380914bbee58d4d32953dd8b43+extended linux/amd64 BuildDate=2024-05-05T10:52:52Z VendorInfo=gohugoio``
- [x] OS:
  - [X] Linux (Ubuntu 24.04)
  - [ ] macOS
  - [ ] Windows
  - [ ] Other:

### Problem

The SwaggerUI shortcode doesn't work anymore.

On my browser's console (I also tested it on several browsers), I have this error:

```
Uncaught ReferenceError: SwaggerUIBundle is not defined
    onload http://localhost:1313/docs/test-swagger/:227
```

Then, when I check the network console, I can see the following issues:

![image](https://github.com/google/docsy/assets/943841/2543397f-1803-4b1b-a2cd-5a4daff7ff61)

It seems the URL used (e.g., https://unpkg.com/swagger-ui-dist@5.1.0/swagger-ui.css) to get the JS artifacts are now blocked.

I tested it on a fresh setup of the docsy example.
The JS and CSS are indeed not unpackaged in the public folder.

Here is the way to reproduce this issue:
* Checkout the docsy example as explained on the documentation (w/ hugo modules)
* Create the folder ``my-new-site/content/en/docs/test-swagger ``
* Add the following page: ``_index.md`` with the following content:

```markdown
---
title: API Reference
description: TEST
weight: 9
type: swagger
---

{{< swaggerui  src="test.json" >}}

```

* Add also a OPENAPI/SWAGGER file besides names test.json

Thanks for your help

**Comment by chalin** [comment]
@theletterf can you take a look?

**Comment by alexandre-touret** [comment]
Hi,
* I tested it on Edge & Firefox 
* I tested both configurations : an update and I reproduced it on a freshly cloned docsy example (BTW, I used to explain how to reproduce this issue)
* I just thought about my corporate computer embeds a local proxy/firewall ZScaler
* I can't access the unpkg URLs from the same browsers

**Comment by theletterf** [comment]
Oh no, ZScaler is terrible... Could you turn it off temporarily and try again? Or try from a different computer? I cannot reproduce this on my laptop:

![Screenshot 2024-05-28 at 11 06 33](https://github.com/google/docsy/assets/1773616/132bf8e9-c456-4876-9880-4751839249e3)

@chalin Not sure if we have other external dependencies like this in Docsy. This one might make things difficult for airgapped environments. I could add this as a note to the documentation.

**Comment by alexandre-touret** [comment]
Hi,
I will try it on my personal computer.

**Comment by alexandre-touret** [comment]
Hi,
Unfortunately, I didn't have time yet to test it on another PC.
I'm to do that this weekend

**Comment by alexandre-touret** [comment]
Hi
I tested it on my personal computer.

It works ...
It was probably due to my company's security restrictions (ZScaler, ...)

Alexandre

**Comment by theletterf** [comment]
Thanks @alexandre-touret. Quite an important report, though. I'll add a note to the docs.
