### ISSUE TITLE
Error Cloning the Docsy theme to my project’s themes subdirectory

### ISSUE THREAD

**Issue by aborruso** [google/docsy#204]
Hi,
these are my steps:

- first of all read https://www.docsy.dev/docs/getting-started/#cloning-the-docsy-theme-to-your-project-s-themes-subdirectory
- then `cd themes`
- then `git clone https://github.com/google/docsy`
- then `cd ..`
- and `hugo`

I have this error:

```
Building sites … ERROR 2020/02/16 10:30:52 Transformation failed: SCSS processing failed: file "stdin", line 6, col 1: File to import not found or unreadable: ../vendor/bootstrap/scss/bootstrap.
```

Probably it's necessary to add some note in this [page](https://www.docsy.dev/docs/getting-started/#cloning-the-docsy-theme-to-your-project-s-themes-subdirectory), but I do not know which. To add fontawesome and bootstramp repo??

Thank you

**Comment by LisaFC** [comment]
Yep, you need fontawesome and bootstrap locally to use Hugo on your local machine, basically you need to recurse everything down (the two repos are submodules of the Docsy theme itself).

It's documented here:
https://www.docsy.dev/docs/deployment/#serving-your-site-locally

**Comment by aborruso** [comment]
I have added a PR https://github.com/google/docsy/pull/206

Thank you

**Comment by LisaFC** [comment]
Thanks!! I'll close this once your PR is in.

**Comment by deitch** [comment]
Is this somewhat out of date? I had been trying using docsy as a git submodule, so:

```
git submodule update --init --recursive
```

but I still get the errors, no submodules cloned, same missing `../vendor/...` error. So I looked at the docsy source, and I see no `.gitmodules` file at all.

Is submodules no longer supported?

**Comment by deitch** [comment]
Eh, never mind. I switched to hugo modules. Still cannot get dependencies working, but I will find a relevant issue or open a new one.

**Comment by wtchangdm** [comment]
(Sorry for digging this old issue out again)

Hi @deitch, have you found any solutions? I switched to hugo module but can't get it work.

**Comment by laurentforet** [comment]
I had the same issue, in order to make it works, I had to follow the installation pre-requisite (https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/#install-postcss) in the themes/docsy folder
