### ISSUE TITLE
Docsy not compatible with latest Hugo version

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#205]
I'm using the following Hugo version:
$ hugo version  v0.64.1/extended darwin/amd64

It seems that the shortcodes do not work properly with the latest Hugo version (v0.64.1 extended). For example, the blocks on the home page do not appear. Reverting to an older Hugo version (Hugo 0.53) does work. On a side note, I noticed that https://example.docsy.dev/ uses an older Hugo version as well. Please advise.

**Comment by LisaFC** [comment]
It should still work, the upgrade to 0.60 changed the Markdown parser that Hugo uses, so you need to make a couple of tweaks if you're using an older config file/copy of the example project - basically you need to tell Goldmark to render HTML as well as Markdown to get the shortcodes to work properly in both 0.60+ and older versions:
https://www.docsy.dev/docs/adding-content/content/#page-contents-and-markup

We also found one more tiny bug if you're using an old copy of the example project:
https://github.com/google/docsy/issues/174

I do recommend joining the docsy-users mailing list as we send out mails when we find/fix big  issues like this,  as well as updating the docs.

**Comment by arnonzooz** [comment]
Hi @LisaFC . Yes, that solved it. Thanks! 
Closing this issue.
