### ISSUE TITLE
Drop `rss_sections` from the user guide

### ISSUE THREAD

**Issue by chalin** [google/docsy#2055]
While is see `rss_sections` in the docs, I don't see it referenced in the layouts. Am I missing something here?

I've done a global search through GitHub and only found one project's layout that uses this parameter: https://github.com/apache/beam/blob/50a3403a4742e1c9e264f57f4411969daeff4642/website/www/site/layouts/index.feed.xml#L23

> <img width="831" alt="image" src="https://github.com/user-attachments/assets/3c13b358-cf12-4cae-955e-d5e2df501920">

**Comment by chalin** [comment]
If it isn't used, then we should strip it out of the docs and the config.

**Comment by chalin** [comment]
Ah, we lost that feature when we made the switch to using Hugo's template:

- #1948

I'd vote to clean it out of the docs as well. WDYT @emckean @LisaFC?

**Comment by LisaFC** [comment]
I can't see any reason to keep it in the docs given that it isn't currently used in the actual theme.

**Comment by LisaFC** [comment]
I can do the PR for removing it from the docs if you like.
