### ISSUE TITLE
Google Search defaults to home page

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#207]
Hi,

I setup Google search as explained in https://www.docsy.dev/docs/adding-content/navigation/#setting-up-site-search. I also have a content/en/search.md file. However, when entering a search term in the Search box and pressing enter, I'm redirected to the home page instead of to the search results page. 

Is this an issue or am I missing something?

Thanks!

**Comment by RichieEscarez** [comment]
If you link your repo, when I get a chance I'll take a look to see if something is indeed missing?

**Comment by arnonzooz** [comment]
Hi,

I think it might be related to this code in assets/js/search.js:
```
var query = $(this).val();
var searchPage = "{{ "search" | absURL }}?q=" + query;
document.location = searchPage;
```

Hard-coding it to the correct url works (though this is not what you'd want):
```
var query = $(this).val();
var searchPage = "{{ "/en/search.html" | absURL }}?q=" + query;
document.location = searchPage;
```

My private is private, but can publish to a public repo if needed. But maybe the issue is indeed in the above?

**Comment by RichieEscarez** [comment]
That's great that you figured it out!

Without knowing more, it looks like `absURL` requires that your `baseURL` is set (maybe a contributing factor?):
https://gohugo.io/functions/absurl/
https://gohugo.io/functions/abslangurl/

Hope that helps.

**Comment by arnonzooz** [comment]
I actually have a baseURL defined in my config.toml.

So all works now :). Closing the issue.

Thanks for helping!
