### ISSUE TITLE
Same configuration but different behavior in user relevant links

### ISSUE THREAD

**Issue by BrentHuang** [google/docsy#2076]
### Environment

- [x] Version of Docsy you are using: v0.10.0
- [ ] How are you using Docsy? As a:
  - [x] Hugo module
  - [ ] NPM module
  - [ ] Git submodule
  - [ ] Other:
- [x] Version of Hugo you are using (output of `hugo version`): v0.134.0
- [ ] OS:
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
  - [ ] Other:

### Problem

in hugo.toml, 

```
[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
name = "aa"
url = "https://cdn.pixabay.com/photo/2024/08/24/14/42/elephant-8994442_1280.jpg"
icon = "fa-brands fa-weixin"
desc = "aaa"
[[params.links.user]]
name = "bb"
url = "https://cdn.pixabay.com/photo/2019/09/15/04/23/rhinoceros-4477306_1280.jpg"
icon = "fa-brands fa-qq"
desc = "bbb"
```

When I click on aa it opens the jpg file in the browser, but when I click on bb it downloads the jpg file, why?
I would expect both to open the file in the browser, not download it.

**Comment by fekete-robert** [comment]
That has nothing to do with docsy/hugo IMO, if you copy those links into a private browser window they show the same behavior. (My guess is that for some reason the server doesn't set the mime type of the second file.)
