### ISSUE TITLE
Docsy SCSS overriding Hugo 0.60+ highlight style

### ISSUE THREAD

**Issue by kmuncie** [google/docsy#214]
The background colors set below seem to be overriding the native Hugo highlight styles after upgrading to Hugo 0.60+

- https://github.com/google/docsy/blob/master/assets/scss/_code.scss#L10
- https://github.com/google/docsy/blob/master/assets/scss/_code.scss#L41

This is especially noticeable with the darker code style themes such as the [default theme of monokai](https://gohugo.io/getting-started/configuration-markup#highlight) as seen below:

![docsy-highlight-bug](https://user-images.githubusercontent.com/582755/75117483-96626c00-5626-11ea-9405-388f55d95956.jpg)

Thank you for your time looking at this.

**Comment by LisaFC** [comment]
Thanks for spotting that, I'll take a look.

**Comment by frodriguezsmartclip** [comment]
@kmuncie yeah, therefore I've configured the Prism.JS to highlight code in my custom theme docsy. So, I dont have to depend if Hugo change the settings for highlighting or something became overriding in theme...

[Here I explain better](https://github.com/google/docsy-example/issues/37#issuecomment-586157096).

Regards!! ;)

**Comment by gittur** [comment]
@LisaFC, any updated on this? the issue still persists.

**Comment by LisaFC** [comment]
Thanks for the reminder! Will try to look at it this week.

**Comment by gittur** [comment]
hey @LisaFC, Sorry to bother again, but any chance you could take a look at this soon :)

**Comment by LisaFC** [comment]
Hey, sorry for the late reply (I was on vacation), I will try to get to it this week along with catching up on the day job. :)

**Comment by LisaFC** [comment]
OK, I've fixed it but need to make sure it doesn't do anything really bizarre for people using pre-0.60 Hugo.

Might do a quick survey on the mailing list....

**Comment by LisaFC** [comment]
One other thought is that if you don't specify a language for the block you don't get your chosen highlight formatting (it's just black text on a grey background) but I *think* that's a Hugo thing rather than anything in our CSS. You can get around it by setting "guessSyntax" to "true" and then all fenced code blocks end up in a highlight div (it hasn't given me anything particularly odd yet, but...).

Also my fix definitely gives ok results deploying with 0.59 so I think I'll get a PR together.

**Comment by LisaFC** [comment]
Have a look at #312. It does mean that users who update to the latest template will also need to update their config.toml files if they don't want to use Monokai, but maybe that's ok?

**Comment by gittur** [comment]
Hey @LisaFC ,just tested it, everything working for me. Thanks a lot. :+1: :pray: 

Hugo version:
Hugo Static Site Generator v0.68.3-157669A0/extended linux/amd64 BuildDate: 2020-03-24T12:13:38Z
