### ISSUE TITLE
PostCSS required for exampleSite

### ISSUE THREAD

**Issue by sdcote** [google/docsy#2146]
Followed the instructions for installing the example site. Received an error:

```
Error: error building site: POSTCSS: failed to transform "/scss/main.rtl.css" (text/css). You need to install PostCSS. See https://gohugo.io/functions/css/postcss/: binary with name "postcss" not found using npx
```

at step: [Preview your site](https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/#preview-your-site)

Using:
- hugo extended v0.139.3
- WIndows 11 Enterprise (10.0.22621)
- node v22.11.0
- npm  v10.5.2

Will try to install PostCSS manually and retry.

**Comment by sdcote** [comment]
Ran `npm i -D postcss postcss-cli autoprefixer`, then ran  `hugo server` but still received the same error.

**Comment by sdcote** [comment]
Fails with Ubuntu and its latest npm (8.5.1) and Hugo (v0.92.2+extended linux/amd64) versions:
```
Error: Error building site: "/home/sdcote/my-new-site/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

**Comment by deining** [comment]
> Hugo (v0.92.2+extended linux/amd64) versions:

This hugo version is ways too old. Use the latest hugo version 0.139.4, and you will be (hopefully) fine.

**Comment by sdcote** [comment]
> As mentioned in the section [Troubleshooting](https://github.com/google/docsy-example?tab=readme-ov-file#troubleshooting) of the example site::
> 
> > Hugo (v0.92.2+extended linux/amd64) versions:
> 
> This hugo version is ways too old. Use the latest hugo version 0.139.4, and you will be (hopefully) fine.

Yeah, I figured as much. That is the default Ubuntu installation.

**Comment by wismann** [comment]
So your problem on Linux is fixed by using an up-to-date version of hugo ?

What about your problems on Windows ?

> Ran `npm i -D postcss postcss-cli autoprefixer`, [...]

This should not be necessary as the dependencies are already baked in the example's `package.json`. A simple `npm install` shoud suffice to install `autoprefixer` and `postcss-cli`.

> [...] then ran `hugo server` but still received the same error.

Have you tried running `npm run serve` on Windows in your project folder?

**Comment by sdcote** [comment]
I finally got it running using one of the alternate methods (modules) so I will not spend any more time on this.

This is more of a notification that the "[Create a new site: start with a prepopulated site](https://www.docsy.dev/docs/get-started/docsy-as-module/example-site-as-template/)" instructions did not work as explained. There are several more steps involved.
