### ISSUE TITLE
Sidebar menu should expand only immediate children, not the whole child graph

### ISSUE THREAD

**Issue by trauts2** [google/docsy#215]
Menu expansion is a bit aggressive for large topic graphs.  

https://www.loom.com/share/b6a00338a8094ed39404107be3f534d7

Instead it would be better if only immediate children were expanded vs the whole child graph.

Also I would really like to see arrows indicating the presence of children for a given node.

Docsy is great btw!  Thanks.

**Comment by frodriguezsmartclip** [comment]
> Also I would really like to see arrows indicating the presence of children for a given node.

Yeah, I'm agree this would be nice if it's developed to docsy theme! 👌

**Comment by LisaFC** [comment]
Thanks for the feedback (the video is super useful to show the problem!). So if you set `sidebar_menu_compact = true` in `config.toml `(the default is `false`) you *should* get the behaviour you want, I've tested it here:
https://brave-shockley-bc9517.netlify.com/docs/tasks/

(**Core Tasks** is selected, its immediate child nodes are displayed but **Working with Ponycopters** isn't expanded until you click on it)

Is there anything else I'm missing?

Arrows are a good idea though (nodes with children being in bold is a bit hard to see in some contexts) and thanks for reminding me of that previous issue, seems like something a lot of users would like particularly with the compact menu.

**Comment by trauts2** [comment]
Thank you Lisa!  It works great. I missed that, it is covered in your
(excellent) docs.

Since I have your ear on menus, might I pick your brain on one more related
topic?  Our app is extensive, and taking a comprehensive pass at
documentation rewrite.  Certain readers will be interested in only subsets
of the application.  And for those users we want to have an alternate menu
which just contains those subsets, omitting whole document sections which
aren't applicable.

I love that Hugo's menu is driven off of the structure of the content dir.
Is it possible to keep that, but selectively omit certain nodes and their
children, in front matter maybe?  I've read the hugo docs on multiple
menus, but to be honest it isn't clear me what the Hugo Way to this is.

Thanks!

Stu

**Comment by LisaFC** [comment]
Yes, that's totally possible, in fact I'm pretty sure I hacked it into a test/demo of something but never included it in the main template.

I'll open a new issue to add it to the theme.

**Comment by LisaFC** [comment]
Even better, it is actually already in the theme, I just forgot about it. :)
https://www.docsy.dev/docs/adding-content/navigation/#section-menu

Add `toc_hide: true` in your page frontmatter and the content won't appear in the TOC

**Comment by trauts2** [comment]
Thanks for the suggestion Lisa.  Yes that does omit the page from the side menu.  But what we're looking for is basically two separate doc-use experiences for side menus.  One, where the user would see the full content graph with all pages.  And a second one where they would see that same menu BUT with n number of branches removed.  So basically two different menus, where one is a subset of the other, and preferably that subtraction would be driven by metadata in the front matter.

I'll be a little surprised if Hugo can do this.  Noodling on ways to do this with javascript dynamically deleting bits from the menu...

**Comment by prdsoftware** [comment]
+1 on this feature.  This would be great.
