### ISSUE TITLE
HUGO_ENV production prevents site from being indexed by Google on AWS

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#217]
The following code in the header partial will prevent Google from indexing a Docsy based site unless the HUGO_ENV env variable is set to PRODUCTION. 

```
{{ if eq (getenv “HUGO_ENV”) “production” }}
<META NAME=“ROBOTS” CONTENT=“INDEX, FOLLOW”>
{{ else }}
<META NAME=“ROBOTS” CONTENT=“NOINDEX, NOFOLLOW”>
{{ end }}
```

I'm deploying my site an AWS bucket and so far as I know the env variable cannot be read (https://stackoverflow.com/questions/36226645/configuring-environment-variables-for-static-web-site-on-aws-s3). So I ended up commenting out those lines of code.

Does anyone have experience deploying to AWS and handling the above?

**Comment by LisaFC** [comment]
This might be a good issue to raise on the [Hugo forums too](https://discourse.gohugo.io/), as it'll affect sites that use other themes too.  I'll see if I can figure anything out in the meantime but I haven't deployed to AWS myself.

**Comment by LisaFC** [comment]
(do let us know if the Hugo people have any ideas as we can add any workarounds to the docs)

**Comment by arnonzooz** [comment]
Hi, 

I raised this on the Hugo forums. See https://discourse.gohugo.io/t/checking-env-variable-prevents-site-from-being-indexed-by-google-on-aws/23707

**Comment by LisaFC** [comment]
Oh great, can you try the solution that bep suggests and if it works we can see about updating the theme.

**Comment by arnonzooz** [comment]
Hi, tested it and it seems to work.

Now onto figuring out why Google refuses to fetch Hugo's sitemap :).

**Comment by arnonzooz** [comment]
Closing this issue.

**Comment by mhansen** [comment]
Hi, I just got bitten by this today on Graphviz and some of our pages are might be unindexed by Google till I redeploy :-( 

https://gitlab.com/graphviz/graphviz.gitlab.io/-/issues/99

Above, @LisaFC mentions "it works we can see about updating the theme", could we reopen this issue to track updating the theme so that others aren't bitten by this?
