### ISSUE TITLE
Regular Releases of Docsy

### ISSUE THREAD

**Issue by markmandel** [google/docsy#218]
I would love to see Docsy have some releases, so we know when Docsy is in a stable state to be used.

Personally, I would advocate some kind of time based release process (i.e. every n weeks, there is a release), since it means something is always getting released, and people know when it's coming.

There are lots of tools for generating changelogs / release lists as well if you would like suggestions.

Either way this project is awesome, please keep up the amazing work :+1:

**Comment by LisaFC** [comment]
Thanks Mark! And that's a great idea, especially as we're now a bit more mature (hem hem) and have a bigger community of users - having something a bit more formal than mailing list and issues page to let people know what's been updated.

Suggestions for release notes/changelog tooling would be great, also if you (or anyone else) thinks it would be useful to keep branches for older versions.

**Comment by markmandel** [comment]
We use the https://github.com/github-changelog-generator/github-changelog-generator (via Docker), it works quite well.

You can see our changelog here: https://github.com/googleforgames/agones/blob/master/CHANGELOG.md

**Comment by gwatts** [comment]
@LisaFC just bumping this one as i think it would be useful; especially when features are added that depend on newer versions of Hugo - Would be a good signal that going from "1.0.0" to "1.1.0" might require a Hugo upgrade, whereas "1.0.0" to "1.0.1" is probably just a bug fix

**Comment by LisaFC** [comment]
This is v timely as we plan to establish a bit more lightweight proper project governance, with a roadmap and possibly more organized releases (and lots of work by @emckean as she Knows About These Things). Will hopefully send out something by the end of the year with some ideas, invite to community meeting (whee!), etc.

**Comment by gwatts** [comment]
@LisaFC awesome; sounds great!  I trust jaffa cakes will be provided at communities meetings ;-)
