### ISSUE TITLE
Scroll and menus break when creating custom section

### ISSUE THREAD

**Issue by secsonthebeach** [google/docsy#220]
Hello, when following the instructions on https://www.docsy/dev/adding-content/content/#custom-sections, the resulting page does not behave properly.

I initially added multiple subdirectories under content/ and then duplicated the templates in themes/docsy/layouts to match the subdirectory name. This worked well, but I realized that keeping docsy up-to-date would not work this way. So I removed the additional layouts, and began  adding `layout: docs` to the front matter of all of my files in the new content/subdirectories

The pages render, but as if it were scrolled to the bottom of the page, and will not scroll up. Also, there is no left nav menu.

Moving everything back under 'docs' works properly, but I was hoping to better organize and categorize things.

**Comment by LisaFC** [comment]
Ok, can you try doing
`type: docs`
instead of
`layout: docs`
in the frontmatter?

That definitely now works for me (I just tried it), if it works for you I'll update the docs and close this.

**Comment by secsonthebeach** [comment]
That definitely works for me as well. Such a simple change! Thank you very much for you help and quick reply @LisaFC

**Comment by LisaFC** [comment]
Great! happy to help.
