### ISSUE TITLE
Sync Layouts partial with custom code

### ISSUE THREAD

**Issue by frodriguezsmartclip** [google/docsy#227]
Hi there,

I have a custom layouts partials, not using the [https://github.com/google/docsy/tree/master/layouts/partials](https://github.com/google/docsy/tree/master/layouts/partials)

But, I would like to know if it's possible to get syncing layouts from docsy git and not to overwrite my custom layouts

BTW, I followed up this docu guide: [https://www.docsy.dev/docs/getting-started/#using-the-github-ui](https://www.docsy.dev/docs/getting-started/#using-the-github-ui), so I have a fork from docsy inside my github account.

```
git remote -v
origin  https://github.com/fr........./docs-adtopy.git (fetch)
origin  https://github.com/fr......../docs-adtopy.git (push)
```

Any ideas to merge and get the last updates related to "docsy theme"?

I only did and execute this by terminal:

```
$ git submodule update --remote
Submodule path 'themes/docsy': checked out 'b75b52f62b0559ac4955814ce1b8b73e3ce4d0ab'
```

Thanks!! Regards. 😃

**Comment by LisaFC** [comment]
Yes, you can totally sync from the Docsy theme without overwriting your custom layouts - you should have your custom layouts in the *project* layouts directory (eg /myproject/layouts/...) and the Docsy layouts will be in the *theme* layouts directory (ie /myproject/themes/docsy/layouts/...). Hugo looks for layouts in your project first so anything you've put in the project directory will override the corresponding layout in the theme.

And yes, you update to the latest (head from this repo) version of the theme by doing:
`git submodule update --remote`

If you want to push the update back up to your project repo you also need to run:
```
git add themes/
git commit -m "Updating theme submodule"
git push origin master
```

I presume the project you forked was the docsy-example? That should be easy to update the theme version using the commands I provided above.

Let me know if anything doesn't work!

**Comment by frodriguezsmartclip** [comment]
@LisaFC Thanks a lot for your rapid response!

Ok, I'll do that.

Yep, I followed the documentation inside docsy: [https://www.docsy.dev/docs/getting-started/#using-the-github-ui](https://www.docsy.dev/docs/getting-started/#using-the-github-ui)

and yes, I forked https://github.com/google/docsy-example   Is that correct?  Or I forked wrong repo??

I write down on the console:

```
$ git submodule update --remote
Submodule path 'docsy': checked out '12ea90da3344a3c4619436f646ec706d99b69351'
```

Is that correct?

Thanks!!

**Comment by LisaFC** [comment]
Yep perfect!

**Comment by frodriguezsmartclip** [comment]
Ok, then, issue resolved. Thanks a lot Lisa. I close this.

Have a nice day!!
