### ISSUE TITLE
Please explain how to adhere to the license requirements

### ISSUE THREAD

**Issue by staenker** [google/docsy#229]
Hi,
we are going to use docsy for our open source project web site. In order to avoid license problems,
we'd like to know if and how we have to note that we are using docsy.
Thanks for clarifying this :)

**Comment by emckean** [comment]
Thank you for using Docsy! We ask the license to be reproduced in all redistributions of the software. You can do this just by making sure to keep the LICENSE file in your Docsy repo. (And if you wanted to link to Docsy on your About page, we wouldn't say no, but it's not a requirement.)

You can also check out the [Apache FAQ](http://www.apache.org/foundation/license-faq.html).

I hope this helps!

**Comment by staenker** [comment]
I did check the Apache FAQ, but I'm no expert in law and contracts, especially when it comes to defining what redistribution vs usage...

We do have a note in the footer of our website: "This website was created using Hugo and the Docsy Template"
The website is also version controlled on a public github repo, which contains the original LICENSE file under the directory: ./themes/docsy (https://github.com/quantummaid/hugo-website/tree/master/themes/docsy)

So if you say that this is sufficient, I'm happy and thank you for saving us a ton of work publishing our frameworks.

**Comment by LisaFC** [comment]
Yes, that's fine! Glad you're finding Docsy helpful!
