### ISSUE TITLE
Side menu does not show only immediate children

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#231]
Hi,

Setting sidebar_menu_compact = false expands all entries in the TOC. This is indeed what I want. However, I only want immediate children to appear expanded (so I don't want the topics in a subfolder to appear expanded as well). 

https://www.loom.com/share/183270af03424fee99d06b03e66b9829

Notice that the topics within 'Working with Ponycopters' appear as well. This is what I don't want.

I realize this seems a duplicate of issue #215 but the behavior I need is somewhat different.  

Thanks

Arnon

**Comment by arnonzooz** [comment]
I hacked the default theme somewhat to illustrate the desired behavior. See the movie below. Notice how the TOC is expanded (sidebar_menu_compact = false) but the topics within 'Working with Ponycopters' only appear when clicking the 'Working with Ponycopters' toc entry.

https://www.loom.com/share/0363f5aa69b9488583113c16e194638a

I'm struggling with the correct syntax for implementing this. Any suggestions/help would be appreciated!

Thanks

**Comment by emckean** [comment]
Hi, closing this as it's been dormant for so long -- if you have more feedback or want to submit a PR, please feel free to reopen!
