### ISSUE TITLE
Support for video

### ISSUE THREAD

**Issue by willwade** [google/docsy#233]
Just a request. Support for the video shortcode: https://github.com/martignoni/hugo-video

**Comment by tshort** [comment]
That particular shortcode implementation has a GPL3 license, so it can't be brought into Docsy directly. You can combine them locally in your own template.

There are other options. Here's one: https://github.com/laozhu/hugo-nuo/blob/master/layouts/shortcodes/video.html

**Comment by willwade** [comment]
Sure. That other one works well. I couldn’t work out how to add a short code outside of the theme - is that possible?

**Comment by tshort** [comment]
You can copy your preferred shortcode to `layouts/shortcodes/video.html` in your site directory.

**Comment by LisaFC** [comment]
Yes, anything you put in your own project's layouts/shortcodes/ directory will either override (if it has the same name as one of the theme shortcodes) or be added to the shortcodes available for your site. If you're happy with that I can close the issue?

**Comment by willwade** [comment]
Sure. Thanks for putting together a fab project. :)
