### ISSUE TITLE
how can I make the local search box large?

### ISSUE THREAD

**Issue by medyagh** [google/docsy#234]
Hi thanks for this great project, we use and love it in minikube. https://minikube.sigs.k8s.io/

I am experimenting with adding local search, I would like to know how I can make the search result box bigger for the local search ?

https://github.com/kubernetes/minikube/pull/7253

thank you !

**Comment by LisaFC** [comment]
@tekezo, any suggestions for a CSS override this user could try?

**Comment by LisaFC** [comment]
And glad you like the project!

**Comment by tekezo** [comment]
I create a PR for this issue.
https://github.com/google/docsy/pull/241

It makes the local search result box bigger.

If you want to manage the width, put the following style into _variables_project.scss.

```scss
body {
    .popover.offline-search-result {
      max-width: 460px;
    }
} 
```

**Comment by medyagh** [comment]
thank you very much @LisaFC  and @tekezo . you rock !
