### ISSUE TITLE
Error after updating Docsy theme submodule

### ISSUE THREAD

**Issue by alexearnshaw** [google/docsy#238]
Hi Docsy people!

I've been wanting to update my Docsy submodule for a while, and finally gave it a try today, but I'm getting an error:

```
aearnshaw@ITEM-AX32372 ~/axway-open-docs (master)$ git submodule update --remote
Submodule path 'themes/docsy': checked out '3123298f5b0f56b3315b55319e17a8fa6c9d98f9'
aearnshaw@ITEM-AX32372 ~/axway-open-docs (master *)$ hugo server
Building sites … ERROR 2020/04/03 16:24:34 Transformation failed: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 8, col 1: File to import not found or unreadable: ../vendor/Font-Awesome/scss/fontawesome.scss. . Check your Hugo installation; you need the extended version to build SCSS/SASS.
ERROR 2020/04/03 16:24:35 Transformation failed: TOCSS: failed to transform "scss/cms.scss" (text/x-scss): SCSS processing failed: file "/home/aearnshaw/axway-open-docs/themes/docsy/assets/scss/main.scss", line 8, col 1: File to import not found or unreadable: ../vendor/Font-Awesome/scss/fontawesome.scss. . Check your Hugo installation; you need the extended version to build SCSS/SASS.
Built in 6192 ms
Error: Error building site: logged 2 error(s)
```

As you can see it looks like I'm getting the latest version of Docsy, (commit '3123298f5b0f56b3315b55319e17a8fa6c9d98f9') but for some reason the submodules Docsy includes (Fontawesome and Bootstrap) are not being updated to whatever versions Docsy is using in the latest version...

When I check on my local system the `vendor/Font-Awesome/scss/` folder does not exist.

Am I doing something wrong? I'm fairly sure the last time I updated Docsy using `git submodule update --remote` everything worked fine and I didn't have to update anything else. This was several months ago however, so maybe Docsy has been updated to use a new version of Fontawesome since then.

Any help much appreciated!

FYI The project where I'm using Docsy is https://github.com/Axway/axway-open-docs

**Comment by LisaFC** [comment]
Try:

git submodule update  --recursive

Another thing that can cause that error is if you don't have postcss and autoprefixer installed in the directory where you're running hugo

https://www.docsy.dev/docs/getting-started/#install-postcss

Hope one of those helps!

**Comment by LisaFC** [comment]
any luck?

**Comment by alexearnshaw** [comment]
Thanks @LisaFC I didn't get a chance to try this yet as had to move on to something more urgent. I'll update when I can.

**Comment by emckean** [comment]
Hi, closing this as no updates for a while -- if this is still an issue and you have more feedback to add, please feel free to reopen!
