### ISSUE TITLE
offlineSearch: show more results and paginate

### ISSUE THREAD

**Issue by medyagh** [google/docsy#243]
Thank you for improving the offlineSearch and adding my previous suggestion, https://github.com/google/docsy/issues/234

I have another feature request for the offlineSearch, I would like it to show more results, and possibly paginate the results (when available) currently the results are limitted to the first few .

is that possible ?

**Comment by tekezo** [comment]
I make a PR https://github.com/google/docsy/pull/275 which adds a configuration option `offlineSearchMaxResults`.
It provides a way to change the maximum result count.

**Comment by LisaFC** [comment]
Closed as fixed in #275
