### ISSUE TITLE
How can I remove the commit message from the last modified string

### ISSUE THREAD

**Issue by pwinston** [google/docsy#246]
I might have just missed it, but I could not see in the docs or in config.toml how to remove the commit message from the last modified string. The text in the red oval below:

<img width="662" alt="Screen Shot 2020-04-10 at 8 58 12 PM" src="https://user-images.githubusercontent.com/4163446/79031659-3c821b00-7b6e-11ea-922d-c40b4180e312.png">

**Comment by pwinston** [comment]
I figured it out set `enableGitInfo = false` in the `config.toml`.

Nothing to see here!

**Comment by tyler71** [comment]
@pwinston 
I believe that will also cause the "Last modified" date to use the frontmatter and not git
if you copy 

```
themes/docsy/layouts/partials/page-meta-lastmod.html
-> layouts/partials/page-meta-lastmod.html
```
and remove 
```
{{ with .GitInfo }}: <a  href="{{ $.Site.Params.github_repo }}/commit/{{ .Hash }}">{{ .Subject }} ({{ .AbbreviatedHash }})</a>{{end }}
```
so it looks like this:
```
{{ T "post_last_mod"}} {{ .Lastmod.Format .Site.Params.time_format_default }}
```
It'll use the git date and not show the circled content.

**Comment by mjang-cobalt** [comment]
Thank you @tyler71 

IOW, we do what you suggest
- and set `enableGitInfo = true` in the `config.toml`

Otherwise, I end up with the following date:

`January 01 0001`
