### ISSUE TITLE
Sidebar in docs not populating

### ISSUE THREAD

**Issue by eribean** [google/docsy#250]
Sidebar nav is no longer populating list of available links.  An example is found [here](https://eribean.github.io/girth/api/).

**Comment by eribean** [comment]
It looks like the "collapse show" class isn't toggling for <ul> element when selecting  top-level link.

**Comment by frodriguezsmartclip** [comment]
Here looks fine: https://eribean.github.io/girth/api/ability_methods/

Try to change "_index.md" to "index.md" for showing these: https://github.com/eribean/girth_docs/blob/99abcbc4e0f7138bfe1db2f17f4a2879765ac04c/content/api/ability_methods/_index.md

**Comment by eribean** [comment]
@frodriguezsmartclip when I change ```_index.md``` to ```index.md``` nothing shows up at all.

**Comment by brettkoonce** [comment]
i noticed this as well as a side effect when hugo got updated to 0.69, would suggest you roll back to .68.3 for now and wait for a fix.

**Comment by eribean** [comment]
@brettkoonce Is this a theme related issue or hugo related issue?

**Comment by brettkoonce** [comment]
would guess theme? don't have the cycles to chase it.

**Comment by eribean** [comment]
Can confirm rolling back to 68.3 gets rid of the issue. I guess I'll close the issue and open up a general issue about compatibility with 69.0.
