### ISSUE TITLE
Compatability Issues with Hugo 0.69.0

### ISSUE THREAD

**Issue by eribean** [google/docsy#251]
Building the site under Hugo 0.69.0 results in side nav for ```type: docs``` not to expose the sidebar links correctly. This works fine under Hugo 0.68.3

**Comment by eribean** [comment]
One clue I've noticed is the \<ul> doesn't toggle the ```show``` class when top links are clicked.

**Comment by brettkoonce** [comment]
see also #250

**Comment by LisaFC** [comment]
Hmm, that's annoying.  I think you've fixed the problem by rolling back in the linked issue, can you clarify exactly what's happening with 0.69.0? The subtrees in the left nav aren't displaying?

If it is, I wonder is it related to this, as the partial for the navbar uses the fact that pages are descendants of sections?

https://github.com/gohugoio/hugo/issues/7178

**Comment by tekezo** [comment]
These PR were fixed this issue on my site.
https://github.com/gohugoio/hugo/pull/7204
https://github.com/gohugoio/hugo/pull/7206

**Comment by tshort** [comment]
Hugo 0.69.2 fixed the side nav problems for my site.

**Comment by frodriguezsmartclip** [comment]
Yap, that's right.

Here is the release 0.69.2 update ([link](https://github.com/gohugoio/hugo/releases/tag/v0.69.2))

**Comment by brettkoonce** [comment]
Can confirm fixed in 0.69.2, thanks again @tekezo!
