### ISSUE TITLE
Can I change top level directory?

### ISSUE THREAD

**Issue by pol4bear** [google/docsy#252]
A document I'm trying to make has multiple versions. I want to make directory something like /docs/1.0, /docs/1.1, /docs/lastest etc.. I changed directory structure what i'd want to do. If someone tries to access /docs I made it to redirect /docs/lastest.
 If someone view /docs/lastest I want /docs/lastest to be top level document but every version under /docs folder shows on sidebar menu. Is there any way to change top level directory of document?

**Comment by wrex** [comment]
I *think* you can get close to what you want with [Docsy versioning](https://www.docsy.dev/docs/adding-content/versioning/). 

Your content directories would be `content/docs/` (i.e. "latest"), `content/docs-1.0/`, `content/docs-1.1`, etc. You'll need to add `type: docs` to the front-matter of all your `doc-#` pages (I'd add it to the [archetypes](https://gohugo.io/content-management/archetypes/#readout), too, so new pages you create with `hugo new` will also get it)

Your `config.toml` would look need to contain something like:

```
[[params.versions]]
  version = "latest"
  url = "https://example.com/docs/"

[[params.versions]]
  version = "v1.0"
  url = "https://example.com/docs-1.0/"

[[params.versions]]
  version = "v1.1"
  url = "https://example.com/docs-1.1/"
```

**Comment by pol4bear** [comment]
I added type: docs to all of my docs-# pages and it worked fine. But the left side menu of /docs-#/ get collapsed and won't show subfolder document list. If I access /docs-#/getstarted/ left side menu works fine again. It worked fine when it was located in /docs/ but after I moved to /docs-#/ left side menu is not working well. How can I fix this?

**Comment by LisaFC** [comment]
That's strange! So the menu is only behaving strangely in the top-level directory/index page of each of your new custom sections?

**Comment by pol4bear** [comment]
Yeap. The side menu is being collapsed only on top-level directory of my custom sections. I didn't check other pages in top-level directory does but on subdirectory pages it works perfectly.

**Comment by pol4bear** [comment]
@LisaFC After I add custom section side bar menu and version warning which says "version is no longer maintained" is not working. The version warning's position is fine but there's no message showing inside. The website is running at https://elk.pol4.dev/. The source is loacted at https://github.com/boijodoc/main-source/

**Comment by LisaFC** [comment]
Closing as obsolete, please reopen if this problem reappears!
