### ISSUE TITLE
disqus comments not appearing, neither in local nor in prod

### ISSUE THREAD

**Issue by mateja82** [google/docsy#258]
Not sure if this is a bug, or there's something weird in my implementation, but it's not working in localhost (not sure if it should), nor on my site.

Here's what I did, as per official instructions on Hugo, and following  #35 [35](https://github.com/google/docsy/pull/35)

## Step 1.
added to config.toml
[params]
...
Enable Disqus Comments
disqusShortName = "www-matscloud-com"

## Step 2.
Copied "disqus-comment.html" to the local layouts/partials 

Is there something else that I should be changing, and isn't docummented? On "content" it seems that everything is in place. @thinkerou I've seen that this was your pull, did you get any feedbacks from anyone else? Thanks

**Comment by mateja82** [comment]
Solved it, changed the parameter name to Site.Params.DisqusShortname (issue due to Hugo base release change).

Pull request done.

**Comment by mateja82** [comment]
Solved it, changed the parameter name to Site.Params.DisqusShortname (issue due to Hugo base release change).

Pull request done.

**Comment by LisaFC** [comment]
Merged now! Thanks for fixing.
