### ISSUE TITLE
Navigation link to the "next page"

### ISSUE THREAD

**Issue by pwinston** [google/docsy#266]
I have a site with just N pages all at the same depth level. It would be nice especially on mobile to have "next page" link at the buttom. Does docsy have any option for this? Or has anyone done something custom?

I'll probably just do it "by hand" for now but just wondering.

**Comment by frodriguezsmartclip** [comment]
This is an open issue here: [https://github.com/google/docsy/issues/208](https://github.com/google/docsy/issues/208)

You can write there and try again! ;)

**Comment by pwinston** [comment]
Yes #208 is what I'm talking about. Closing this.
