### ISSUE TITLE
[Feature Request] Add support for download content in pdf format

### ISSUE THREAD

**Issue by toni-moreno** [google/docsy#267]
Hello to everybody in this great project.

I'm playing itn docsy and I like a lot. But sometimes our customers ask for a printable pdf document.  Is there any way to export all ( or perhaps some parts) as a pdf?

Thank you very much.

**Comment by LisaFC** [comment]
Hi!  It's not something that Docsy or Hugo currently supports, but there's an open issue in Hugo to add export to PDF, currently tagged for the 0.70 release - once that's implemented you should be able to do what you want:

https://github.com/gohugoio/hugo/issues/6332

**Comment by gwatts** [comment]
@toni-moreno I opened a PR #356 which adds a "print entire section" feature .. idea being that your browser then gathers all the pages (and sub-pages) for a section of the site, and you can then have the browser "print to pdf" from there..

Having Hugo generate a PDF directly during its build flow is a more complicated affair (as the hugo issue @LisaFC linked indicates, but hopefully my update will get close enough for now; will be interested to know what you think.

Take a look at this page to see an example ("Print entire section" link is on the right): https://deploy-preview-356--docsydocs.netlify.app/docs/adding-content/

**Comment by LisaFC** [comment]
Closing as fixed by "print entire section"
