### ISSUE TITLE
Add option to remove right nav

### ISSUE THREAD

**Issue by pwinston** [google/docsy#273]
How can I make the sidebar wider for the documentation pages? The example site's sidebar is wider than mine, but I can't figure out how that was done. Thanks.

**Comment by LisaFC** [comment]
Huh, that's odd, I didn't do anything to set the width. It's a Bootstrap grid column with some extra CSS styling for the nav section. You can see how we divided up the widths in the base file for docs:

https://github.com/google/docsy/blob/master/layouts/docs/baseof.html

The CSS is here so you can override just this file in your own project and tweak the padding and margins so it's how you want it, or you could create your own baseof file.

https://github.com/google/docsy/blob/master/assets/scss/_sidebar-tree.scss

Can I see your site to see if there's anything else odd going on?

**Comment by pwinston** [comment]
The site is https://tobeva.com/wiki

But this is totally bizarre. Sometimes the sidebar is narrow and sometimes it's wide. Even in Chrome sometimes it's narrow or wide. When wide it's identical to the Docsy example site. When narrow it's a fair amount more narrow.

See screenshot below. Top to bottom that's Chrome, also Chrome, and Firefox. I just tried 2 other mac's just now, one showed it narrow and one wide. I can't explain how that's even possible, for it to vary. This seems totally crazy.

<img width="914" alt="width" src="https://user-images.githubusercontent.com/4163446/81691739-4926b700-942b-11ea-89b4-32f42a575519.png">

**Comment by LisaFC** [comment]
That is REALLY strange! The grid gives different % ratios for medium and extra large screens, but these are all clearly on the same screen. For me I'm getting your "narrow" version on my Macbook Pro (13 inch) and the "wide" version on my monitor, which is what I'd expect.

**Comment by LisaFC** [comment]
These are the Bootstrap breakpoints for different screen sizes:

```
// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

**Comment by pwinston** [comment]
My main machine is a macbook with 3 external monitors, all portrait. So who knows what weird bugs Chrome and/or Firefox have with that setup.

However I see a problem on a lone macbook with the Docsys

**Comment by pwinston** [comment]
Closed by mistake.

I think I can explain it. Not shown in my screenshots is the right side of the window. When my column is narrow it's because the window is wide enough for the right sidebar! Sorry for the confusion not realizing that.

However that implies to me the "responsive" logic here is not great. For example here is Docsy example site with 2 columns, the left sidebar looks good:

<img width="1190" alt="wide" src="https://user-images.githubusercontent.com/4163446/81732707-de8f6e80-945e-11ea-8507-adad8a3895f4.png">

Make the window slightly *bigger* and the right sidebar appears and now the left sidebar is squished. I'd argue this is a poor choice given how much worse the left looks, and how important the left side is:

<img width="1203" alt="narrow" src="https://user-images.githubusercontent.com/4163446/81732921-3201bc80-945f-11ea-9bae-3360ffd8968b.png">

For my purposes disabling the right sidebar would work, if you know how to that?

For all users I'd argue you don't want to squish the left sidebar? But it's subtle issue maybe most people don't care.

**Comment by LisaFC** [comment]
Yeah, it would be nice to spend some time (or have people volunteer to spend it!)  generally tweaking our responsive layout, we already have a few open issues about how we could have better UX on mobile. It *is* hard and I am not always very good at it. :)

I'll play around a bit and see if there's an easy way for you to take out the right sidebar for all screen sizes (it doesn't display in mobile)

**Comment by pwinston** [comment]
Cool thanks. Having the right sidebar be optional seems like a reasonable
config option even apart from this layout use.

Thinking about it, I think the reason shrinking the left sidebar is bad is
because it’s really a menu/index. It’s not free text. And it’s narrow to
start with. Shrinking it forces many headings to two lines, which means as
a “menu” it’s now displaying half the number links in the same vertical
space. So it’s a functional issue.

Whereas the main column is free text. And wider so the percentage of
shrinking would be less. So I think it can better absorb the change in
width.

But that’s philosophical. Maybe there are in fact reasons to shrink the
left sidebar.

As for why I hit this I suspect it’s because I tend to make my browser
windows portrait shaped, so they look like a piece of paper. Not wide so
they use the whole width of the screen.

I see people using both approaches. I don’t think either style is going
away.

**Comment by pwinston** [comment]
Is there maybe a hack-way I can keep the right sidebar from popping up? Would be nice until there is a real config option. I'm not that good with CSS.

**Comment by LisaFC** [comment]
Should be, yeah, I'll take a look. Will probably just be a matter of overriding the relevant layout.

**Comment by LisaFC** [comment]
OK, so a super simple fix is to add your own layouts/docs/baseof.html to your project with this content (it's the existing one minus the toc div) then you just won't get a right sidebar, ever. 

```
<!doctype html>
<html lang="{{ .Site.Language.Lang }}" class="no-js">
  <head>
    {{ partial "head.html" . }}
  </head>
  <body class="td-{{ .Kind }}">
    <header>
      {{ partial "navbar.html" . }}
    </header>
    <div class="container-fluid td-outer">
      <div class="td-main">
        <div class="row flex-xl-nowrap">
          <div class="col-12 col-md-3 col-xl-2 td-sidebar d-print-none">
            {{ partial "sidebar.html" . }}
          </div>
          <!--<div class="d-none d-xl-block col-xl-2 td-toc d-print-none">
            {{ partial "toc.html" . }}
          </div>-->
          <main class="col-12 col-md-9 col-xl-8 pl-md-5" role="main">
            {{ partial "version-banner.html" . }}
            {{ if not .Site.Params.ui.breadcrumb_disable }}{{ partial "breadcrumb.html" . }}{{ end }}
            {{ block "main" . }}{{ end }}
          </main>
        </div>
      </div>
      {{ partial "footer.html" . }}
    </div>
    {{ partial "scripts.html" . }}
  </body>
</html>
```

The only disadvantage is that you also don't get the Github links as they're in the sidebar.

**Comment by pwinston** [comment]
Thanks that does remove the right sidebar. However the left sidebar still shrinks, pops to a smaller size, when you make the window wider. Same as shown in the images above. The topics/headings that fit on one line suddenly take up 2 lines since there is less horizontal room. Which is silly because the window is **wider** not narrower. There's more room not less.

It's not a huge deal. But ideally there'd be a way to keep the left column from shrinking when the browser window gets wider.

**Comment by LisaFC** [comment]
Ah gotcha, yes, the left column is still resizing according to the "old" division of space. I'll try to tweak it.

**Comment by LisaFC** [comment]
Ok, try this:


```
<!doctype html>
<html lang="{{ .Site.Language.Lang }}" class="no-js">
  <head>
    {{ partial "head.html" . }}
  </head>
  <body class="td-{{ .Kind }}">
    <header>
      {{ partial "navbar.html" . }}
    </header>
    <div class="container-fluid td-outer">
      <div class="td-main">
        <div class="row flex-xl-nowrap">
          <div class="col-12 col-md-auto col-xl-auto td-sidebar d-print-none">
            {{ partial "sidebar.html" . }}
          </div>
          <main class="col-12 col-md-10 col-xl-10 pl-md-5" role="main">
            {{ partial "version-banner.html" . }}
            {{ if not .Site.Params.ui.breadcrumb_disable }}{{ partial "breadcrumb.html" . }}{{ end }}
            {{ block "main" . }}{{ end }}
          </main>
        </div>
      </div>
      {{ partial "footer.html" . }}
    </div>
    {{ partial "scripts.html" . }}
  </body>
</html>

**Comment by pwinston** [comment]
That just displays nothing! Well it's shows the sidebar but the entire main section is blank:

<img width="1132" alt="tobeva-blank" src="https://user-images.githubusercontent.com/4163446/88311274-ab7b1e00-ccde-11ea-95ab-70f1462826b1.png">

Compared to the real site: https://tobeva.com/about/

This is the diff the real one on the left and yours on the right:

<img width="1237" alt="docsy-diff" src="https://user-images.githubusercontent.com/4163446/88311436-dfeeda00-ccde-11ea-9d84-2783ca666b81.png">

Man this CSS stuff is cryptic: "col-12 col-md-10 col-xl-10 pl-md-5".

**Comment by LisaFC** [comment]
Ah I see what's happened, I've made the main text section too wide so it's popped down below the navbar at a certain width (if you scroll down you'll find it) - I didn't see it on my version because I didn't shrink it enough. I'll tweak it again to make sure it always fits.

This is the cryptic horror the CSS is based on :) : https://getbootstrap.com/docs/4.1/layout/grid/

**Comment by pwinston** [comment]
Yeah "col-12 col-md-10 col-xl-10 pl-md-5" is literally what code looked like in the 1960's before they invented higher level languages. I'm imagining people that felt programming was too hard so they are "just" doing CSS instead...

**Comment by LisaFC** [comment]
One more go (this worked at all widths on my test site):

```
<!doctype html>
<html lang="{{ .Site.Language.Lang }}" class="no-js">
  <head>
    {{ partial "head.html" . }}
  </head>
  <body class="td-{{ .Kind }}">
    <header>
      {{ partial "navbar.html" . }}
    </header>
    <div class="container-fluid td-outer">
      <div class="td-main">
        <div class="row flex-xl-nowrap">
          <div class="col-12 col-md-auto col-xl-auto td-sidebar d-print-none">
            {{ partial "sidebar.html" . }}
          </div>
          <main class="col-12 col-md-7 col-xl-8 pl-md-5" role="main">
            {{ partial "version-banner.html" . }}
            {{ if not .Site.Params.ui.breadcrumb_disable }}{{ partial "breadcrumb.html" . }}{{ end }}
            {{ block "main" . }}{{ end }}
          </main>
        </div>
      </div>
      {{ partial "footer.html" . }}
    </div>
    {{ partial "scripts.html" . }}
  </body>
</html>
```

That should give you a left nav that's just based on text width and a main section that takes up a reasonable percentage of the page without being too wide. I'll see if I can come up with a nicer version to properly parameterize switching off the right nav, though I don't know are all users not going to want a "flex-width" left nav.

**Comment by LisaFC** [comment]
And yes, the Bootstrap stuff is kind of impenetrable until you realize that you're just setting the widths/relative widths of columns in a 12 column grid with variants depending on the size of the screen.

**Comment by pwinston** [comment]
Yes that works! Thanks! I deployed it:

https://tobeva.com/resources/
https://tobeva.com/resources/technical/operating_sytems/

**Comment by BethProedrou** [comment]
I am having the same problem, but the current solution no longer seems to work. I would appreciate some help if possible.

**Comment by fekete-robert** [comment]
Which docsy version are you using?

**Comment by BethProedrou** [comment]
The solution worked in the end. I just made a mistake while implementing it. Thank you for the swift answer and apologies for the disturbance. I will delete my comment and you can close the issue again.

**Comment by fekete-robert** [comment]
Glad you got it sorted out :)
