### ISSUE TITLE
Examples: consider adding bazel.build ?

### ISSUE THREAD

**Issue by mhansen** [google/docsy#282]
http://bazel.build/ is based off docsy, but the themes ported over to Jekyll rather than Hugo.

https://groups.google.com/forum/#!msg/bazel-dev/hjRP7JTtZ_U/9SZYZUSBDAAJ discusses a docsy-based prototype and incororates their ideas into the site.

I thought I'd open this issue to ask if it's worth adding. Perhaps it isn't, if it's "different enough" to be using Jekyll. But you can still tell that it looks pretty docsy! :-)

**Comment by emckean** [comment]
hi, closing this as it looks like Bazel.build is Devsite now. :)
