### ISSUE TITLE
Can't get docsy to work with hugo modules.

### ISSUE THREAD

**Issue by wlai-axway** [google/docsy#283]
Hi, I am trying to use hugo modules to manage dependencies. When using hugo modules then everything has to be configured this way and the theme = ["docsy"] configuration needs to be replaced by:

> [module]
>   [[module.imports]]
>     path = "github.com/google/docsy"
>#theme = ["docsy"]

That doesn't work because docsy uses submodules and hugo modules doesn't seem to take care of that so hugo build results in failure due to missing bootstrap or Font-Awesome files.

Alternatively the docsy theme can still be kept as a git submodule and you tell hugo to load it as a module using this configuration:
> [module]
>   [[module.imports]]
>     path = "docsy"
>#theme = ["docsy"]

That configuration seems to work fine and hugo builds with no errors but the generated pages doesn't seem right. Here's a test using https://github.com/google/docsy-example :
![image](https://user-images.githubusercontent.com/20820993/84372972-d4829c00-abd3-11ea-9772-72ed7090778d.png)

**Comment by LisaFC** [comment]
Hmm, I'll have a look. We built the theme before Hugo modules existed so it may need some tweaking to work with them.

**Comment by d-henn** [comment]
Is this still something being looked at? Would love to be able to convert to hugo modules!

**Comment by deining** [comment]
Support for using the theme as hugo module was introduced with #871, so this ticket can be closed.
