### ISSUE TITLE
Add unit/integration tests 

### ISSUE THREAD

**Issue by medyagh** [google/docsy#286]
I am curious, if I wanna contribute to docsy, are there unit or integration tests that we could run for docsy ?

**Comment by chalin** [comment]
Hi @medyagh - we now have smoke and Docsy-package tests running under GitHub actions as part of CI. For details, see the workflow files under https://github.com/google/docsy/tree/main/.github/workflows.

I'm considering this issue closed by:

- #1776 
- #1777
