### ISSUE TITLE
docsy.dev: feedback link "Please tell us how we can improve." is broken

### ISSUE THREAD

**Issue by mhansen** [google/docsy#287]
To reproduce:

* visit https://www.docsy.dev/docs/getting-started/
* under Feedback, was this page useful, click 'Yes'
* A message shows, "Glad to hear it! Please tell us how we can improve."
* click "how we can improve"

Expected: takes me to https://github.com/google/docsy/issues/new
Actual: takes me to https://github.com/USERNAME/REPOSITORY/issues/new

![image](https://user-images.githubusercontent.com/105529/84586390-70bed400-ae5c-11ea-8b62-10ff4d52cfd4.png)

**Comment by LisaFC** [comment]
Thanks for spotting that! (we apparently added the feature but didn't configure it for our own site....)

**Comment by LisaFC** [comment]
Fixed in #293

**Comment by mhansen** [comment]
Thank you! btw docsy looks really good, I think it's great to take
documentation best practices and codify them :-)

**Comment by LisaFC** [comment]
Thanks! Glad you like it!
