### ISSUE TITLE
No ID generated for H1 headings

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#288]
Hi,

Is there a reason that no IDs are generated for H1 headings? From the docsy docs:

```
<div class="td-content">
	<h1>Welcome to Docsy</h1>
```

for H2 the ID is generated:

```
<h2 id="what-is-docsy">What is Docsy?<a aria-hidden="true" 
```

Thanks

**Comment by LisaFC** [comment]
I *think* (from my dim memory of when we put this together) it's because (in most cases?) there's only one h1 per page and it's usually the page title, so just linking to the page works.  Is there a use case for links on h1s?

**Comment by arnonzooz** [comment]
Well, since HUGO ins't a single-page app like a React app, the state of the left TOC is not kept when you click a link (the TOC scrolls up to the top). I thought to work around this by having the left TOC links link directly to an anchor, which is why I wanted to use the heading ID. Doing so works, but I might choose not do so anyway cause it causes quite ugly urls. So for now I maintain the state of the left TOC with some custom javascript that keeps track of the scroll position. It works, though not ideal.
