### ISSUE TITLE
Make the search box in the left-hand nav optional

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#29]
Currently, if you enable the search in Docsy, you get two search boxes: One at the right of the top menu bar, the other at the top of the left-hand nav.

For my site (Kubeflow) I want just the top right search box, not the one in the left nav. To do that, I need to create a custom `sidebar-tree.html` to override the theme's sidebar-tree. (PR ttps://github.com/kubeflow/website/pull/471.)

Instead, it'd be nice if the double location of the search box was optional. (I guess there may be some sites that'd like the search only in the left nav and not at top right.)

**Comment by LisaFC** [comment]
Fixed in #37
