### ISSUE TITLE
Ability to change syntax highlighting

### ISSUE THREAD

**Issue by ghost** [google/docsy#291]
Hello,

I am new to docsy and hugo, I see [here](https://gohugo.io/content-management/syntax-highlighting/) that hugo allows changing syntax highliting using [chroma styles](https://xyproto.github.io/splash/docs/longer/index.html).

Is it possible to use these along side docsy?

**Comment by frodriguezsmartclip** [comment]
Yes, It's possible. 

But, I changed that syntax highlighting for this better with custom plugins: **Prism.JS**

You can read more about this [here](https://github.com/google/docsy-example/issues/37#issuecomment-586157096):

Regards 😉

**Comment by gittur** [comment]
hello @frodriguezsmartclip , thankyou for the answer.

Can you guide where to put the the `prism.js` and `prism.css` files?

**Comment by frodriguezsmartclip** [comment]
> hello @frodriguezsmartclip , thankyou for the answer.
> 
> Can you guide where to put the the `prism.js` and `prism.css` files?

Ok, it's easy. 📃 

1) You need to custom and download Prism.JS from [here.](https://prismjs.com/download.html)

BTW, in their website, there is a [nice-easy "how-to" about basic usage.](https://prismjs.com/#basic-usage)

2) Put your link **prism.css** inside the path:

`layouts\partials\head-css.html`
`static\css\prism.min.css`

3) Put your **prism.js** inside the path:

`layouts\partials\scripts.html`
`static\js\prism.min.js`

And that's all!! 😉  Hope it helps!!

**Comment by gittur** [comment]
```
grep -r 'prism*' layouts/partials  

layouts/partials/scripts.html:<script src="../../static/js/prism.js"></script>
layouts/partials/head-css.html:<link href="../../static/css/prism.css" rel="stylesheet" />
```
edited:
https://github.com/google/docsy/blob/master/layouts/partials/head-css.html
https://github.com/google/docsy/blob/master/layouts/partials/scripts.html

and added the lines shown above outputted by the `grep` command at the top.

then put the prism files in their respective folders.
```
ls static/css/prism.css 
static/css/prism.css

ls static/js/prism.js 
static/js/prism.js
```
When I serve locally with `hugo serve`, doesn't work. Also removed the `goldmark.highlight` from the `config.toml`.

Can't seem to get it to work for me.

**Comment by gittur** [comment]
@frodriguezsmartclip Do you see any thing that i might have missed?

**Comment by frodriguezsmartclip** [comment]
> ```
> grep -r 'prism*' layouts/partials  
> 
> layouts/partials/scripts.html:<script src="../../static/js/prism.js"></script>
> layouts/partials/head-css.html:<link href="../../static/css/prism.css" rel="stylesheet" />
> ```
> 

That URL reference for CSS and JS is wrong. Need to be:

```
<link href="/css/prism.min.css" ...>
<script src="/js/prism.min.js" defer></script>
```

NOT static.... Hugo know when you put statics files there, that's their path.

Regards!!

**Comment by gittur** [comment]
aaaah nice @frodriguezsmartclip , work now! but still we got [this](https://github.com/google/docsy/issues/214) issue which causes the background color to not change according to the highlight.

**Comment by LisaFC** [comment]
Prism support should be fixed by #325

**Comment by trombonehero** [comment]
You may also need #373 if using a non-empty `BaseURL`...

**Comment by LisaFC** [comment]
Closed as Prism issues were fixed.
