### ISSUE TITLE
Feature request - Copy to clipboard button for code samples?

### ISSUE THREAD

**Issue by alexearnshaw** [google/docsy#292]
Hi Docsy maintainers!

We've received a request from some of the users of our Docsy site https://axway-open-docs.netlify.app/ to have "Copy" buttons on our code samples.

I see that Hugo doesn't support this out of the box, but it seems possible with the addition of some Javascript when I do a google search. For example, https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

Is this something you would consider adding to the Docsy theme? I'd be happy to help with a PR if i can but I am no JS developer :)

**Comment by LisaFC** [comment]
That's a nice idea! Let me have a look at other sites that use it (my JS skills are a bit "mash at the keyboard and hope it works...)

**Comment by coliff** [comment]
I think https://clipboardjs.com/ would be a good choice for this.

**Comment by gittur** [comment]
I think you can do this by integrating prism.js with hugo. Prism.js has multiple plugins that include copy code button.

**Comment by frodriguezsmartclip** [comment]
> I think you can do this by integrating prism.js with hugo. Prism.js has multiple plugins that include copy code button.

Exactly, I used Prim.js in the past, and works like a charm 👌  ([here my comment about that](https://github.com/google/docsy-example/issues/37#issuecomment-586157096))

Regards!!

**Comment by LisaFC** [comment]
Prism sounds like a good option! Let me have a look and see how easy it is to integrate.

**Comment by frodriguezsmartclip** [comment]
> Prism sounds like a good option! Let me have a look and see how easy it is to integrate.

It's too easy! If you need help, let me know 😉

**Comment by LisaFC** [comment]
Hey @alexearnshaw @frodriguezsmartclip do you feel like working together to add this? I'm happy to review. :)

**Comment by alexearnshaw** [comment]
@LisaFC I've just integrated PrismJS on another (non-Hugo) project, so I think I can have a go at this in the next few weeks. Please assign me to this issue.

**Comment by LisaFC** [comment]
Thanks Alex!
