### ISSUE TITLE
Getting Started: Get local copies of the project submodules so you can build and run your site locally

### ISSUE THREAD

**Issue by Olex2** [google/docsy#298]
A few weeks ago, when I first installed a docsy site, I had no problems with Step 3 of 'Using the command line:

`git submodule update --init --recursive`

This command still works on that site.

However, on a brand new site, following the two steps preceding this one, this git submodule command fails (on two machines) with:

`
Cloning into 'D:/Hugo/Sites/name/themes/docsy/assets/vendor/bootstrap'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
`

On the other hand, there is no problem with:

`Cloning into 'D:/Hugo/Sites/name/themes/docsy/assets/vendor/Font-Awesome'...`

What am I missing here?

Thank you!

**Comment by 8bitmp3** [comment]
@Olex2 I had a temporary issue with this step yesterday. Try again today. I suspect the issue was indeed because `the remote end hung up` and it couldn't transfer some submodules to you. 

Just in case, here's what I did to start building a new site locally:

- Downloaded the extended version of Hugo
- Installed PostCSS with `sudo npm install -D --save autoprefixer` and `sudo npm install -D --save postcss-cli`.
- Used `git clone`/`git submodule add` to add the Docsy theme to the `/themes` folder
- Downloaded local copies of the theme’s own submodules with `git submodule update --init --recursive`
- Added the theme to `config.toml` with `echo 'theme = "docsy"' >> config.toml`
- Ran the server locally: `hugo server -D`

**Comment by LisaFC** [comment]
Is this working as expected now?

**Comment by Olex2** [comment]
Hello,

Thanks for asking, but no, it's still not working. All other aspects work
fine (and I can copy the missing folder over from a working docsy/hugo) --
but I guess that's not the idea ;)

`PS D:\Hugo\Sites\fred2> git submodule update --init --recursive

Cloning into 'D:/Hugo/Sites/fred2/themes/docsy/assets/vendor/bootstrap'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data
remaining
fatal: clone of 'https://github.com/twbs/bootstrap.git' into submodule path
'D:/Hugo/Sites/fred2/themes/docsy/assets/vendor/bootstrap' failed
Failed to clone 'assets/vendor/bootstrap'. Retry scheduled
Cloning into 'D:/Hugo/Sites/fred2/themes/docsy/assets/vendor/bootstrap'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data
remaining
fatal: clone of 'https://github.com/twbs/bootstrap.git' into submodule path
'D:/Hugo/Sites/fred2/themes/docsy/assets/vendor/bootstrap' failed
Failed to clone 'assets/vendor/bootstrap' a second time, aborting
Failed to recurse into submodule path 'themes/docsy'`

**Comment by LisaFC** [comment]
Strange! Ok let me see if I can get it to work.

**Comment by gittur** [comment]
Are you using a VPN of any sort?

**Comment by Olex2** [comment]
No -- I need to switch my usual VPN off, otherwise I can't even get to git
;)

**Comment by gittur** [comment]
Do normal git clones work?

**Comment by Olex2** [comment]
Windows 10, Windows PowerShell,  autoprefixer and postcss-cli  installed &
working properly. No VPN, on fast & stable network.

1) git clone https://github.com/google/docsy-example.git fred3 --> no
problem :)
2) cd fred3
3) git submodule update --init --recursive

This leads consistently to the stack trace as shown above

The same result from windows cmd, or git bash -- on two different machines.

So, there's nothing 'home-made' here -- I can't see why this would fail :(

Thanks for your support!!!!

Horst

**Comment by LisaFC** [comment]
That's very odd, I just tried it:

```
lcarey-macbookpro:~ lcarey$ git clone https://github.com/google/docsy-example.git puntle
Cloning into 'puntle'...
remote: Enumerating objects: 1068, done.
remote: Total 1068 (delta 0), reused 0 (delta 0), pack-reused 1068
Receiving objects: 100% (1068/1068), 2.45 MiB | 3.77 MiB/s, done.
Resolving deltas: 100% (545/545), done.
lcarey-macbookpro:~ lcarey$ cd puntle
lcarey-macbookpro:puntle lcarey$ git submodule update --init --recursive
Submodule 'themes/docsy' (https://github.com/google/docsy) registered for path 'themes/docsy'
Cloning into '/Users/lcarey/puntle/themes/docsy'...
Submodule path 'themes/docsy': checked out 'dd303fd19cc13ffc01bcbe86ff54f21e423d04de'
Submodule 'assets/vendor/Font-Awesome' (https://github.com/FortAwesome/Font-Awesome.git) registered for path 'themes/docsy/assets/vendor/Font-Awesome'
Submodule 'assets/vendor/bootstrap' (https://github.com/twbs/bootstrap.git) registered for path 'themes/docsy/assets/vendor/bootstrap'
Cloning into '/Users/lcarey/puntle/themes/docsy/assets/vendor/Font-Awesome'...
Cloning into '/Users/lcarey/puntle/themes/docsy/assets/vendor/bootstrap'...
Submodule path 'themes/docsy/assets/vendor/Font-Awesome': checked out '538a5bc4cf7989821d052e3ff919e2bead07021c'
Submodule path 'themes/docsy/assets/vendor/bootstrap': checked out '3b558734382ce58b51e5fc676453bfd53bba9201'
lcarey-macbookpro:puntle lcarey$ 
```

Can you git clone the bootstrap repo directly?

**Comment by Olex2** [comment]
No. It got about 85% of it (showing the process), and then:

PS D:\Hugo\Sites> git clone https://github.com/twbs/bootstrap.git
bootstrap_fred
Cloning into 'bootstrap_fred'...
remote: Enumerating objects: 154131, done.
error: RPC failed; curl 18 transfer closed with outstanding read data
remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Same thing!

This is so weird!

**Comment by gittur** [comment]
This most probably a network issue at your end, probably related to MTU as far as I can tell or some network firewall. Have you tries it from your home network?

**Comment by Olex2** [comment]
I am working from home (still not allowed anywhere near work!) I thank you
for your help and concern! I will ask a colleague to try from her network.

I've not experienced any (other) network issues at all on what appears to
be a super fast and reliable internet connection.

Horst

PS: I am enjoying working with hugo and docsy immensely. It's fantastic!

**Comment by LisaFC** [comment]
Did this ever resolve? Glad you're enjoying the theme!

**Comment by Olex2** [comment]
Hello,

I still don't know what causes the problem, but I *do* know that it has
nothing to do with Docsy at all -- and I apologize for having asked for
help here.

I have since found that *other* git repros at github show exactly the same
behaviour - but not all. It's the same on two computers -- and the only
common factor is the internet connection (stable & 80Mbs).

The problem occurs only when using https, not with ssh.

The pragmatic solution was to put everything into a dropbox account so that
collaborators can work on our site together.

And yes: Docsy is *exactly* what we've been looking for!

Thank you!

**Comment by LisaFC** [comment]
No problem, and sorry you had the issue in the first place (and good you could find a workaround!).

**Comment by Olex2** [comment]
Hello Lisa -- I am now ready to deploy our site based on docsy -- and I
would like to use GitLab for this. I tried all I can, and am now running
out of steam. The postcss seems to be a very sticky point!

Building sites … ERROR 2020/10/24 19:54:04 error: failed to transform
resource: POSTCSS: failed to transform "scss/main.css" (text/css): PostCSS
not found; install with "npm install postcss-cli". See
https://gohugo.io/hugo-pipes/postcss/

I've got this, and can not -- with all the help from Google -- work out
what I need to do differently:

image: registry.gitlab.com/yaegashi/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

Please excuse me if this way of contacting you is a bit cheeky...

Horst
