### ISSUE TITLE
the Github edit link should allow for the site to live in a folder

### ISSUE THREAD

**Issue by balopat** [google/docsy#3]
Our site lives inside our code repo itself under the docs/ folder. This breaks the Github edit link: see https://github.com/GoogleContainerTools/skaffold/pull/1417/files - I had to create the partial for overriding - it would be nice if I could just change `siteFolder` param, or similar.

**Comment by sarahmaddox** [comment]
I have a similar issue, in that my content is not internationalized. Therefore the content lives in the `/content/` folder, not `/content/en/`.

This is the line that needs changing:
https://github.com/google/docsy/blob/3ca22ac9a0b7e4b4faf54cd4f4ab272695f1516a/layouts/partials/page-meta-links.html#L5

I've similarly created the partial to override the hard-coded path.

Perhaps it could make use of the already-defined `contentDir` variable in config.toml

**Comment by LisaFC** [comment]
Fixed by #94 (plus another follow-on commit)
