### ISSUE TITLE
Allow an additional dropdown in the top menu bar via config

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#30]
For the Kubeflow site I needed to add a dropdown menu offering different versions of the docs: https://www.kubeflow.org

The Agones site needed to add a similar option:
https://agones.dev/site/docs/

To do this, I had to add a custom navbar partial. It'd be nice it we could add a dropdown via config rather than needing to override the Docsy layouts.

**Comment by LisaFC** [comment]
Fixed in #95
