### ISSUE TITLE
Error building the site

### ISSUE THREAD

**Issue by dend** [google/docsy#304]
I am trying to build the Docsy theme on an existing site that I have, and I run into the following issue:

```bash
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): 
SCSS processing failed: file "/Users/den/docs/themes/docsy/assets/scss/_colors.scss", 
line 4, col 18: argument `$color2` of `mix($color1, $color2, $weight: 50%)` must be a color.
```

I am using the following build of Hugo:

```bash
Hugo Static Site Generator v0.68.3-157669A0/extended darwin/amd64 BuildDate: 2020-03-24T12:11:24Z
```

What could be missing? Anything I need to specify in my config to resolve this?

All the submodules seem to be correctly loaded and available in their respective folders.

**Comment by brunoamaral** [comment]
what are the values you have to $color2 ? Could it be that main.scss is loaded before that value is defined?

**Comment by dend** [comment]
I actually haven't modified it at all. The potential root cause of the issue is the fact that I was snapping the theme to the latest Bootstrap, which likely has made some changes in how they handle colors.

**Comment by LisaFC** [comment]
Hmm, let me have a look. If we don't work with the latest Bootstrap we might need to make some updates.

**Comment by LisaFC** [comment]
It seems to be Bootstrap 0.5.0-alpha that's doing it, as the latest not-alpha release (0.4.5) works fine.

**Comment by LisaFC** [comment]
Anything past 0.4.5 seems potentially break-y so I'll have a look at the alpha docs/code for now to see *why* 0.5.0 broke the build but won't make any updates to the main Docsy repo yet. From the Bootstrap blog post:

> Before you jump to updating, please remember v5 is now in alpha—breaking changes will continue to occur until our first beta. We haven’t finished adding or removing everything, so check for open issues and pull requests as you have questions or feedback.

I'll update the theme submodule to point to the 0.4.5 version anyway as that doesn't seem to make anything fall over...

**Comment by LisaFC** [comment]
Updated! Do you want to close this and I'll start a new issue for working with Bootstrap 0.5.0?

**Comment by dend** [comment]
Excellent, thank you @LisaFC!
