### ISSUE TITLE
Typo in offline-search.js

### ISSUE THREAD

**Issue by cdhunt** [google/docsy#305]
It looks like the div class is correctly named `offline-search-result`, but the script is referencing `offlnie-search-max-results`. 

I haven't noticed any unexpected behavior in offline search functionality, though.

https://github.com/google/docsy/blob/02904c33475a4a9e21104bff901f8c6f821fd597/assets/js/offline-search.js#L103

**Comment by LisaFC** [comment]
@tekezo, could you take a look?

**Comment by tekezo** [comment]
Thank you for feedback!
I checked the code, both div class and javascript were misspelled, so there was no problem with the behavior.

I made a PR to fix this typo.
https://github.com/google/docsy/pull/313
