### ISSUE TITLE
Missing copyright info in License

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#31]
Line 189 of the LICENSE file needs to be updated with copyright information.

**Comment by LisaFC** [comment]
Hmm, it appears that a huge number of Apache license users have also made this error in that I'm not sure what to put here but have yet to find one in the Google org where people have filled that info in. I will continue my search....

**Comment by LisaFC** [comment]
Aha, I see what's going on here. I was looking through loads of Apache licenses and couldn't figure out why nobody had filled it in - it's because it's boilerplate instructions for how to apply an Apache license to a file.
