### ISSUE TITLE
page-meta-links.html assumed /content is in root

### ISSUE THREAD

**Issue by markmandel** [google/docsy#32]
Content:
https://github.com/google/docsy/blob/master/layouts/partials/page-meta-links.html

Specifically if you look at:
```gotemplate
{{ $editURL := printf "%s/edit/master/content/%s/%s" $gh_repo ($.Site.Language.Lang) .Path }}
```
You can see that the editURL assums that the $gh_repo is the root -- when it may not be.

Solution - have a subdir toml config that can be set, and default to "" for the root path of the directory.

**Comment by LisaFC** [comment]
So there's a really simple way of doing this that leaves an extra "/" in the URL when there's no github subdir but still goes to the right page. I am currently trying to do something that doesn't have the extra forward slash but conditionals in Go templates are horrible (I may return to the extra / option to preserve my sanity...).

**Comment by LisaFC** [comment]
I have triumphed over mad Go scoping issues (possibly by invoking the powers of the cuddly gopher who sits on my desk) but now need to figure out how to integrate that with the "have you got a language-specific subdir" check introduced in f6336160c3ecc918eab704e84eb557b2d7756bf3
