### ISSUE TITLE
parameter to customize the length of toc

### ISSUE THREAD

**Issue by kbhawkey** [google/docsy#326]
Hi. The theme's toc template (`partials/layout/toc.html`) checks the length of 
the Table of Contents to determine whether to display the list of headings.
In pages that are data intensive (contain a number of tables) but have few headings, it would 
help readers navigate through the page.
I could customize the partial template, but wonder if this is something to consider as a change to the theme.
Possibly add a new site parameter (default to 200) and update the partial to check this parameter.
Sites could override this parameter.

**Comment by LisaFC** [comment]
If you can see a use case for parameterizing it, then by all means go ahead  - if you leave 200 as the default then it won't break existing sites and most users will get reasonable behaviour.

**Comment by kbhawkey** [comment]
For now, I will override the theme's toc partial and get feedback on the additional headings. Thanks!
/close
