### ISSUE TITLE
Serving from GitHub Pages 

### ISSUE THREAD

**Issue by jzinner** [google/docsy#336]
Hello Docsy Community, 

I’m switching from Jekyll to Hugo as my static site generator so that I can use the Docsy Hugo theme.

I have been following the [Hosting Hugo on Github Project Pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-project-pages)

My [config.toml](https://github.com/jzinner/softwarehardening-hugo-docsy/blob/master/config.toml) build parameters are
> theme = [“docsy”]
> themesDir = “themes”
> #publishDir builds hugo to the docs folder (instead of the default public) necessary to use Github Pages to serve the Project
> publishDir = “docs”

After building using `hugo` and uploading pushing the `docs` directory to GitHub, when I look at the resulting Github Page, 
The Docsy theme does not render instead I get stripped down html - see image below.

![Docsy_Github_Page_not_rendering](https://user-images.githubusercontent.com/7864372/92795770-3fc83f80-f376-11ea-96d6-8c55b2761034.png)

Any ideas?
Thank you in advance,

**Comment by LisaFC** [comment]
I haven't served a Hugo site from Github Pages myself, but does it build and serve locally ok?

**Comment by jzinner** [comment]
Thank you for replying @LisaFC.  I asked for help on [Hugo's Discourse Board](https://discourse.gohugo.io/t/docsy-theme-not-rendering-using-github-pages/28109), and someone was able to point me in the right direction. 

I updated hugoDocs with the solution and [created a PR for hugoDocs](https://github.com/gohugoio/hugoDocs/pull/1223)

I am closing this issue in Docsy - it's Hugo related not theme related.  Thank you again.
