### ISSUE TITLE
Toggle sidebar burger button is hidden for screens smaller than 400px on Firefox

### ISSUE THREAD

**Issue by jopasdev** [google/docsy#357]
On Firefox for screens smaller than 400px the burger button is hidden and scrolling to right side is required to see the button.

![Screenshot from 2020-10-13 21-26-07](https://user-images.githubusercontent.com/368590/95929714-1185b780-0d9b-11eb-8e44-e5e9b56dade7.png)

**Comment by LisaFC** [comment]
Fixed in #362
