### ISSUE TITLE
Add a "copy" button to code blocks

### ISSUE THREAD

**Issue by chipzoller** [google/docsy#370]
This (cool, btw) theme is commonly used for documentation of "technical" subject matters which often include code. It would be super helpful if there were just a simple "copy" button somewhere in that code block providing users an easier way to select all and copy what's in that block. We implemented that plus other functions in our [Clarity theme](https://github.com/chipzoller/hugo-clarity), so if no one can pick this up it might be something we could look at doing in the future.

**Comment by LisaFC** [comment]
If you switch to using Prism for your code highlighting, you'll get a copy button!
https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism

(we didn't make Prism the default just because a lot of our users rely on Chroma styles, but it's easy to switch)
