### ISSUE TITLE
 Search bar above the left nav is missing

### ISSUE THREAD

**Issue by brian-armory** [google/docsy#384]
(I filed this issue in the [example repo too](https://github.com/google/docsy-example/issues/88). Not sure which one is the correct venue. Feel free to close this one or the other.)

For https://example.docsy.dev/, the search bar above the left nav is set to show up.

https://github.com/google/docsy-example/blob/3cbe73a93a413872774e8115aa3641f1472bc51a/config.toml#L133

The search bar doesn't appear above the left nav though:
https://s.armory.io/qGulz4dW

We ran into this issue on our docs site (docs.armory.io) and are planning to downgrade the theme version since it worked previously.

**Comment by LisaFC** [comment]
Oh, that's very odd - thanks for letting us know.  Let me check which version/change broke that.

**Comment by LisaFC** [comment]
So it looks like it might have vanished after #356 (which none of us noticed) - @gwatts, can you take a look?

**Comment by gwatts** [comment]
Looks like it goes back a bit further than that -It seems the search is now intentionally hidden on "large displays" as a consequence of #362

**Comment by LisaFC** [comment]
Gotcha. @geriom, can you unhide the extra search bar, as it's already possible to hide it from the config if you don't want it, and we have users who *do* want the search box in the left nav on large screens.

**Comment by LisaFC** [comment]
#390 should restore it, will merge unless anyone has strong objections. :)
