### ISSUE TITLE
Adjust header and footer to open external links in new tab

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#39]
By default, Docsy opens all external links in a new tab, when those links are part of a page. This is due to the following `config.toml` setting:

```
[blackfriday]
hrefTargetBlank = true
```

For consistency, if there are external links in the header and footer (such as the privacy policy), Docsy should by default open those links in a new tab.

The following PR shows how I achieved this in Kubeflow:
https://github.com/kubeflow/website/pull/500/files

**Comment by LisaFC** [comment]
Excellent. I have totally borrowed this.
