### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by jalateras** [google/docsy#393]
This is probably not the forum for these type of questions. Whart do you use to as an authentication layer in from of docsy. We have a bunch of clients from different organizations that would like to access our API but we do not want to make it public.

Any advice?

**Comment by gwatts** [comment]
In terms of forums, there's a Docsy community mailing list you might like to join: https://www.docsy.dev/community/

To answer your question (just as someone who uses Docsy) - I  deploy a company Docsy site to an AWS S3 bucket and then have Cloudfront serve the site.  I then use a Lambda at Edge function (https://github.com/Widen/cloudfront-auth) which authenticates employees using Google Workspace (but also support Okta, AD. etc)

I'm going to be writing up how I do that with automation examples in the near future.

Commercial providers such at Netlify also have solutions that might be worth looking at too if you want to do less of your own plumbing :-)

**Comment by dinotoa** [comment]
> This is probably not the forum for these type of questions. Whart do you use to as an authentication layer in from of docsy. We have a bunch of clients from different organizations that would like to access our API but we do not want to make it public.
> 
> Any advice?

Another option you may want to consider is [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy#oauth2_proxy) that you can use stand-alone or in conjunction with nginx.
if you need https you can use let’s encrypt.

an option we use for some customer is google cloud [identity aware proxy](https://cloud.google.com/iap), which is non trivial to setup, but is a very robust and fast option.

**Comment by emckean** [comment]
Thanks for the options folks, if there are more questions on this it would be good to move to Discussions :)
