### ISSUE TITLE
Print Support won't work if you don't have the repository links enabled

### ISSUE THREAD

**Issue by ronoaldo** [google/docsy#396]
Currently, the link is only rendered if the github_repo property has a value, and therefore, only visible if also the repository links are visible as well.

It would be nice to split those so one can enable the print support without the other links (edit page, new page, new issue, etc.).

**Comment by LisaFC** [comment]
@gwatts, want to take a look at this one?

**Comment by gwatts** [comment]
Ah yep that wasn't intended behaviour; got a bit lost in the if/else maze for that partial - the linked PR above should fix it!
