### ISSUE TITLE
Broken edit links with custom content folder

### ISSUE THREAD

**Issue by alexivkin** [google/docsy#402]
layouts/partials/page-meta-links.html makes a wrong assumption that the source markdown files are in a "content" directory on github. When custom hugo content directory is used the github edit and create links become broken. 
Docsy should rely on the `contentDir` variable, which also has a benefit of not needing the if .Site.Language.Lang logic.

**Comment by gwatts** [comment]
Hrm, yes that's a good point - I'm not sure that that `contentDir` variable is actually accessible to use in a template though: https://discourse.gohugo.io/t/accessing-the-contentdir-location-from-within-a-template/8271

We could add an extra parameter to override the default.. ideally though it would fetch the contentDir of the active site (of which there may be multiple if the site is in multiple languages); probably a feature request on Hugo really unless I'm missing something

**Comment by alexivkin** [comment]
Seems like a bug to me - docsy shows wrong edit links if hugo's supported custom content folder is used. 
I've solved it for myself with a parameter override and a fix in the partial.

**Comment by gwatts** [comment]
I agree it's a bug; i'm saying that i don't think there's a "clean" way to fix it in Docsy, without duplicating the `contentDir` setting as a parameter so it can be accessible to the partial template.. We can do that, it's just not very clean - It would be better if Hugo exposed the `contentDir` setting somehow, I think

I'll think on it a bit more when I have some spare time - If anyone else has the same problem, please add a like to this issue!

**Comment by LisaFC** [comment]
This came up (in a slightly different context) in #138 and I remember wishing at the time that there was a way for Hugo to expose contentDir for use in templates - if anyone has a nice solution I'm also all for it. I think mostly people have fixed it for themselves by overriding the partial, but it would be nice for it to work out of the box for a variety of content directories.

**Comment by chalin** [comment]
With the various fixes applied to repo links, such as #1744, I believe that this has been addressed. Closing for now. If it is still an issue, please let us know!
