### ISSUE TITLE
Look and Feel Dead link on 

### ISSUE THREAD

**Issue by bobhy** [google/docsy#403]
Page https://www.docsy.dev/docs/adding-content/lookandfeel/
has a dead link referring to: https://mermaid-js.github.io/mermaid/getting-started/Setup.html#mermaidapi-configuration-defaults

I think mermaid has changed both doc site and API substantially since this page was written; the urls are way off.

And the instructions for enabling mermaid aren't working for me: I find that a well-formed mermaid figure is rendered like a code block of unknown language.  I've dealt with this in other themes.  I don't know how this worked with BlackFriday, but goldmark doesn't handle mermaid as a language for the code block and so renders it as a plain code block.  Mermaid doesn't see a `<div class="mermaid">`, rather `<div class="mermaid-language">` (if your're lucky).  There is an alternate initialization trick to get mermaid to process this class instead, see: https://discourse.gohugo.io/t/use-mermaid-with-code-fences/17211.  However, that requires a change to the theme.  I'll be working on a PR for this, because I love Mermaid.  But this page will need update in any case.

**Comment by bobhy** [comment]
I retract the claim about mermaid being broken.  I had not actually enabled it in my test!  But the dead link is a confirmed (minor) issue.

**Comment by LisaFC** [comment]
Thanks for spotting that!
