### ISSUE TITLE
Some Bootstrap colors not configurable

### ISSUE THREAD

**Issue by honzik20** [google/docsy#409]
I'm trying to override default theme colors - with partial success.

I can change:

$primary
$primary-light: lighten($primary, 75%)
$secondary
$success
$info
$warning
$danger

But I can't change:

$white
$light
$dark
$blue
$orange

I've tried creating a _content.scss in assets/scss - but they're not picked up (in fact, anything I put in that folder is ignored. Could it be because they're in a Hugo module?)

Any help appreciated.

**Comment by prdsoftware** [comment]
I noticed a similar thing with the examples for the blog pages.  See the "Components" section here:

https://example.docsy.dev/blog/2018/10/06/the-second-blog-post/#components

All of the colours are the same, when they shouldn't be.  Maybe this is part of the same problem?

**Comment by LisaFC** [comment]
> I noticed a similar thing with the examples for the blog pages. See the "Components" section here:
> 
> https://example.docsy.dev/blog/2018/10/06/the-second-blog-post/#components
> 
> All of the colours are the same, when they shouldn't be. Maybe this is part of the same problem?

Hmm, no, I looked at the source and there's no reason why the colours should be different on that page - you have to explicitly specify different colours for alerts and those ones are all the same (no colour specified, so default colour): https://www.docsy.dev/docs/adding-content/shortcodes/#alert

I'll have a look at the Bootstrap overrides now.

**Comment by LisaFC** [comment]
The Bootstrap thing is very weird as you should be able to override anything in this file:
https://github.com/google/docsy/blob/master/assets/scss/_variables.scss

by just putting your own values in your _variables_project.scss. Also we don't use Hugo modules so putting your own entirely overridden SCSS files in assets/scss/... should work fine - it should literally just override the file that's included in main.scss when building the CSS.

Let me do some experimentation.

**Comment by LisaFC** [comment]
So I just overrode $white to red to create this, er, attractive offering:
https://tender-beaver-c94732.netlify.app/docs/

Can you let me know what you tried that didn't work?

**Comment by prdsoftware** [comment]
Oh, sorry about the wrong steer.  I was getting mixed up by looking at this page which is coloured:

https://example.docsy.dev/docs/tasks/task/#components 

And this page, which is not

https://example.docsy.dev/blog/2018/10/06/the-second-blog-post/#components

**Comment by LisaFC** [comment]
@honzik20 can you share your repo with me and/or how you're changing colours, or let me know if my suggestion helped so I can close the issue? Thanks!

**Comment by honzik20** [comment]
@LisaFC That certainly...is something.

It must have been a caching error somewhere. By doing hugo mod clean & tidy, it seems to be working now. You can close this. Much appreciated.
