### ISSUE TITLE
Update styling on the feedback buttons

### ISSUE THREAD

**Issue by prdsoftware** [google/docsy#414]
The default feedback buttons were a little old-school for my liking, so I updated the styling to be a little more consistent with the theme.  I updated the feedback.html page at \themes\docsy\layouts\partials\feedback.html to this....

```
<button class="feedback--answer feedback--answer-yes btn btn-md btn-primary">Yes</button>
<button class="feedback--answer feedback--answer-no btn btn-md btn-primary">No</button>
```

Perhaps this might be useful to someone.

Example here https://docs.helpmasterpro.com

**Comment by LisaFC** [comment]
Oh they're much nicer! Do you want to do a PR with that change and we can merge it in to the theme?

**Comment by prdsoftware** [comment]
I wasn't sure if doing this was going to break anything else, so perhaps someone with a bit more knowledge about the mechanism can test it, and make the change?  AFAIK it's just a cosmetic change, so I think it should be fine.

**Comment by Symbolics** [comment]
I was just looking for the same thing. Is this going to be merged into the master branch?

**Comment by LisaFC** [comment]
Just catching up on this - yes, that's exactly how I'd do it (and I notice Kubernetes did the same). I'll create a PR and get this in.
