### ISSUE TITLE
Does not highlight code

### ISSUE THREAD

**Issue by MarcinKlejna** [google/docsy#416]
Template does not highlight code:
other template:
https://ibb.co/KqKypmd
docsy:
https://ibb.co/bRSK8t6

Markdown code
```
`\([^,]*\), \(.*\)`

<mark>`\(`</mark>`[^,]*`<mark>`\)`</mark>`, \(.*\)` Pierwsza część pomiędzy `\( \)` dopasowuje „Ostatnie”\
`\(`<mark>`[^,]`</mark>`*\), \(.*\)` dopasuj wszystko z wyjątkiem przecinka\
`\([^,]`<mark>`*`</mark>`\), \(.*\)` dowolną ilość razy\
`\([^,]*\)`<mark>`, `</mark>`\(.*\)` dopasowuje dosłownie `, `\
`\([^,]*\), `<mark>`\(`</mark>`.*`<mark>`\)`</mark> Druga część między `\( \)` dopasowuje "Pierwsze"\
`\([^,]*\), \(`<mark>`.`</mark>`*\)` dowolny znak\
`\([^,]*\), \(.`<mark>`*`</mark>`\)` dowolną ilość razy
```

**Comment by LisaFC** [comment]
So Hugo uses Goldmark as its Markdown processor, which by default ignores HTML in Markdown files unless you set the following in your `config.toml`:

```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
(see https://www.docsy.dev/docs/adding-content/content/#page-contents-and-markup)

I did so in a test site and here's your code with highlighting:
https://tender-beaver-c94732.netlify.app/docs/examples/

(if I comment out the `unsafe = true` the highlighting disappears)

**Comment by MarcinKlejna** [comment]
Thank you!
