### ISSUE TITLE
Print page does not work after site has been deployed to GitHub Pages

### ISSUE THREAD

**Issue by mountaindude** [google/docsy#421]
I have a site at https://butler-auth.ptarmiganlabs.com, built using Docsy (latest version from GitHub as of Jan 2021).

The outputs section looks like this:

[outputs]
section = [ "HTML", "RSS", "print" ]

The "Print entire section" links work as expected when previewing the site locally. 

But: After building the site and deploying it to GitHub pages the "Print..." links on each page just return 404s:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/1029262/105146812-ad446380-5b00-11eb-9214-251adb719ff4.png">

Which is strange, as the html page is there when looking in [GitHub](https://github.com/ptarmiganlabs/butler-auth-docs/blob/master/docs/docs/_print/index.html).

As the html file is there it feels like it's GitHub pages that won't serve files located in `_print` folders...?
If that's the case it might be hard to fix from Docsy's side, except maybe by changing the name of the `_print` folders.

**Comment by gwatts** [comment]
I imagine Github pages doesn't like path names starting with an underscore.. A quick search of the their docs didn't reveal which characters are acceptable in path names for me though.

In any case, you can customize what that `_print` name is called for your site without updating the theme; I picked one with a leading underscore to avoid it colliding with real page names. 

 If you'd like to change it to `printview` for example, you can update your site's `config.toml` and add the following:

```toml
[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "printview"
permalinkable = false
```

Hope that helps!

**Comment by mountaindude** [comment]
Yeah that's pretty much my conclusion too. 

That workaround looks 10/10 - will test it!

**Comment by gwatts** [comment]
Great; let me know if that works for you and I'll update the docs if so!

**Comment by gwatts** [comment]
Not an intended side effect; likely related to #381 - If you are using relative links to your images, rather than having Hugo calculate the image's URL for you then that's probably the cause of the issue

**Comment by mountaindude** [comment]
Yup, only using relative links. 
Not a biggie for me in this case.

**Comment by mountaindude** [comment]
Always found Hugo's way of handling images a bit clunky... Relative paths are easy and just works in most cases.
But it's prob just that I've never taken the time to dive into Hugo images properly. Should do that.

**Comment by gwatts** [comment]
@mountaindude finally getting around to this.. i did a deploy of a test site to github pages and it doesn't seem to have an issue with the underscore anymore - Can you confirm that `_print` works for you now too?  Wondering if they just "fixed" it on their end

**Comment by mountaindude** [comment]
Adding a super-late response to @gwatts ...

Nope, this never worked for me until today, when I added this to the site's config file:

```
[outputFormats]
[outputFormats.PRINT]
baseName = "index"
isHTML = true
mediaType = "text/html"
path = "printview"
permalinkable = false
```

I haven't look into it at all, but the fix above seems to do the trick.

Closing the ticket as it's pretty old and there's a workaround.
