### ISSUE TITLE
Tabbed code content

### ISSUE THREAD

**Issue by nryberg** [google/docsy#429]
When writing similar code for multiple languages (think Java, Go, Ruby), it's common to have tabbed content that lets you select which language you prefer.  A good [Docusaurus](https://v2.docusaurus.io/docs/markdown-features#tabs) example shows how this works.

Is this possible in Docsy or through a third party plugin?

**Comment by MarcinKlejna** [comment]
you can use shortcodes e.g.  https://github.com/thegeeklab/hugo-geekdoc/tree/master/layouts/shortcodes
https://geekdocs.de/shortcodes/tabs/

**Comment by nryberg** [comment]
I'm able to bring over the tab.html and tabs.html templates from Geekdocs, but struggling a little with the CSS.  When I look at Geekdocs, I can see the related classes, but would love to get your suggestions on how to sync the two up.  
![Tabs_Have](https://user-images.githubusercontent.com/46165/105880625-2e9c6a00-5fc9-11eb-982e-16532704a694.png)
![Tabs_Want](https://user-images.githubusercontent.com/46165/105880632-30fec400-5fc9-11eb-95b7-bee337c3511c.png)

**Comment by nryberg** [comment]
Update - I'm able to get closer but still can't "hide" the buttons".  Updated _styles_project.css with gdocs styles. 

## CSS
![Tabs_css](https://user-images.githubusercontent.com/46165/105890452-00248c00-5fd5-11eb-8e9c-f3da74de8ea0.png)

## Buttons
![Tabs_Have_2](https://user-images.githubusercontent.com/46165/105890467-03b81300-5fd5-11eb-9219-d543b71eddb5.png)

**Comment by nryberg** [comment]
This has been superseded by the tabpane feature. 
https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes
