### ISSUE TITLE
Cannot remove "About Goldydocs" from footer

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#430]
I cannot seem to remove the "About Goldydocs" from the footer of the site (cloned from the [docsy sample site](https://github.com/google/docsy-example)). I would have thought this to be configurable from the config.toml, or perhaps documented in [look and feel](https://www.docsy.dev/docs/adding-content/lookandfeel/), but I haven't been able to find it anywhere. Searching the source only shows that string in one file: content/en/about/_index.html, and since that is a generated file, assume the value must come from a configuration variable somewhere. Which one is it and how is it set? Assuming it isn't a bug, I suspect this is a common enough task to be specifically documented, perhaps in an FAQ.

**Comment by LisaFC** [comment]
Hi there,

So the link title is set here:
https://github.com/google/docsy/blob/master/layouts/partials/footer.html#L23

- it's basically the title of your About page, so if you haven't changed that from the [example site](https://example.docsy.dev/about/) then that's what you get. If you don't *have* an About page at `/about/` at then it shouldn't appear.

You can remove that link entirely in your project's config.toml by setting [this value](https://github.com/google/docsy-example/blob/master/config.toml#L149) to `true`:

`footer_about_disable = true`
