### ISSUE TITLE
Allow configuring the range of copyright years at the footer

### ISSUE THREAD

**Issue by nghialv** [google/docsy#436]
Hello.

Thank you for a great OSS.
We are using Docsy for all of our OSS products and we really love Docsy.

Currently, Docsy is fixing the year in copyright part with the current year.
It would be nice if we can configure that field. For example, to be "2020 - 2021".

Thanks.

**Comment by LisaFC** [comment]
Gotcha. I'll see if I can come up with a nice way of parameterizing it, though in the meantime you could create your own version of the footer file for your project, and just swap out  {{ now.Year }} with your custom value:

https://github.com/google/docsy/blob/master/layouts/partials/footer.html#L20

Are you likely to always have the current year as the end of your range (and does anyone else have any special requirements)?

**Comment by LisaFC** [comment]
Aha, I see from your linked PR you have already done that! :)

**Comment by nghialv** [comment]
Yes. We temporarily fixed it by overriding the footer.html file.

> Are you likely to always have the current year as the end of your range (and does anyone else have any special requirements)?

Yes. It will be like this.

https://pipecd.dev/

Thanks.

**Comment by yann-soubeyrand** [comment]
Hello, this is not exactly fixing your issue, but this should allow for an easier footer override: https://github.com/google/docsy/pull/1500.
