### ISSUE TITLE
Directory browsing?

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#437]
Is there a way to let the user browse directories? The use case is contributed code, lots of it, going back a long way (i.e. I don't want an individual page for each project). I want to put the archive up there in case a user finds something useful.

I've got the files in the static contents directory, but the Hugo server just shows a blank page when going to the URL instead of listing the contents.

**Comment by LisaFC** [comment]
Hmmm, no, there's nothing built in to Hugo that would do that - the site will just show the page/file at whatever URL you've given it. We build navigation/TOCs in Docsy sites but that's from files that Hugo "knows" about ie MD/HTML files with Hugo frontmatter/metadata.

It might be something you could add yourself to create the directory tree, though that's probably one for the [Hugo discussion site](https://discourse.gohugo.io/). Does anyone else have any ideas?

**Comment by Symbolics** [comment]
I'll close this. The solution I went with what putting the archive on GitHub and allowing them to browse that way.
