### ISSUE TITLE
Link to Google Developer Documentation Style Guide

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#44]
Consider including a link somewhere in the instructions to the Google Developer Documentation Style Guide:

https://developers.google.com/style/

**Comment by LisaFC** [comment]
In the draft user guide now, will close this once it's published.

**Comment by LisaFC** [comment]
Published at draft location here:
https://serene-roentgen-10fbaa.netlify.com/docs/adding-content/content/#content-style
https://serene-roentgen-10fbaa.netlify.com/docs/organizing/#what-about-writing-style

Closing as content won't change when we move to the final URL
