### ISSUE TITLE
Hugo beginner resources?

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#443]
I suspect that I'm not the only one coming at Hugo via the need for a documentation website and Docsy. Are there any recommended resources for folks that are not familiar with Hugo, and with only a passing knowledge of JS/CSS/HTML?

As an example, I want to know how to create a custom page layout, and started with something 'out of the way', the 404 page. Specifically I thought I would try to add the [Space 404 layout](https://codepen.io/eroxburgh/pen/zYYyEPg). Looking at the [Kubernetes 404 setup](https://github.com/kubernetes/website/blob/6a85a072904eb73bbdbf1577a91a918f6dba14b9/layouts/404.html),  it seems like I need to:

- Modify the sites (not the theme) 404.html page in layouts/
- Create a 404-partial.html in the sites partials/ directory (after creating it) to hold the JS
- Do something with the CSS

It seems like customizing a documentation page is going to be relatively common. If there's a FAQ on how to do this, it would be good to put in in the Docsy docs. By FAQ, I mean _basic_ information; there's plenty of information out there on Hugo templates, but most of it is geared to advanced Hugo users or Go practitioners. I'd love to see a section in Docsy called "common tasks" with stuff like this in it. Or a "Docsy for Hugo beginners" or something like that. It seems that the pattern of "find a page design you like, stuff the JS/CSS/HTML into Doscy" is going to be one that at least I'm going to be repeating a few times during this exercise.

If I'm on the right track, perhaps it can be as simple as the list above. Well, except for the CSS. Where is the CSS for a custom page supposed to go?

**Comment by Symbolics** [comment]
For anyone that finds this issue when searching for the same information, you can put the CSS (but _not_ SCSS) into the 404.html page, wrapped in <style> tags.

Whilst this works, it is a case of "the first thing I tried that worked" and unlikely to be considered best practice (unless I got very lucky).

I'd like to suggest leaving this open as a reminder because a simple example of how to add a page with a completely new style, according to best practices, would be a worthwhile addition to the documentation.

**Comment by LisaFC** [comment]
So the resources I normally send people to are the Hugo docs and the Hugo discussion site - do any other users have good "get started with Hugo" content they'd recommend?

We also have a Hugo tips page though it hasn't been updated in a while (must remove the bit about Blackfriday as the Markdown parser as Hugo has been using Goldmark for ages now), if anyone wants to add anything that might trip users up? https://www.docsy.dev/docs/best-practices/site-guidance/

**Comment by Symbolics** [comment]
There's a good explanation of how to add a new page with custom styling on the [Learn style customization page](https://learn.netlify.app/en/basics/style-customization/). It's MIT license, so it could be modified and brought to Docsy, or perhaps just linked to.

**Comment by emckean** [comment]
Closing this now as it's not really an issue, please feel free to open a [Discussion](https://github.com/google/docsy/discussions) if more discussion is needed!
