### ISSUE TITLE
Adding locks icon to certain child pages

### ISSUE THREAD

**Issue by ajeetraina** [google/docsy#444]
I have created child pages but those are private in nature. Is there any way, I can add lock icons 

Like: https://www.freepik.com/free-icon/locked-padlock_778307.htm

```
---
title: "Long Page Title"
linkTitle: "Short Nav Title"
weight: 100
description: >-
     Page description for heading and indexes.
---

## private page (<==== If we can add lock icon here)

This is a private page restricted to specific teams only
```

**Comment by LisaFC** [comment]
Do you want to restrict access to the pages (which is outside the scope of Docsy though may be provided by your hosting solution/something you can implement yourself - see #393), or just show a lock icon?

If it's an image you can just include it in the page like [any other image](/iconsimages/#other-pages), or you could add something conditional in your own project where if the metadata included something like access: restricted you displayed the icon?

**Comment by ajeetraina** [comment]
It's just a lock "image" which I need to add next to a heading of child page.

**Comment by LisaFC** [comment]
This seems to have been resolved with our ability to add icons to menu items, feel free to reopen if necessary.
