### ISSUE TITLE
Modifying the theme to display code blocks in full width

### ISSUE THREAD

**Issue by RinkiyaKeDad** [google/docsy#447]
Hi!

Is there a way to render the code blocks in full width to avoid a horizontal scroll on them? (please ignore the circled part in the image to avoid confusion)
![scroll](https://user-images.githubusercontent.com/56963264/107623117-ddee6780-6c7e-11eb-8eb3-a250e087bc28.png)

Thanks :)

**Comment by LisaFC** [comment]
Yes, just tested it - if you create your own version of _code.scss with max-width=100% for both code blocks and highlight divs you get full width for both:

```
// Code formatting.

.td-content {
	// Highlighted code.
    .highlight {
        @extend .card;
	
        margin: 2rem 0;
        padding: 0;
	**max-width: 100%;**
	    
        pre {
            margin: 0;
            padding: 1rem;
        }
    }

    // Inline code
    p code, li > code, table code {
        color: inherit;
        padding: 0.2em 0.4em;
        margin: 0;
        font-size: 85%;
        word-break: normal;
        background-color: rgba($black, 0.05);
        border-radius: $border-radius;

        br {
            display: none;
        }
    }


    // Code blocks
    pre {
        word-wrap: normal;
        background-color: $gray-100;
        padding: $spacer;
        **max-width: 100%;**
     

        > code {
	    background-color: inherit !important;
            padding: 0;
            margin: 0;
            font-size: 100%;
            word-break: normal;
            white-space: pre;
            border: 0;
        }
    }

    pre.mermaid {
        background-color: inherit;
        font-size: 0;
    }
}
```

**Comment by RinkiyaKeDad** [comment]
Thanks a lot for the reply @LisaFC! I've been testing it too. I found that changing max-width to 100% in [_utilities.scss](https://github.com/google/docsy/blob/master/assets/scss/support/_utilities.scss#L79) also fixes this. Which one of these is the better way to do this?

**Comment by LisaFC** [comment]
The _utilities.scss one will make other things wider as well, not just code blocks, provided you're on a "larger" monitor (ie not a small laptop/tablet or phone): https://github.com/google/docsy/blob/master/assets/scss/_content.scss#L61

So depends on what you prefer for your site - do you want to update just the width of the code blocks or everything else on the page?

**Comment by RinkiyaKeDad** [comment]
Got it. Thanks a lot for the help! :D
