### ISSUE TITLE
specify url for edit this page individually on each page

### ISSUE THREAD

**Issue by laszewsk** [google/docsy#448]
We are developing piplanet.org. As we have several repositories in which we maintain the code and also the documentation as READMEs.md file we like to integrate them as a "copy" into the hugo Web site.

For this reason we are in the need to set the URL of the "Edit this page" individually on the pages that this require. Is there an option to add to the metadata

```
---
...
edit: http:// .... link to where the actual content is managed ....
...
---
```

This way when we edit the page we can jump to the source location.

**Comment by LisaFC** [comment]
Yes, you can update any of the Github link variables (or indeed any variable in config.toml) on a page by page basis:
https://www.docsy.dev/docs/adding-content/repository-links/#link-configuration

So for example if you wanted to change github_repo for a particular page, you'd do something like:

```
---
title: "Example Page"
linkTitle: "Example Page"
date: 2017-01-05
github_repo: "https://github.com/LisaFC/boing"
description: >
  A short lead description about this content page. It can be **bold** or _italic_ and can be split over multiple paragraphs.
---

```

**Comment by laszewsk** [comment]
When I put 

github_repo: "https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/README.md"

I get the following URL:

https://github.com/cloudmesh/cloudmesh-pi-burn/blob/main/README.md/edit/main/content/en/docs/software/burner/_index.md

instead of 

https://github.com/cloudmesh/cloudmesh-pi-burn/edit/main/README.md

I guess the repo assumes hugo structure, while however, I do need a direct link instead. Do you know how to do that?

**Comment by LisaFC** [comment]
Let me check, you might be able to just add an extra variable and some more conditional bits in the partial so it doesn't build the URL if that variable is present.

**Comment by LisaFC** [comment]
If you have a custom URL to a README in another repo, presumably you don't want the "create new child page" link and probably don't want the "file an issue with this project" link?

**Comment by LisaFC** [comment]
OK, done, you can add this to your own project (and we'll see if anyone else is interested). Add github_url metadata to your page:

```
---
title: "Example Page"
linkTitle: "Example Page"
date: 2017-01-05
github_url: "https://github.com/LisaFC/boing/edit/main/README.md"
description: >
  A short lead description about this content page. It can be **bold** or _italic_ and can be split over multiple paragraphs.
---
```

Add your own version of layouts/partials/page-meta-links.html, like this:
https://github.com/LisaFC/boing/blob/master/layouts/partials/page-meta-links.html

Et voila! You do only get one edit link because all the other links are based on having a repo URL and we're pointing users at a specific file in a completely different repo. If you want any of the other links let me know and I'll see if we can figure it out.

**Comment by laszewsk** [comment]
This works beautifully. Thank you Thank you Thank you! I love it

**Comment by laszewsk** [comment]
Thank you again, we hope this feature is going to be integrated into the next release. We use this a lot also on other Web sites

We have for example in another site about 170 distributed repos. Having the feature allows us to manage the web page content in a distributed fashion while making sure the original source is modified easily.

For this reason, we also wrote https://pypi.org/project/cyberaide-bookmanager/ We hope that in the future we can add an option to point to a docsy site that then creates an automatic epub from all the content. It is actually relatively simple to do but we just need to convert the "matadata" to regular markdown or add metadata parsing to our tool.

**Comment by LisaFC** [comment]
I can easily add the feature to the main theme, I might reopen this issue to see if anyone else has preferences (eg any additional links beyond the custom edit link).

Bookmanager tool looks really cool!

**Comment by laszewsk** [comment]
For some reason, I get now when I use

github_repo: "https://github.com/cybertraining-dsc/fa20-523-312/edit/main/project/project.md"

in meta the link on edit as 

https://github.com/cybertraining-dsc/fa20-523-312/edit/main/project/project.md/edit/master/content/en/report/fa20-523-312/project/project.md

Do I use it wrong?

**Comment by LisaFC** [comment]
Are you still using my override? The override lets you provide a separate github_url metadata that's used instead of the generated link.

If you specify github_repo in your page metadata, the layout assumes it's just the repo part of the path and concatenates it with the page path, which is what you're seeing.

**Comment by laszewsk** [comment]
I assume you mean place the page-meta-links.html into ./layouts/partials?
I am getting unfortunately an error, so I assume I must de doing something wrong. Please note I am using the newest theme. 

hugo serve
Error: add site dependencies: load resources: loading templates: "./layouts/partials/page-meta-links.html:531:1": parse failed: template: partials/page-meta-links.html:531: function "className" not defined

**Comment by LisaFC** [comment]
OK, let me check my copy and see if I can reproduce/figure out what's going on!

What version of Hugo and what OS are you using?

**Comment by laszewsk** [comment]
macos 11.4
Hugo Static Site Generator v0.79.0/extended darwin/amd64 BuildDate: unknown

**Comment by LisaFC** [comment]
So I'm currently using 0.82 extended on Netlify and it's working fine with the custom partial. Here's the source for a page with the metadata:
https://github.com/LisaFC/boing/blob/master/content/en/docs/Examples/_index.md

...and here's the rendered page (check the value of the Edit this page link):
https://tender-beaver-c94732.netlify.app/docs/examples/

**Comment by LisaFC** [comment]
though hmm, hang on, not sure if I've updated to the latest version of the theme. Let me do so and see if I need to tweak the partial.

**Comment by laszewsk** [comment]
I just checked with hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
I have the same issue, but I do run the latest theme

**Comment by LisaFC** [comment]
Just updated to the latest theme and it's still working fine on Netlify. Can you try just building our example site with no customizations and see if there are any problems?

**Comment by laszewsk** [comment]
I got it to work with your partials:

I run it on hugo 0.83, the newest release version of docsy, osx newest release

https://github.com/LisaFC/boing/blob/master/layouts/partials/page-meta-links.html

However, I did not get it to work with the regular theme. 
This is such a great feature that it deserves more attention in the regular theme ...

**Comment by laszewsk** [comment]
I think I know what is happening. It only works if the document is in the content/en/docs folder

However, I have all my submodules in content/en/report

Than the link does not get properly created

**Comment by laszewsk** [comment]
here is what I do not understand

my content looks like

layout/partials/page-meta-links.html
content/en/docs
             -> pages under docs do the replacement of github_url correctly
content/en/report/
             here I place my submodules so they do not list in /docs as I only need portions of what is in the submodules, e.g specific files, 
             lets assume the submodule is 
content/en/report/mysubmodule/report/report.md
 
Now when I put github_url in report.md the $gh_url is false and instead goes in the else condition of page-meta-links.html as it seems to think that $gh_url does not exist from Params it displays the wrong URL ...
Do you happen to know how I apply page-meta-links.html properly to files that are not in 
content/en/docs?

**Comment by laszewsk** [comment]
I got it to work after redoing everything.
