### ISSUE TITLE
Search functionality using local search instead of GCS

### ISSUE THREAD

**Issue by maestrofx** [google/docsy#45]
#### Goal
To have a local search functionality (indexing words locally) instead of GCS into the internet.

#### More
First, I found `docsy` is a great theme for my internal/personal documentation/handbook. In production, I separate the contents (writings) with a static page generator. What functionality I love is indexing and searching capability through a lot of articles I have.

#### Feature request
- Is there any roadmap to add local search functionality to `docsy` theme?
- Is this only for Google team's needs btw?

Thank you.

**Comment by LisaFC** [comment]
Hi, no, it's not just for Google teams - anyone can use it!

We haven't planned adding a local search facility specifically to our theme, but there are various search options available for Hugo sites that you can try with it (some free, some not): https://gohugo.io/tools/search/

**Comment by theletterf** [comment]
Adding lunrjs or similar is the way to go, but it’s not trivial for non-developers. Anyone willing to help with this?

**Comment by theletterf** [comment]
@LisaFC I know it’s Google’s, but adding local/offline search can dramatically boost the theme popularity, especially when docs are not meant to be indexed or published in the open.

**Comment by LisaFC** [comment]
Oh yeah, I think having non-Google/local search as an option in the theme is great if anyone wants to work on adding it - we chose the Google custom search engine as our default because it was easy and free to add, not because it's from Google.

**Comment by roidelapluie** [comment]
It would be great if docsy could bring along search (e.g. with https://lunrjs.com/).

Other tools do this (https://squidfunk.github.io/mkdocs-material/getting-started/#site-search) and it is fast and useful for medium websites that are not available over the internet.

**Comment by theletterf** [comment]
I've offline search with Lunr.js working [in my fork](https://github.com/theletterf/docsy). Waiting a bit to polish the code before I open the PR. Could someone try it out and let me know?

![image](https://user-images.githubusercontent.com/1773616/61795703-50d98880-ae24-11e9-88a9-8849bed87bbe.png)

**Comment by roidelapluie** [comment]
request.open("GET", "/index.json", true); => that should repect base url and use relative URL

**Comment by roidelapluie** [comment]
@theletterf you should put a small doc about how to enable it. I struggle with generating the index.json. And there are issue with relative url's.

I am happy to test this further  asap when I know how to generate the index.json ;)

**Comment by LisaFC** [comment]
I'd love if we had a doc about this!

We will also shortly have (not-offline) Algolia docsearch enabled so there are lots of search options to choose from: #127

**Comment by theletterf** [comment]
Will try to resume development soon!

**Comment by theletterf** [comment]
@LisaFC @roidelapluie PR open, at last. :)

https://github.com/google/docsy/pull/142

**Comment by theletterf** [comment]
@roidelapluie Not sure how to fix the relative path issue. It's working for me.

**Comment by LisaFC** [comment]
This is working and checked in thanks to @theletterf :)

**Comment by theletterf** [comment]
Pleasure working with you, @LisaFC ! :)
