### ISSUE TITLE
TOC Fonts?

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#453]
Is there a way to change the fonts in the TOC? As it is, there's a lot of wrapping for a fair few of the headings. Alternatively, a way to move that sidebar out? It seems fixed width now.

I know @narrenfrei is working on some TOC stuff, and this would be a nice addition, assuming that it isn't fixed in some other way by his changes. I've got to say that the number one comment I get from folks that have seen the site is about the TOC; perhaps the fonts will be a good stop-gap measure until we get a new TOC.

Speaking of that, is there a roadmap that indicates what the priorities are?

**Comment by LisaFC** [comment]
Yes, you can change the font by just changing the style in _sidebar-tree.scss. For example if you wanted (not that this is something anyone would want as it's hideous...) it smaller and in Courier/monospace, you'd add something like this in your version:

```
.td-sidebar-nav {
    padding-right: 0.5rem;
    margin-right: -15px;
    margin-left: -15px;
    font-size: 12px;
    font-family: "Lucida Console", "Courier New", monospace;
...
```

and you get:
https://tender-beaver-c94732.netlify.app/docs/tasks/

(you could also run wild and have different fonts for headings and subsections if you get more specific in that file)

Relative widths for the various sections on a docs page (left nav, main content, right nav) are set here:
https://github.com/google/docsy/blob/master/layouts/docs/baseof.html
  
It's just regular Bootstrap so you can tweak it as much as you like (or add more/less padding relative to your text in _sidebar-tree.scss). It's not fixed width btw, if you change the size of the window it should flex.

@emckean is driving our roadmap effort, we will hopefully have something to share/comment on once we are not all quite so swamped in our day jobs...
