### ISSUE TITLE
First level headings?

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#455]
Now that we're starting to put content into Docsy, I've just noticed that first level headings aren't displayed in document TOCs. For example the first level heading:

`# Starting and Finishing` is absent from the document TOC (right side menu)

But `## Starting the application`, the next section does appear in the right-side TOC.

Is this a bug or a feature?

**Comment by narrenfrei** [comment]
You should be able to control the TOC in your config.toml:
https://gohugo.io/getting-started/configuration-markup/#table-of-contents

With this setting all headings from 1-6 should be generated.
```
[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
```
https://github.com/okkur/syna/issues/682#issuecomment-574020598

But only headings from your page content files will be generated in the TOC and not the H1, which is generated from the `title` paramter in your front matter.

**Comment by Symbolics** [comment]
Thanks. So is it a convention (Hugo? Docsy? HTML?) that there is supposed to be only a single `#heading -> H1` in a document, to indicate the title? In the docs I'm working with, many of which are auto-generated or converted, `#/H1` is assigned frequently throughout the document to indicate section headings.

**Comment by narrenfrei** [comment]
I'd say it's more something like religion ;-)

No, before HTML5 it was quiet important, to use only 1 H1 per page. And now ....? I think, this article explains it queit well.
https://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824

If you want to use more H1 in your pages, you can set `startleve = 1`. But if you really should do it? I say nothing at all :-D

**Comment by Symbolics** [comment]
Thank you, that's useful to know. It seems then, in this case, multiple H1 headings are incorrect, since the entire page covers a single topic. I'll see about getting the generator adjusted.
