### ISSUE TITLE
Fetching Twitter Feeds and placing it over Child page

### ISSUE THREAD

**Issue by ajeetraina** [google/docsy#458]
I want to fetch tweets from our community experts and have been able to get success half-way via

```
<a class="twitter-timeline" data-dnt="true" data-theme="light" href="https://twitter.com/testprojectcommunity/lists/test-projectcommunity-16220?ref_src=twsrc%5Etfw">A Twitter List by Testprojectcommunity</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

But the problem is it fetches overall tweets. I am looking out for a way I can fetch tweets having "TestProject" as a term in the tweet. Any idea if it is still possible?

**Comment by LisaFC** [comment]
This might be a better question for the Hugo discussion forum as they have a broader community of users who might have tried doing this in their sites: https://discourse.gohugo.io/
