### ISSUE TITLE
How should I close RSS?

### ISSUE THREAD

**Issue by thinkerou** [google/docsy#46]

**Comment by rionam** [comment]
Can you provide more detail? What are you trying to do?

**Comment by thinkerou** [comment]
@rionam thank your reply! At the page https://gin-gonic.com/blog/
Now:
![image](https://user-images.githubusercontent.com/4488261/53743405-b230a780-3ed5-11e9-96c8-7123494632ee.png)
I hope this:
![image](https://user-images.githubusercontent.com/4488261/53743489-e4420980-3ed5-11e9-9048-fbc81c6f575b.png)

If the page is post page https://gin-gonic.com/blog/2019/02/26/how-to-build-one-effective-middleware/
when the page no longer display `RSS`, content width also change, thanks!

**Comment by rionam** [comment]
Hi
Looks like you can disable RSS as follows: https://kodify.net/hugo/pages/disable-rss-feeds/
We will update our documentation to point to this. Hope this helps.
