### ISSUE TITLE
Revert #383: menu .Identifier fields meant for structuring menus not HTML ids

### ISSUE THREAD

**Issue by chalin** [google/docsy#460]
After looking at #383, I reread the [`menu` docs under Nesting](https://gohugo.io/content-management/menus/#nesting) where it states that (emphasis mine):

> In practice, `.Name` and `.Identifier` are only used to structure relationships and **therefore never displayed**.

In my opinion, `.Identifier` was never intended to be rendered as an HTML `id` field.

`id` fields are meant to be unique in any given page and #383 (silently) introduces `id` fields for all menus with `. Identifier` fields -- which means all menus with nested subentries. I think that #383 should be reverted.

@LisaFC - if you agree, I don't mind submitting a PR to revert #383. Thanks.

**Comment by LisaFC** [comment]
Thanks for spotting that - and yes, from looking at the Hugo docs I think you're right, I don't think it serves any useful purpose once the site is generated.
