### ISSUE TITLE
Configuring time_format_blog

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#466]
I have configured the time format to European style in the _theme_ config.toml and wonder if this is the correct location. The documentation suggests that this kind of configuration should be one in the _site_ configuration, but the project template does not have this parameter in its toml file.

Is there something special about 'blog configuration that means it has to be done in the theme? If not, perhaps these parameters should be moved into the site config.toml.

**Comment by LisaFC** [comment]
You can add any param you like to your own config.toml, even ones we haven't used if you want to use them in your own customizations!

There's a time format in the theme because that's one of the few things you can make a default for any project using a theme.

**Comment by Symbolics** [comment]
Thanks @LisaFC. I'm not exactly sure I follow. Would 'best practice' put it in the theme or the site config.toml?

**Comment by LisaFC** [comment]
Your own version should go in your site config.toml (as that's specific to your site). There's nothing special about the params in the theme, other than that they're defaults for any site using it - your own config.toml params will override them if you want.
