### ISSUE TITLE
toc_hide: true works in TOC, but still shows in top-level documentation page

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#476]
I'm trying to hide the Reference section until we can work out a few issues with the API documentation generation. Adding `toc_hide: true` to `Reference/_index.md` works to hide it in the TOC, but from the top level documentation http://127.0.0.1:1313/docs/ the Reference section still shows up in the list on the page.

**Comment by narrenfrei** [comment]
Yes, you're right. But I think, that's feature and not a bug ;-)

The parameter toc_hide really only hide the page from the side bar menu (TOC), but the page is still reachable. (For example by the links in the section index area of the parent page.)

If you really want to hide a page completely, you can set the parameter draft: true.

**Comment by Symbolics** [comment]
That's got it, thanks.
