### ISSUE TITLE
Search on  https://example.docsy.dev finds results on https://temp.bep.is

### ISSUE THREAD

**Issue by narrenfrei** [google/docsy#479]
Don't know if it's a bug, feature or simply a artifact from bygone times, but when you search for "api" on https://example.docsy.dev you'll get results from https://temp.bep.is

**Comment by LisaFC** [comment]
Oh weird, that is truly an artifact from bygone days. The site search is a Google custom search, I'll take a look at the settings and see if I can rescope it.
