### ISSUE TITLE
Add Google Analytic

### ISSUE THREAD

**Issue by thinkerou** [google/docsy#48]

**Comment by theletterf** [comment]
You can already do that. It’s in the docs. 

https://www.docsy.dev/docs/adding-content/feedback/

**Comment by theletterf** [comment]
Oh I see. You didn’t close this one.

**Comment by chalin** [comment]
I don't understand what the issue is here. Do you @LisaFC? Based on #49, I get the impression that the intent was to have Docsy support GA, which it clearly does now. I'm going to close this issue. Feel free to open a new one if something is still missing.
