### ISSUE TITLE
Using the Algolia DocSearch

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#486]
According to the [documentation on this topic](https://www.docsy.dev/docs/adding-content/navigation/#configure-algolia-docsearch), you are supposed to:

> Add the JavaScript code provided to you by Algolia to the head and body of every page on your site. See Add code to head or before body end for details.

Is that correct? Adding the JavaScript to the head _and_ body? It seems like one or the other should be sufficient.

**Comment by LisaFC** [comment]
@alexearnshaw, can you take a look at this? (Alex added the feature!)

**Comment by alexearnshaw** [comment]
From what I remember it’s not the same code you add to the head and body end, but 2 different snippets of code, unless Algolia have since changed the code they send?

**Comment by Symbolics** [comment]
I see, I didn't realise it went in two different places. I "applied" yesterday and still haven't received the JavaScript codes from Algolia. Will report back here once I have them.

**Comment by Symbolics** [comment]
No response yet from Algolia, but a related question: should Docsy be one of the [Algolia supported integrations](https://docsearch.algolia.com/docs/integrations)?

**Comment by prdsoftware** [comment]
Yeah, this same issue tripped me up initially.  I didn't realize there was 2 different places to update.  Only upon re-reading the documentation carefully I got it.  Algolia took a few days to get back to me, but it's an awesome product and soooo much better than the Google custom search.

**Comment by LisaFC** [comment]
> No response yet from Algolia, but a related question: should Docsy be one of the [Algolia supported integrations](https://docsearch.algolia.com/docs/integrations)?

That's a good idea - I was looking at their other listed integrations and they're no more/less integrated than we are. :) I'll send them a link to our docs and see if we can get them to list us.

**Comment by LisaFC** [comment]
They are going to add us to their list! Will close this now.
