### ISSUE TITLE
git update bootstrap

### ISSUE THREAD

**Issue by denalon** [google/docsy#490]
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "/denalon/code/library/assets/scss/_boxes.scss", line 7, col 18: argument `$color2` of `mix($color1, $color2, $weight: 50%)` must be a color

**Comment by denalon** [comment]
The following prompt appears in the update bootstrap：

line 4, col 18: argument `$color2` of `mix($color1, $color2, $weight: 50%)` must be a color 
line 7, col 18: argument `$color2` of `mix($color1, $color2, $weight: 50%)` must be a color

**Comment by LisaFC** [comment]
Yes, it's a known issue with Bootstrap 5 - we have an open issue to look into it  #470 (it may be a more general Hugo problem as we're not the only theme it's broken)  If you don't *need* Bootstrap 5 everything should work fine with the latest version 4, which is the most recent GA version.
