### ISSUE TITLE
Project info: add URL https://docsy.dev

### ISSUE THREAD

**Issue by deining** [google/docsy#494]
To allow users get started quickly, I would propose to add https://docsy.dev to the project info in the top right corner:

<img src="https://user-images.githubusercontent.com/18169566/112891349-59459480-90d8-11eb-9ec5-a9af8dd6a3fa.png"  width="400" />

Adding some keywords (represented as cloud tag) would make sense too, IMHO.

**Comment by LisaFC** [comment]
Great suggestion! Done.
