### ISSUE TITLE
Add author mechanism

### ISSUE THREAD

**Issue by huehnerlady** [google/docsy#503]
HI,

I absolutely love the docsy theme, it also has a blog theme, and I like that I can put everything at one point.

I am missing a possibility to have authors though.
Currently we using [this theme](https://github.com/jonathanjanssens/hugo-casper3). It allows an authors page (see for example [here](https://tech.europace.de/authors/) which is really handy to see other articles from this Author and also get more information, which is stored centrally and not per blog-post.

Is there any plan to add something similar to docsy?

**Comment by narrenfrei** [comment]
One possibility is to use taxonomies. In our intern documentation (So I can't give you a public link with an example.) I've generated a taxonomy called person, which I use to assign responsible contact person to specific topics. So I can also generate a page with all assigned articles of a person.

**Comment by huehnerlady** [comment]
@narrenfrei that sounds cool, could you maybe add that into your blog theme? :)

**Comment by narrenfrei** [comment]
Before I find the time to make a PR for the tagging function like I use it in our internal doc (There exist already a PR and discussion about tagging at #324), I want to leave a hint, how this can be done generally: 
https://moonbooth.com/hugo/authors/

**Comment by narrenfrei** [comment]
Some additional info:
Docsy already uses a "author" front matter, but this is no predefined front matter of Hugo. So, if you also want to have a separate page for each author generated by Hugo, it maybe will be easier to add the author info like described in the link above by using taxonomies.
