### ISSUE TITLE
Fine grain UI configuration options

### ISSUE THREAD

**Issue by RichieEscarez** [google/docsy#51]
While the Docsy template does allow users to override UI elements, we should consider "chunking" out certain parts and their corresponding configuration so that overriding "look and feel" of any site has less overhead.

For example, the Community page allows you to set text and URLs through configuration parameters (config.toml), is it possible to use that model to allow easier manipulation of more than just text (like the size, position, behavior of UI elements)?

**Comment by LisaFC** [comment]
It's definitely doable, either via variables for CSS or in config.toml (eg we had a recent PR that let you switch on and off the search box on the left nav, and we have an issue to make the top nav more configurable), we just need to decide which elements users would most like to be able to tweak. Can we refine this a bit and have specific issues for specific UI elements?

**Comment by emckean** [comment]
Closing this as it's been an ongoing process to config all the things :) 
we can start a discussion if we want folks to nominate more items to add to config.toml.
