### ISSUE TITLE
Filtering twitter timeline

### ISSUE THREAD

**Issue by ajeetraina** [google/docsy#515]
I am able to pull tweets using Twitter timeline and paste it over one of the child page successfully as shown under https://docker.github.io/get-involved/docs/captains/newsfeed/

```
<a class="twitter-timeline" data-width="1000" data-height="6000" data-link-color="#cc0000" data-chrome="noscrollbar transparent" data-tweet-limit="20" data-border-color="#cc0000" href="https://twitter.com/dockercommunity/lists/dockercaptains-55156?ref_src=twsrc%5Etfw">A Twitter List by dockercommunity</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

But I want to filter the content and want to just display only a specific word or pattern. Is it possible?

**Comment by emckean** [comment]
Hi Ajeet! This is more of a Twitter question than a Docsy question. :)
