### ISSUE TITLE
TabPane Feature does not work on live site

### ISSUE THREAD

**Issue by nryberg** [google/docsy#524]
The TabPane feature (which is great) doesn't work on the live Docsy site:

https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes

When I click the tabs, the content doesn't change.  

This also doesn't work on a local Hugo install, but would like to see it working on the main site. 

Using Chrome Version 87.0.4280.88 (Official Build) (64-bit) on Windows.   Testing on FireFox on Windows also does not work.

**Comment by LisaFC** [comment]
Hmm, that's weird, I think it was working in the preview when we merged it. Let me see if anything has changed since then/if we have mismatched versions of anything.

**Comment by LisaFC** [comment]
Working again now! Fixed by #522

**Comment by nryberg** [comment]
That was it - hand edited the SHA per #522 and it works fine.
