### ISSUE TITLE
Update Hugo branding in RSS XML feed

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#53]
The term 'Hugo' appears in the generated RSS when it shouldn't:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>OpenCue – New Releases</title>
<link>/blog/releases/</link>
<description>Recent Hugo news from gohugo.io</description>
<generator>Hugo -- gohugo.io</generator>
<lastBuildDate>Fri, 15 Feb 2019 19:06:19 -0500</lastBuildDate>
<image>
<url>img/hugo.png</url>
<title>GoHugo.io</title>
<link>/blog/releases/</link>
</image>
```

I believe this is caused by the contents of the [RSS XML template](https://github.com/google/docsy/blob/3ca22ac9a0b7e4b4faf54cd4f4ab272695f1516a/layouts/_default/list.rss.xml).

Specifically this section:

```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ .Site.Title }} – {{ .Title }}</title>
    <link>{{ .Permalink }}</link>
    <description>Recent Hugo news from gohugo.io</description>
    <generator>Hugo -- gohugo.io</generator>{{ with .Site.LanguageCode }}
    <language>{{.}}</language>{{end}}{{ with .Site.Author.email }}
    <managingEditor>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</managingEditor>{{end}}{{ with .Site.Author.email }}
    <webMaster>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</webMaster>{{end}}{{ with .Site.Copyright }}
    <copyright>{{.}}</copyright>{{end}}{{ if not .Date.IsZero }}
    <lastBuildDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</lastBuildDate>{{ end }}
    <image>
      <url>{{ "img/hugo.png" | absURL }}</url>
      <title>GoHugo.io</title>
      <link>{{ .Permalink }}</link>
    </image>
```

Ideally, the template needs to be updated to populate the <description>, <image> <title>, <image <url> from variables so that the tenant Docsy sites don't need to overrider this template locally.

**Comment by sharifsalah** [comment]
Also, related to this, there are a bunch of issues related to the validity of the RSS feed:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftestydocsy.netlify.com%2Fblog%2Findex.xml

In particular, the XML should generally be using full URLs as opposed to relative paths. I expect this is going to require some way of configuring Docsy with the root domain for the site.

**Comment by LisaFC** [comment]
Configuring the root URL is easy, you just set rootUrl in your config.toml or in your netlify.toml if you just want it for your Netlify deployment versus your local copy. I'll mention in the docs you should do that if you want a valid RSS feed. Will take a look at the actual feed template now...

**Comment by sharifsalah** [comment]
Ah thanks, I don't think I had got round to configuring the root URL yet, which explains why I saw this behavior. I have since configured the root URL for robots.txt and it's working as expected. So it is just the template.
