### ISSUE TITLE
GitHub Pages failing to build the site.

### ISSUE THREAD

**Issue by collabnix** [google/docsy#531]
While building the site using docsy, I am facing the below error:

```
A file was included in assets/vendor/bootstrap/site/docs/4.5/components/alerts.md that is a symlink or does not exist in your _includes directory.
```

Any idea how to fix this?

**Comment by LisaFC** [comment]
So GitHub Pages doesn't build Hugo sites by default (I think that error is looking for an _includes directory, which is something that Jekyll uses) - you need to either build it yourself locally and serve the generated site, or set up a GitHub Action (new!) to build it.

Follow the instructions here: https://gohugo.io/hosting-and-deployment/hosting-on-github/

Let me know if that's something you've already tried!

**Comment by LisaFC** [comment]
Did that work? Will close the issue if so.
