### ISSUE TITLE
Title off center on mobile

### ISSUE THREAD

**Issue by ianlewis** [google/docsy#54]
The title is off center because of assets/icons/logo.svg being being included in the html. If the file is deleted then an error is generated during rendering. I couldn't figure out a way to conditionally include the logo from the assets/ directory. Page resources can't read it and readFile doesn't seem to work either.

![Screenshot 2019-03-14 at 19 35 07](https://user-images.githubusercontent.com/49289/54350286-57930a80-4690-11e9-97be-b5f550e854db.png)

**Comment by LisaFC** [comment]
Currently trying to fix this and make the navbar a bit more flexible!

**Comment by ianlewis** [comment]
Thanks! I didn't submit a PR since I couldn't quickly think of a way to fix it without breaking existing sites.

**Comment by LisaFC** [comment]
So the easiest way to do this without breaking anything is to just remove the "blank" icon file in the theme and add an  {{ if (fileExists "") }} check in the navbar partial, which means the thing works and is centred even if you don't have an icon.
