### ISSUE TITLE
Disable lastmod when no GitHub info is present

### ISSUE THREAD

**Issue by huehnerlady** [google/docsy#541]
I stumbled onto the problem, that the information of the last modification is still shown, but not working, if you do not add the GitHub repository link. For some websites it does make sense not to show that info

I created a [pull request](https://github.com/google/docsy/pull/509) already for my idea, but due to a missing cla it cannot be merged.
So hopefully there is someone else that likes the idea and would work on it 🙂

**Comment by deining** [comment]
@huehnerlady, why did you delete the branch `disable-lastmod-when-no-github-info-is-present` from your docsy fork? I just wanted to submit your PR on your behalf (I do have CLA signed), but now I'm not able to pull it in from your repo :-(. Can you please restore the branch to your GitHub fork using a local copy? Thanks.

**Comment by huehnerlady** [comment]
@deining I see, I did not think that the branch would be any use to someone as it was in my fork (I am not that familiar with forking yet).

I restored it so now you should be able to use it :) 

Thanks for your help

**Comment by huehnerlady** [comment]
@deining would you be able to use my branch now? I like to clean up and would delete my fork as I am not able to contribute without signing the CLA :)

**Comment by deining** [comment]
> @deining would you be able to use my branch now?

Yes. Give me some time, this is in my TODO list.

**Comment by deining** [comment]
Created PR #557 to eventually resolve this issue.

**Comment by huehnerlady** [comment]
As it was not linked, but is now merged, I close this issue manually now, @deining many many thanks for your help
