### ISSUE TITLE
Enhancement: add hooks/ head partial for inclusion of cookie consent script(s)

### ISSUE THREAD

**Issue by aimeeu** [google/docsy#545]
We are required to make our docs site GDPR compliant. This involves adding JS to the header. We tried adding the scripts to our copy of hooks/head-end.html, but Google Analytics fires before the cookie consent scripts do. Rather than disabling GA in config.toml and instead adding JS to enable it, the solution is to move GA template inclusion after head-end partial.

```
{{ partial "hooks/head-end.html" . }}
<!--To comply with GDPR, cookie consent scripts placed in head-end must execute before Google Analytics is enabled -->
{{ if hugo.IsProduction }}
{{ template "_internal/google_analytics_async.html" . }}
{{ end }}
```

I will submit a PR for this.

**Comment by LisaFC** [comment]
Fixed in #546
