### ISSUE TITLE
For SEO, we should generate an XML sitemap for each site

### ISSUE THREAD

**Issue by rionam** [google/docsy#55]
sitemap.xml is important for SEO, and is supported by Hugo: https://gohugo.io/templates/sitemap-template/

We should also document this: for example, how to change the sitemap frequency etc.

**Comment by sharifsalah** [comment]
It might be good to also demonstrate the relevant configuration for the sitemap in the docsy-example [config.toml](https://github.com/google/docsy-example/blob/master/config.toml) file:

Config info:

https://github.com/google/docsy-example/blob/master/config.toml

**Comment by LisaFC** [comment]
Good idea (and it does it all by itself unless you want to configure it: https://docsydocs.netlify.com/sitemap.xml)

Should we just add it to the Adding content page?

**Comment by rionam** [comment]
Great idea

**Comment by LisaFC** [comment]
Done!
