### ISSUE TITLE
How do you comment out a line or section of your content?

### ISSUE THREAD

**Issue by ceedgedev** [google/docsy#562]
If I have a line of content that I want to comment out so it doesn't display on the production site, how would I do that?
Thanks

**Comment by Symbolics** [comment]
The same way you comment out HTML, with `<!-- ... -->`

**Comment by ceedgedev** [comment]
Thanks, I use /* or // with HTML., I think. I tried several different things but didn't include the --. Thanks for the prompt response. I've looked all over and couldn't find an answer.
