### ISSUE TITLE
Section menu doesn't show siblings of parent pages

### ISSUE THREAD

**Issue by AaronCrawfis** [google/docsy#571]
After https://github.com/google/docsy/commit/70bf4bc580ce984c042dcfd9eeb0637cfe63cc59#diff-936974843f4ebd4ed902f880848d8640095e1506bb3d6c42bd04114a6746e14a the section menu doesn't show the sibling pages of parents anymore.

I would like to be able to show all pages at all parent levels. Is there a new parameter I'm missing?

## Before commit (correct)

All parent pages, and siblings of parents are shown.

![image](https://user-images.githubusercontent.com/54363786/119608679-31f30700-bdab-11eb-98ca-ebbfeb30bdce.png)

## After commit (incorrect)

Siblings of parents are missing. (ignore indentation, that's due to something else)

![image](https://user-images.githubusercontent.com/54363786/119608879-8ac29f80-bdab-11eb-87e9-6e659fceb67c.png)

**Comment by AaronCrawfis** [comment]
@narrenfrei any ideas?

**Comment by narrenfrei** [comment]
I'll take a look. Is the site public? Could you share a URL with me.

**Comment by narrenfrei** [comment]
I've already found it. When I can remember me correctly, I'd gave some thought around while coding, what's the better behavior. Thought I'd decided to make it the same way, as it was before. Maybe not? I'll make a PR (hopefully) in the evening.

**Comment by narrenfrei** [comment]
#575 should restore the old behavior

**Comment by narrenfrei** [comment]
@AaronCrawfis
I think, this Issue can be closed, if #575 works as expected.

**Comment by AaronCrawfis** [comment]
Perfect, thanks! Confirmed working
