### ISSUE TITLE
Would like a way to avoid uppercasing the navbar title

### ISSUE THREAD

**Issue by mhansen** [google/docsy#572]
Hi Docsy authors!

I'm migrating the Graphviz website to Docsy, and Docsy styles the title as "GRAPHVIZ", using the CSS class `text-uppercase` which is `!important`, with no easy way to override.

There is a hard way to override: fork the entire `layouts/partials/navbar.html` file, but I would like to gain from any of Docsy's updates to the navbar.

I think a bunch of sites will want to control their branding at the top-left to not be auto-capitalized? https://grpc.io/docs/ for example, styles their name 'gRPC' not 'GRPC', and they forked navbar.html to achieve this.

**Comment by LisaFC** [comment]
That's a good suggestion - it should be easy enough to parameterize the styling for the navbar title.

**Comment by mhansen** [comment]
Just brainstorming some options:
- an overridable layout partial file?
- overridable title text in the config yml? navbar_title or something like
that?
- remove the !important from the css to make it easier to override?
- (perhaps the simplest option but not backwards compatible): change the
default to not capitalise, and let users capitalise their title string if
they want it presented like that?

**Comment by narrenfrei** [comment]
I think would no CSS styling like capitalize. The site title should be shown as it's typed in the config.toml by default. If someone likes it capsized, this should be done by the project specific stylesheet.

**Comment by mhansen** [comment]
Just to link up the issues, this was the change I landed in Graphviz to un-capitalize the title: https://gitlab.com/graphviz/graphviz.gitlab.io/-/merge_requests/354
