### ISSUE TITLE
如何拉取所有主机的信息

### ISSUE THREAD

**Issue by Nginx1** [google/docsy#576]
我们监控服务器有1000+但是现在只能单独拉取一个服务器信息，我想拉取所有服务器信息以及其他备注和资产的信息

**Comment by theletterf** [comment]
?

**Comment by mhansen** [comment]
Google Translate says:

> How to pull the information of all hosts
>
> We have 1000+ monitoring servers, but now we can only pull one server information separately. I want to pull all server information and other remarks and asset information

Seems like a question about monitoring and aggregating a server farm, seems to have nothing to do with Docsy.
