### ISSUE TITLE
Community page layout is a bit odd

### ISSUE THREAD

**Issue by LisaFC** [google/docsy#58]
The padding around the text, etc. on the community page is a bit unsatisfactory (possibly because I wrote it in a hurry before a demo) - @markmandel, you don't fancy tidying it up, do you?

**Comment by LisaFC** [comment]
#73 definitely makes this look less weird as there's more padding round the sides.

**Comment by markmandel** [comment]
Thank you for doing this work, so I didn't have to :smile:

**Comment by LisaFC** [comment]
I deem this fixed now that #73 is in, we can always iterate on it...
