### ISSUE TITLE
Documentation for site setup does not show the collapsible sidebars with triangles

### ISSUE THREAD

**Issue by laszewsk** [google/docsy#582]
Neither the sample web page or the setup guide in the docsy documentation show the nice collapsible menus with the icons. Here is a super nice example

https://narrenfrei.github.io/docsy-dev-page/docs/tutorials/multi-bear/

**Comment by narrenfrei** [comment]
Hi, in the moment the features are not in the official Docsy version, but there already exists a ready PR #518 waiting for merge. The documentation therefore you can find (at the moment only) here: https://deploy-preview-518--docsydocs.netlify.app/docs/adding-content/navigation/#section-menu

When the PR is merged you will be able to enable the foldable menu by setting `ui.sidebar_menu_foldable = true` in your projects `config.toml`.

How to use the icons is (already) described in the official docs: https://www.docsy.dev/docs/adding-content/navigation/#adding-icons-to-section-menu and https://www.docsy.dev/docs/adding-content/navigation/#adding-icons-to-the-top-level-menu

**Comment by prdsoftware** [comment]
Looks great.  Really looking forward to this being implemented.  Thanks for your hard work on this.

**Comment by LisaFC** [comment]
Fixed in #518
