### ISSUE TITLE
Incorrect displayed feature block if using *.md files

### ISSUE THREAD

**Issue by TOsmanov** [google/docsy#584]
Current situation:
When you add a feature block to the .md page, the block is displayed incorrectly

![image](https://user-images.githubusercontent.com/54434686/121153469-c307ba80-c84e-11eb-8ac0-6de442554ae6.png)

HTML generated:

![image](https://user-images.githubusercontent.com/54434686/121153534-d155d680-c84e-11eb-9791-1c3d57f3f968.png)

The temporary solution is to roll back this change:

https://github.com/google/docsy/commit/908135d

**Comment by LisaFC** [comment]
@deining, do you want to take a look at this?

**Comment by TOsmanov** [comment]
Looks like this problem is with the 4 spaces in line 9 and 16 `features.html` if you write:
```
    {{ if eq .Page.File.Ext "md" }}
      {{ .Get "title" | markdownify }}
```
In one line:
```
    {{ if eq .Page.File.Ext "md" }}{{ .Get "title" | markdownify }}
```
the problem does not occur
