### ISSUE TITLE
Looks like some test data got into docsy.dev

### ISSUE THREAD

**Issue by mhansen** [google/docsy#589]
https://www.docsy.dev/docs/adding-content/lookandfeel/

Looks like there's some test data for new docsy features on docsy.dev. It makes it a bit unclear which is the actual docs for docsy vs which is test data.

![image](https://user-images.githubusercontent.com/105529/121832647-e4b0e800-cd0d-11eb-8aa3-b55217c21180.png)

For example there are now two 'previews and deployment' pages:

![image](https://user-images.githubusercontent.com/105529/121832701-0316e380-cd0e-11eb-9bfa-eb25543972db.png)

Not sure if this is intended or if it was meant for the docsy example site instead?

**Comment by narrenfrei** [comment]
I have already informed @LisaFC  about it: https://github.com/google/docsy/pull/554#issuecomment-859932625

**Comment by mhansen** [comment]
Ah, thanks!

**Comment by LisaFC** [comment]
Fixed!
