### ISSUE TITLE
Updating Docsy moves navbar to the left (wrong) side

### ISSUE THREAD

**Issue by mhansen** [google/docsy#590]
Hi there, I just updated Graphviz to the latest Docsy with `git submodule update --remote`, now the table of contents is on the wrong side of the screen:

![image](https://user-images.githubusercontent.com/105529/121833883-b385e700-cd10-11eb-9d77-985f66bba936.png)

I suspect this is related to #554 merged 2 days ago, because that commit changed the navbar HTML layout from a `<div>` tag to an `<aside>` tag: https://github.com/google/docsy/pull/554/files#diff-4a7bcb5855bcc928f61527aba2cb16f957266b13ab51553e46016c82ac8c4dd2R16. But I haven't looked into it further than that yet.

**Comment by mhansen** [comment]
If you'd like to reproduce, git clone https://gitlab.com/graphviz/graphviz.gitlab.io and run `git submodule update --remote` then `hugo serve`

**Comment by mhansen** [comment]
I just confirmed that #554 is the cause: I checked out f82dd5efa0eb5a03086498686f9e60f7bd2bb5f3 (immediately before #554 was merged) and the navbar is on the correct side.

**Comment by mhansen** [comment]
@narrenfrei FYI -- perhaps this has the same cause as the test data getting into docsy.dev?

**Comment by LisaFC** [comment]
Oh yeah, that shouldn't do that - let me take a look. I don't think it's anything to do with the test data, that was just data that got merged in in error.

**Comment by LisaFC** [comment]
Though it is very weird, as if I look at the deploy preview for #554 (https://deploy-preview-554--docsydocs.netlify.app/docs/) the table of contents is in the right place, so I'm not sure why it's shifted left for you. Can you tell me what browser you're using?

We'll try and get the test data removed ASAP as well.

**Comment by mhansen** [comment]
Yeah, maybe it’s something about my layout. I’m using macOS Google Chrome.

**Comment by narrenfrei** [comment]
Maybe it's browser specific. But I have to ask: do you have any project specific Stylesheets?

**Comment by mhansen** [comment]
The only extra css we add is prism.css for syntax highlighting.

**Comment by narrenfrei** [comment]
@mhansen 
Have you tried to update all sub modules as described in https://www.docsy.dev/docs/getting-started/#using-the-command-line by `git submodule update --init --recursive`?

Because after running your commands above ...
```
git clone https://gitlab.com/graphviz/graphviz.gitlab.io
git submodule update --remote
hugo server
```
... I've got some error message. But after running `git submodule update --init --recursive` Hugo could build the site and the TOC was shown on the right position.

**Comment by mhansen** [comment]
I'm able to build the site. Is the error message you get

"WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always
return false."?

I think `git submodule update --init --recursive` undoes the `git submodule
update --remote`, reverting back to the previously-commited version of
docsy.

**Comment by mhansen** [comment]
Try this, I think I skipped a step:

git clone https://gitlab.com/graphviz/graphviz.gitlab.io
git submodule update --init --recursive
git submodule update --remote
hugo server

**Comment by narrenfrei** [comment]
After this steps I get also the right positioned TOC.
Tested on MAC with Safari, Chrome and Firefox

**Comment by LisaFC** [comment]
Excellent! Can I close the issue?

**Comment by mhansen** [comment]
Ah, sorry for the hassle. I just reran my own repro steps in a fresh git repo and couldn't reproduce. Sorry for wasting your time; I'll close this for now and update if I figure out how I screwed up my git repository. Probably ran some bad submodule command.

**Comment by mhansen** [comment]
By the way, on the fresh repo I still see this error `WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.`, do you see that too? It seems new in the latest merge request (#554) but perhaps again I messed up my git repo.

**Comment by mhansen** [comment]
For the archives: I think I just had my git submodules out of sync --
perhaps I had a different bootstrap submodule than a docsy submodule.
Running a few submodule update commands fixed it. Sorry again for the
trouble!
