### ISSUE TITLE
How to change the "Edit this page" link via metadata? 

### ISSUE THREAD

**Issue by laszewsk** [google/docsy#597]
The new menu version works really well. I am still looking for the solution that changes the "Edit this page" link to a link that is somewhere else rather than the source hugo content (e.g. it is in a different repo because its in a submodule)

Scenario:

I have about 100+ submodules in hundred different repos that bring in content into hugo via submodules.
The issue I have is that for the user it is unintuitive if they press edit this page and do not end up to the page where the real content is maintained. I thought this was implemented, but I could not find the documentation for it.

Is this implemented? If yes, how do I do it? Right now I have a link under the title, but that is not that nice ...

**Comment by LisaFC** [comment]
I remember coming up with a fix (for you!) in #448 that lets you specify a per-page edit URL - does that still meet your needs? If so I can look at adding it to the main theme.

**Comment by laszewsk** [comment]
See my comment in #448 I have now difficulties using it. Maybe I use the feature wrong I assumed I can just overwrite the link, but it gives me a wrong link

**Comment by laszewsk** [comment]
I got it to work by redoing everything
