### ISSUE TITLE
community_links.html: Contribution Guidelines is hardcoded

### ISSUE THREAD

**Issue by markmandel** [google/docsy#6]
Relevant line:
https://github.com/google/docsy/blob/master/layouts/partials/community_links.html#L17

```html
<p>You can find out how to contribute to these docs in our <a href="/docs/contribution-guidelines/">Contribution Guidelines</a>.
```
It would be great if /docs/contribution-guidelines/ could be something you could overrride, maybe in the config.toml.

I moved my contribution section around a bit, and this broke things :cry:

**Comment by emckean** [comment]
fixed in #1044
