### ISSUE TITLE
Cannot get partials to render at all

### ISSUE THREAD

**Issue by martinbean** [google/docsy#609]
I’ve got a Hugo-based project with the Docsy theme installed as a submodule at **themes/docsy**. However, I cannot get partials to be parsed no matter what I do.

I have a content file like this:

```html
<!-- content/index.html -->
---
title: Home
---
{{ partial "platform.html" . }}
```

And this partial:

```html
<!-- layouts/partials/platform.html -->
<p>Platform</p>
```

But the partial doesn’t get parsed at all; the literal string `{{ partial "platform.html" . }}` just gets dumped in the browser.

Am I doing something wrong here or misunderstanding what Docsy is?

**Comment by narrenfrei** [comment]
Looks for me, as you try to use partials in a content file. Partials only work in layout files. In content files you have to use shortcodes. (If I understood the concept right ;-) h

https://jpdroege.com/blog/hugo-shortcodes-partials/

**Comment by LisaFC** [comment]
@narrenfrei is correct! (and I found that confusing when I started working with Hugo)

We have multiple built-in shortcodes in Docsy, and you can also follow links to the Hugo shortcodes docs: https://www.docsy.dev/docs/adding-content/shortcodes/

**Comment by martinbean** [comment]
@narrenfrei @LisaFC Thanks for helping fill my knowledge gap!
