### ISSUE TITLE
Foldable sidebar cuts off entries, even if sidebar_menu_truncate is sufficiently high

### ISSUE THREAD

**Issue by dholbach** [google/docsy#616]
For a minimal test-case, please see: https://github.com/dholbach/new-site

![Screenshot from 2021-07-02 10-29-20](https://user-images.githubusercontent.com/1346979/124245586-697a6f00-db20-11eb-9cbe-012d645908e1.png)

For a more elaborate one, please see <https://github.com/fluxcd/website/> and the "Flux CLI" section under https://fluxcd.io/docs/

**Comment by LisaFC** [comment]
@narrenfrei, as our Foldable Sidebar King, can you take a look at this?

**Comment by narrenfrei** [comment]
@dholbach Do you mean the issue, that that the last link can't get seen completely or is really a menu item missing?

**Comment by dholbach** [comment]
@narrenfrei The entries are sorted alphabetically, see https://github.com/dholbach/new-site/tree/main/content/docs/section for the full list of entries. niH... is the last one that can be accessed in the foldable menu.

**Comment by dholbach** [comment]
To clarify this somewhat: from judging the generated HTML all entries are added. It might be a styling issue? :man_shrugging:

**Comment by narrenfrei** [comment]
I'll take a look today (on evening).

**Comment by narrenfrei** [comment]
I've found the cause: https://github.com/google/docsy/blob/003b798c1252004c5c7a2915496b90c78d7a36e2/assets/scss/_nav.scss#L162

I'll prepare a bug fix. Hopefully it's enough to set the ´max-height` for `input:checked ~ ul.foldable` to a very big size - e.g.: `max-height: 10000vmax;`

@dholbach Could you test this simple fix?

**Comment by dholbach** [comment]
This (and setting params.ui.sidebar_menu_truncate) makes it work - thanks a lot!

**Comment by dholbach** [comment]
![Screenshot from 2021-07-06 15-26-59](https://user-images.githubusercontent.com/1346979/124608295-e5e9b680-de6e-11eb-9f93-33fec423a15b.png)

https://github.com/dholbach/new-site now works.

**Comment by dholbach** [comment]
Also [fixes our problem](https://github.com/fluxcd/website/pull/390) on fluxcd.io: 

![](https://user-images.githubusercontent.com/1346979/124612536-b0df6300-de72-11eb-826f-371bb1d5d1c8.png)

**Comment by narrenfrei** [comment]
@LisaFC I'll prepare a PR.

**Comment by scrooks** [comment]
I think this same problem also exists in the right sidebar when there's a long ToC.  Not sure if this fix will fix things over there also...

**Comment by narrenfrei** [comment]
> I think this same problem also exists in the right sidebar when there's a long ToC.  Not sure if this fix will fix things over there also...

Do you have an example for the TOC? Because I think that my fix won't solve an issue in the TOC.

**Comment by scrooks** [comment]
> Do you have an example for the TOC? Because I think that my fix won't solve an issue in the TOC.

I don't, I'm sorry, and I don't have time at the moment to generate one.  I know I made a quick fix for it a while ago using this CSS (which is probably not the right way to do it!):

```css
.td-sidebar-toc {
    height: calc(100vh - 4rem);
}
```

**Comment by dholbach** [comment]
#618 fixed this.
