### ISSUE TITLE
Tabpane not work

### ISSUE THREAD

**Issue by infilos** [google/docsy#617]
I copy the tabpane example code from offical document to local example code, then compile failed:

the copied code:

```
{{< tabpane >}}
{{< tab header="English" >}}
Welcome!
{{< /tab >}}
{{< tab  header="German" lang="de" >}}
Herzlich willkommen!
{{< /tab >}}
{{< tab  header="Swahili" >}}
Karibu sana!
{{< /tab >}}
{{< /tabpane >}}
```

the error:

```
Rebuild failed:

".../docsy-example/content/en/docs/_index.md:16:1": failed to extract shortcode: template for shortcode "tabpane" not found

14
15
16 {{< tabpane >}}
17 {{< tab header="English" >}}
18 Welcome!

hugo v0.84.4+extended darwin/arm64 BuildDate=unknown
```

I have already run command `git submodule update --init --recursive`.

**Comment by infilos** [comment]
I found the local theme doesn't even have the short-code definitions of tab pane and card, so I run `git submodule update --remote --merge`, then everything work as expect.

But I cannot found any document about this.

Please close this.

**Comment by LisaFC** [comment]
So we cover how to update the theme itself in Updating Docsy: https://www.docsy.dev/docs/updating/

As we say in the doc (and as you found), you need to run `git submodule update --remote` to pull the latest version of the theme from our repo.
