### ISSUE TITLE
Docsy sidebar menu tabs into menu items that aren't visible

### ISSUE THREAD

**Issue by alisondy** [google/docsy#621]
Tab navigation focuses on menu items that aren't visible

![ezgif-4-6729f8bcc438](https://user-images.githubusercontent.com/19580905/124749298-f5730900-df1b-11eb-91e5-b54aa7990498.gif)

**Comment by narrenfrei** [comment]
Yeah, you are right. This is because the visibility toggling isn't done by change display to none but by set the max-height to 0.
Set `tabindex="-1"` for the hidden menu items should make it.

I'll take a look.

**Comment by emckean** [comment]
This seems to be fixed in the latest version of Docsy; would you please reopen if that's not the case? Thank you!
