### ISSUE TITLE
Lunr Offline search not available with multiple versions configured 

### ISSUE THREAD

**Issue by at055612** [google/docsy#622]
It seems that when the site is configured with multiple versions (`[[params.versions]]`) the lunr offline search and right hand github links are not available.

I have this problem in the site I am developing but have also recreated it using a vanilla docsy-example.  I did the following:

```bash
git clone https://github.com/google/docsy-example.git
cd docsy-example
git submodule update --init --recursive
git submodule update --remote

docker-compose build
docker-compose run site -v
docker-compose up

# Search fields and github links visible (see first image below)

# edit config.toml (see diff below)

sudo rm -rf ./public
docker-compose run site -v
docker-compose up

# Search fields and github links no longer visible (see second image below)
# No .json file in ./public (see third image below)
```

Please can you let me know if I am doing something wrong with the configuration or whether this is a bug as it appears to be.  This may be related to #154 and #226.  This is a really good Hugo theme by the way, thanks.

The diff for the changes I have made is as follows:

```diff
diff --git a/config.toml b/config.toml
index f0292cb..ab18206 100644
--- a/config.toml
+++ b/config.toml
@@ -115,6 +115,10 @@ version = "0.0"
# point people to the main doc site.
url_latest_version = "https://example.com"

+[[params.versions]]
+  version = "master"
+  url = "https://master.kubeflow.org"
+
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/google/docsy-example"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
@@ -128,13 +132,13 @@ github_project_repo = "https://github.com/google/docsy"
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
-gcs_engine_id = "d72aa9b2712488cc3"
+#gcs_engine_id = "d72aa9b2712488cc3"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
-offlineSearch = false
+offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false
diff --git a/themes/docsy b/themes/docsy
index 62cc3ed..003b798 160000
--- a/themes/docsy
+++ b/themes/docsy
@@ -1 +1 @@
-Subproject commit 62cc3edbea013465179e1ea641d0d0da4fdba6f0
+Subproject commit 003b798c1252004c5c7a2915496b90c78d7a36e2-dirty

```

**Search and github links visible**
![image](https://user-images.githubusercontent.com/22818309/124882196-0bd69e80-dfc8-11eb-9dcc-bc9cb6956623.png)

**Search and github links NOT visible**
![image](https://user-images.githubusercontent.com/22818309/124882318-2ad53080-dfc8-11eb-8f9a-7bba1d10f1bf.png)

**ls of `./public` when versions block in use**
![image](https://user-images.githubusercontent.com/22818309/124883608-691f1f80-dfc9-11eb-9105-08743774db09.png)

**Comment by LisaFC** [comment]
Huh, that *is* odd - the versions params should literally just govern what goes in that drop-down, we don't use them anywhere else (I don't think). Let me take a look....

**Comment by LisaFC** [comment]
Ok, I see what's happened - you've put `[[params.versions]]` in the middle of the site `[params]`, so Hugo doesn't think anything below them is a site parameter any more, including the github repo, enabling offline search, etc.

If you put your version settings below the site params it all works fine, eg:

```
# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

[[params.versions]]
  version = "master"
  url = "https://master.kubeflow.org"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
...
```


.toml syntax is confusing!

**Comment by at055612** [comment]
Apologies.  I thought it must have been some muppetry on my part.  That fixes it.  Not worked much with TOML.  The _Obvious_ in _TOML_ is debatable.

Thanks for looking into it.

**Comment by LisaFC** [comment]
No problem, and glad you like the theme!
