### ISSUE TITLE
Cannot change search (magnifying glass) icon

### ISSUE THREAD

**Issue by arnonzooz** [google/docsy#625]
Hi all,

I'm trying to see where the magnifying glass in the Search input box is defined, but cannot manage to find it. Isn't it a fontawesome icon?

Thanks for your help!

**Comment by LisaFC** [comment]
It's here: https://github.com/google/docsy/blob/master/layouts/partials/search-input.html#L10

It's the HTML entity &#xf002; which is equivalent to fontawesome's fa-search.

**Comment by arnonzooz** [comment]
Thank you. Found it. Closing the issue.
