### ISSUE TITLE
Duplicate horizontal bar at bottom of leaf pages

### ISSUE THREAD

**Issue by thebe14** [google/docsy#627]
If you add the last modified info to the bottom of your pages (_page-meta-lastmod_ partial), then the pages that do not have child pages will end up having two horizontal lines before the last modified information (at the end of the page). The cause is that the (sub)page index (_section-index_ partial) adds a horizontal line even if the pages collection is empty.

**Comment by LisaFC** [comment]
Hmm, that should be easy enough to fix. I'll take a look.

**Comment by thebe14** [comment]
See PR #628
