### ISSUE TITLE
Add support for tabbed content

### ISSUE THREAD

**Issue by thebe14** [google/docsy#629]
Can be used e.g. for instructions on how to install something on multiple platforms, each platform having its own tab. Or for code in multiple language that does the same thing. 

![linux](https://user-images.githubusercontent.com/25453173/125158716-30bb4500-e173-11eb-856b-de4558f3a758.png)
![windows](https://user-images.githubusercontent.com/25453173/125158718-32850880-e173-11eb-950f-6e2053594034.png)

**Comment by honzik20** [comment]
This might be what you're looking for: https://www.docsy.dev/docs/adding-content/shortcodes/#tabbed-panes

**Comment by thebe14** [comment]
That's a good start, yes. Except that will make the entire content of the tab a code snippet. If you want to use it for anything but code, it will not look good.
