### ISSUE TITLE
Bootstrap git submodule v4.5.3, not in sync with partials/scripts.html (still v4.6.0)

### ISSUE THREAD

**Issue by pschrey2** [google/docsy#632]
### Discussed in https://github.com/google/docsy/discussions/631

<div type='discussions-op-text'>

<sup>Originally posted by **pschrey2** July 13, 2021</sup>
Hi, bootstrap seems to be switched back to version 4.5.3 on May 29 with commit c5f1613fb1b163ad4ea18e603fc1915494f4bf49 (see git submodule bootstrap at https://github.com/google/docsy/tree/master/assets/vendor).
Any reason for that?
Regards, Patrik</div>

Happened by mistake during PR #554. Can the /assets/vendor/bootstrap git submodule be refered back to version 4.6.0?
Because now the submodule and https://github.com/google/docsy/blob/master/layouts/partials/scripts.html are not in sync.

The upgrade was done earlier by @deining on April 12 (8b2f695#diff-05e01d0fe33a568f907cb8c03ee25e8cef7221d73f052ac04392232753d25467) plus an SRI hash fix later on April 17.

**Comment by LisaFC** [comment]
Done! (also I hate updating git submodules, it always feels like bomb disposal)
