### ISSUE TITLE
Versions dropdown is missing right margin

### ISSUE THREAD

**Issue by at055612** [google/docsy#633]
When the versions feature is enabled, the versions drop down is butted up against the search input.  It should probably have similar spacing to the top nav bar menu items.

![image](https://user-images.githubusercontent.com/22818309/125623721-17256cd6-bc7d-45dd-90c0-ed62a82660de.png)

A change along these lines is probably needed

```diff
diff --git a/layouts/partials/navbar.html b/layouts/partials/navbar.html
index 8f78291..4436dc0 100644
--- a/layouts/partials/navbar.html
+++ b/layouts/partials/navbar.html
@@ -20,12 +20,12 @@
                        </li>
                        {{ end }}
                        {{ if  .Site.Params.versions }}
-                       <li class="nav-item dropdown d-none d-lg-block">
+                       <li class="nav-item dropdown mr-4 d-none d-lg-block">
                                {{ partial "navbar-version-selector.html" . }}
                        </li>
                        {{ end }}
                        {{ if  (gt (len .Site.Home.Translations) 0) }}
-                       <li class="nav-item dropdown d-none d-lg-block">
+                       <li class="nav-item dropdown mr-4 d-none d-lg-block">
                                {{ partial "navbar-lang-selector.html" . }}
                        </li>
                        {{ end }}
```

![image](https://user-images.githubusercontent.com/22818309/125623865-1ce6d0d9-8485-4361-abb1-dab13398dbc9.png)

**Comment by LisaFC** [comment]
Ooh, that does look better. Let me see how it works in something with a language drop-down as well.

**Comment by at055612** [comment]
On a slightly related note I also made the following change to the search input border colour to make it stand out a little more.  This is dependent on the colour of the nav bar so I am not suggesting you use the same colour in the docsy theme.

Your docsy example site looks like this.  You can only just see the outline of the input field.

![image](https://user-images.githubusercontent.com/22818309/125651547-24c536d3-9322-4dbb-b249-2cdc1b083c19.png)

I added this to my `_styles_project.scss`
```css
.navbar {
  /* Make the search input more visible in the top nav bar */
  .form-control {
    border:1px solid #ffffff8c; 
  }
}
```

See further up for how it now looks on my site.  Front-end is not my strong point, so there may be a better way of making it stand out a bit.

**Comment by LisaFC** [comment]
> Ooh, that does look better. Let me see how it works in something with a language drop-down as well.

This looks better with the language drop-down too. Can you do a PR with your update?

**Comment by at055612** [comment]
yep, will do
