### ISSUE TITLE
huge whitespace in sidebar menus

### ISSUE THREAD

**Issue by pschrey2** [google/docsy#637]
Hi,

I saw by accident very big page files on Kubernetes documentation.
For example https://kubernetes.io/docs/tasks/ is 21850 lines long and the lines 286-20056 are taken for the sidebar menu containing a lot of whitespace (do right-mouse and "view page source").

The root cause are the partials https://github.com/google/docsy/blob/master/layouts/partials/sidebar-tree.html and https://github.com/google/docsy/blob/master/layouts/partials/sidebar.html
Both don't use the "-" in the template parts to remove whitespace as documentated [here](https://gohugo.io/templates/introduction/#whitespace).

I have prepared a Pull request #638 to drastic reduce this whitespace. Validation should be easy, it only adds "-" at most hugo templates and removes other whitespace, to at least solve this on Docsy theme side.
Kubernetes will have to update their project level partial overwrites.

There are other places with extra whitespace but the impact is less, so I have not taken those into account now.

**Comment by LisaFC** [comment]
Thanks for that!

**Comment by pschrey2** [comment]
And thank you @LisaFC  for merging. Can this issue be closed?

**Comment by LisaFC** [comment]
Sure thing!
