### ISSUE TITLE
sidebar_menu_foldable: checkboxes instead of triangles ?

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#641]
I've just enabled the foldable sidebar with `sidebar_menu_foldable = true`, but instead of collapsing triangles, I get checkboxes:

![check-boxes](https://user-images.githubusercontent.com/1607499/126726896-29577cdc-d6e4-4bed-8d98-e1f9746eba1f.png)

Anyone have any ideas why this might be so? This is with the most recent Docsy update (as of yesterday).

**Comment by narrenfrei** [comment]
Can you provide a link?

Do you have project specific Stylesheets? The markup from the foldable menu are checkboxes, which get removed by CSS.

**Comment by Symbolics** [comment]
Here is the [repo ](https://github.com/Lisp-Stat/documentation) and live [site](https://lisp-stat.dev/). I can reliably reproduce this by toggling `sidebar_menu_foldable`. I don't think I'm using any project specific stylesheets; we're not too skilled on the HTML side of things here and wouldn't change CSS unless it was required for some other reason.

**Comment by narrenfrei** [comment]
You have project specific stylesheets in your repo ;-)
look here: https://github.com/Lisp-Stat/documentation/tree/master/assets/scss

Your https://github.com/Lisp-Stat/documentation/blob/a01515a2be206412d6b48c5071f82ef7c77efd46/assets/scss/_nav.scss overwrites the `_nav.scss` from Docsy (including the style infos for the foldable menu - beginning at: https://github.com/google/docsy/blob/0070ccffaed2b88d673e4a01e382720c4fc59f67/assets/scss/_nav.scss#L133)

**Comment by Symbolics** [comment]
Problem fixed after removing `_nav.css`, thank you.
