### ISSUE TITLE
Changes introducing hugo.IsProduction were overwritten

### ISSUE THREAD

**Issue by chalin** [google/docsy#652]
_Originally posted by @chalin in https://github.com/google/docsy/issues/611#issuecomment-895335837_

---

@LisaFC et al.: somehow #540 reverted #413. The latter introduced the use of `hugo.IsProduction`, in replacement of the environment-variable checking code. IMHO, use of `hugo.IsProduction` is the better (if not proper) way to determine the build environment, in particular since the build environment can be specified using the [-e flag][] command line flag.

[-e flag]: https://gohugo.io/commands/hugo/#options

Possibly related: #611
Related: #651

/cc @nate-double-u

**Comment by LisaFC** [comment]
Ahhh, thanks for spotting this. And yes, agreed that hugo.IsProduction is definitely the way to go.

I'll send a mail to the mailing list when we merge/fix this and update the docs, as this will be a breaking change for some users (ie their site will be indexed by default).

**Comment by LisaFC** [comment]
(apologies for late reply, I was on vacation)

**Comment by chalin** [comment]
No worries. I hope that you had a great vacation!
