### ISSUE TITLE
Upgrading docsy gives "error calling where: reflect: call of reflect.Value.Type on zero Value"

### ISSUE THREAD

**Issue by mhansen** [google/docsy#656]
Hi there, on https://gitlab.com/graphviz/graphviz.gitlab.io/, I tried updating the Docsy theme, using
```
git submodule update --remote
```
I now get this error (building on macOS):

```
$ hugo serve
Start building sites … 
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: docs/list.html:21:11: executing "main" at <partial "section-index.html" .>: error calling partial: "/Users/mark/projects/graphviz.gitlab.io/themes/docsy/layouts/partials/section-index.html:5:17": execute of template failed: template: partials/section-index.html:5:17: executing "partials/section-index.html" at <where $pages "Parent.File.UniqueID" "==" $parent.File.UniqueID>: error calling where: reflect: call of reflect.Value.Type on zero Value
Built in 9630 ms
```

it seems to be pointing at Docsy's `partials/section-index.html` line 5 which is: `{{ $pages = (where $pages "Parent.File.UniqueID" "==" $parent.File.UniqueID) }}`.

From https://stackoverflow.com/questions/41995110/panic-reflect-call-of-reflect-value-call-on-zero-value, sounds like someone's trying to use a `reflect.Value` type in Go without first checking if it's nil.

I'm not sure if this is a Hugo problem or a Docsy problem.

**Comment by mhansen** [comment]
Looks like the low-level error comes from here: https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/reflect/value.go;l=1908;drc=f0ff6d4a67ec9a956aa655d487543da034cf576b

**Comment by mhansen** [comment]
Quite a few calls to `reflect.ValueOf(...).Type()` in here: https://github.com/gohugoio/hugo/blob/master/tpl/collections/where.go

**Comment by chrishas35** [comment]
Looks like this is the same I'm running into.  I'll close #659 as a dup and bring my details here... 

> Have my own docs-only site, but have been able to replicate with [gwatts/mostlydocs](https://github.com/gwatts/mostlydocs/) referenced in the [docsy docs](https://github.com/google/docsy/blob/master/userguide/content/en/docs/Adding%20content/content.md#alternative-site-structure).
> 
> On latest the following error is thrown when running `hugo server`:
> 
> ```
> $ hugo server
> Start building sites … 
> Built in 4256 ms
> Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: docs/list.html:21:11: executing "main" at <partial "section-index.html" .>: error calling partial: "/workspaces/mostlydocs/themes/docsy/layouts/partials/section-index.html:5:17": execute of template failed: template: partials/section-index.html:5:17: executing "partials/section-index.html" at <where $pages "Parent.File.UniqueID" "==" $parent.File.UniqueID>: error calling where: reflect: call of reflect.Value.Type on zero Value
> ```
> 
> After reviewing history for [section-index.html](https://github.com/google/docsy/blob/master/layouts/partials/section-index.html), I believe I traced the introduction of the error to merge commit [fbe578e](https://github.com/google/docsy/commit/fbe578e0da4cea0be99bab0178926e5d76387e70) PR #628 as the parent commit, [f85c845](https://github.com/google/docsy/commit/f85c845226f30a4b2a55085d142e96def89e4c3f), does not throw the error.

@mhansen the latest you'll be able to upgrade to is f85c845226f30a4b2a55085d142e96def89e4c3f until resolved.

**Comment by LisaFC** [comment]
Hmmm, didn't spot that one (as it builds fine with that commit and later for both the Docsy docs site and the example site). 

@thebe14, can you revisit that code - I wonder do we need to do a further "does this exist" before using the value.

**Comment by mhansen** [comment]
Thanks. Confirming graphviz docs build now.
