### ISSUE TITLE
'markmap' feature is not working in 'docsy-example'

### ISSUE THREAD

**Issue by amirootyet** [google/docsy#671]
This is a great feature, specially for a documentation platform. However, it is not working in my Docsy project. I cloned the Docsy-example repo and tried there with the same result. Here's how to reproduce the issue:

```
git clone --recurse-submodules --depth 1 https://github.com/google/docsy-example
cd docsy-example
vi content/en/docs/Examples/_index.md
```
I then added the `markmap` [example shown](https://www.docsy.dev/docs/adding-content/lookandfeel/) in documentation to the end of `_index.md`page. Proceeded to save and quit (`:wq`)
Edited the `config.toml` to enable markmap by adding this to the end of `config.toml`

```
[params.markmap]
enable = true
```

```
hugo
hugo serve
```

The `markmap` does not render but shows up as a code block. Not sure what I did incorrectly and I can't find any previous issues around markmap here. Perhaps it's a feature that's not used enough for someone to have noticed so far? Can someone please help?

My hugo and nodeJS:

```
hugo version                                                          
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown

node -v                                       
v14.17.5
```

**Comment by LisaFC** [comment]
OK, it looks like Docsy-example wasn't updated to the latest version of the theme that had the Markmap script enabled.

I'll fix the example project - you can fix your own project by following the "update your theme" instructions here: https://www.docsy.dev/docs/updating/#update-a-docsy-submodule

Thanks for spotting this!
