### ISSUE TITLE
Impossible to include SVG image with imgproc

### ISSUE THREAD

**Issue by antoineozenne** [google/docsy#685]
It seems to be impossible to import a SVG image with imgproc. Here the error when trying:

```console
# hugo server -b http://localhost:1313/
Start building sites … 
hugo v0.88.1+extended linux/amd64 BuildDate=2021-09-04T13:52:13Z
Error: Error building site: "/home/foo/bar/pages/content/fr/links/_index.md:17:1": failed to render shortcode "imgproc": failed to process shortcode: "/home/foo/bar/pages/themes/docsy/layouts/shortcodes/imgproc.html:9:34": execute of template failed: template: shortcodes/imgproc.html:9:34: executing "shortcodes/imgproc.html" at <$original.Fill>: error calling Fill: *resources.genericResource is not an image
Built in 476 ms
```

Did I miss something?

**Comment by LisaFC** [comment]
Unfortunately Hugo image processing (which that shortcode uses) doesn't support processing SVG files - supported types are jpg, png, tif, bmp, gif and webp.

If you want to use SVGs inline in your Markdown I think you need a shortcode using [Hugo's readFile function](https://gohugo.io/functions/readfile/).

Here is a sort of hacky version I put together based on something I found in the Hugo forums (hacky in that there are no divs/styling and the file path is hardcoded):
https://github.com/LisaFC/boing/blob/master/layouts/shortcodes/svg.html

You'd use it in your page like this: `{{< svg "triangle.svg" >}}`

And voila, a triangle: https://tender-beaver-c94732.netlify.app/docs/examples/

**Comment by antoineozenne** [comment]
Thank you @LisaFC!
