### ISSUE TITLE
Link in community_links.html partial should be relative

### ISSUE THREAD

**Issue by markjschreiber** [google/docsy#686]
I think the `href` on line 17 of should not be absolute but rather relative so that it still works when there is a base URL.

I suggest it should be:

`<p>You can find out how to contribute to these docs in our <a href="../docs/contribution-guidelines/">Contribution Guidelines</a>.`

Rather than:

`<p>You can find out how to contribute to these docs in our <a href="/docs/contribution-guidelines/">Contribution Guidelines</a>.`

In it's current form it will link to `localhost:1313/docs/contribution-guidelines/` rather than `localhost:1313/<mybase-url>/docs/contribution-guidelines`

If you think this this correct I can make a pull request to correct this.

**Comment by LisaFC** [comment]
Oh yes, I think you're right! Please do make a pull request.

**Comment by markjschreiber** [comment]
Hi There, I just submitted the PR https://github.com/google/docsy/pull/687

**Comment by LisaFC** [comment]
Fixed in #687
