### ISSUE TITLE
Error building site: POSTCSS: failed to transform "scss/main.css"

### ISSUE THREAD

**Issue by catherinepope** [google/docsy#701]
Hello. Docsy is working fine and looking lovely on my local machine. However, when I deploy to Netlify, I keep getting the following error code. I looked at other issues and ran: _npm install -g postcss-cli_. That made no difference, though. Is there something I'm missing? Thanks so much for your time.

![netlify-error](https://user-images.githubusercontent.com/129828/134207191-dd112beb-9be6-4d90-92a0-a3c557b1dad0.jpg)

**Comment by catherinepope** [comment]
Many thanks for your response, Erin. Yes, I followed the instructions on Netlify deployment. I've just tried reinstalling PostCSS, but am still getting the same error.

**Comment by emckean** [comment]
It might be a problem with autoprefixer ... can you let me know what version of autoprefixer you're using?

**Comment by catherinepope** [comment]
I can't see a version anywhere, Erin. Where do I find that information, please? I installed it via npm today.

**Comment by catherinepope** [comment]
It's 10.3.4. Thank you!

**Comment by emckean** [comment]
I think that might have been a red herring :( 

Another random q: do you have a netlify.toml file? And if you can share your package.json file that might help too :)

**Comment by catherinepope** [comment]
Well, happily, the problem has fixed itself overnight! I received a pull request from Dependabot, bumping the postcss-cli version from 7.1.2 to 10.3.4. Now everything builds and deploys properly. Thanks so much for your support, Erin.
