### ISSUE TITLE
lunr search: text field background fills in after you press enter, causing poor contrast

### ISSUE THREAD

**Issue by mhansen** [google/docsy#718]
To repro, set `offlineSearch = true` in your `config.toml` then try searching, and press enter after entering a search term.

Expected: text box has high contast (maybe staying with a white background?)
Actual: text box has a blue background with black text on it.

![image](https://user-images.githubusercontent.com/105529/136772318-1ee33470-efff-4347-b75a-b55ed25527df.png)

Here's a video:

https://user-images.githubusercontent.com/105529/136772259-13eb5464-c967-4de3-97c3-696256feb5e8.mov

**Comment by mhansen** [comment]
The background colour is set to `#fff` with `.form-control:focus`, and reverts back to `transparent` (set by `.td-search-input`) when it loses focus.

**Comment by LisaFC** [comment]
Huh, that does not look right, thanks for letting us know. @tekezo, you know most about Lunr, can you see what's happening here? I'll play around with it myself as well.

**Comment by tekezo** [comment]
Thank you for feedback!

@LisaFC I fixed this issue at https://github.com/google/docsy/pull/719. Please review the PR.

**Comment by chalin** [comment]
I can see this issue even with `offlineSearch = false`, such as for the Docsy user guide. To reproduce:

 1. Visit any page of https://www.docsy.dev/
 2. Add text to the site-search input
 3. Move focus outside of the input

Here's an example of what you'll see:

> <img width="400" alt="unfocused search input" src="https://user-images.githubusercontent.com/4140793/142295195-ab1c52c9-df27-4251-80f0-b9ffa7b15409.png">

**Comment by mhansen** [comment]
Thank you! Confirming this looks great and high-contrast now with the white-on-accent.

**Comment by chalin** [comment]
Thanks for the feedback @mhansen!
