### ISSUE TITLE
[enhancement] "Create documentation issue" should offer disable config

### ISSUE THREAD

**Issue by jshaughn** [google/docsy#731]
Thanks for Docsy, it's great, we have recently migrated kiali.io to the theme.

For Kiali, we'd prefer to consolidate all issues as "Project" issues, and so we'd either like "Create documentation issue" to act just like "Create project issue", or to not show it at all.   If we disable it today we also lose the "Edit this page" and "Create child page" options, both of which we like.   We'd like to see a config.toml option that could support our situation.

**Comment by LisaFC** [comment]
So a quick project-specific fix would be to create your own version of [/layouts/partials/page-meta-links.html](https://github.com/google/docsy/blob/master/layouts/partials/page-meta-links.html) with lines 39-45 changed to

```
    <a href="{{ $editURL }}" target="_blank"><i class="fa fa-edit fa-fw"></i> {{ T "post_edit_this" }}</a>
    <a href="{{ $newPageURL }}" target="_blank"><i class="fa fa-edit fa-fw"></i> {{ T "post_create_child_page" }}</a>
    {{ if $gh_project_repo }}
      {{ $project_issueURL := printf "%s/issues/new" $gh_project_repo }}
      <a href="{{ $project_issueURL }}" target="_blank"><i class="fab fa-github fa-fw"></i> {{ T "post_create_issue" }}</a>
      <a href="{{ $project_issueURL }}" target="_blank"><i class="fas fa-tasks fa-fw"></i> {{ T "post_create_project_issue" }}</a>
    {{ end }}
```

That would give you both the docs and project links pointing to the same repo url (`$project_issueURL`). 

It's not ideal in that you'll need to manually update the file if we make any improvements to that partial - though as you can see if you look at the file it's full of conditionals so I don't want the theme version to get *too* complicated (especially as you're the first project I've seen who don't want to use the same github_repo for all three doc-related links). I'll see if I can think of anything better, if that will work for you in the meantime. @chalin, any thoughts, as you did the most recent update to the links partial?

**Comment by jshaughn** [comment]
@LisaFC , thanks so much for the detailed workaround.  We may consider it but to be honest, one major goal of migrating to Docsy was to minimize customization and focus on content.  We can probably live with our current workaround, which is to enable Github Issues on our website repo.   If there is a change in the future we would then point our doc issues to our main repo, to consolidate issues in one place.  Again, thanks for looking at this request.

**Comment by LisaFC** [comment]
No problem, if we come up with a better in-theme solution I'll update this issue!

**Comment by chalin** [comment]
I've also come across a situation where I need a bit more control over which repo links are shown. I'll need to give this a bit more thought before I get back to you.

**Comment by chalin** [comment]
@jshaughn, you can hide the create-doc-issue link by adding the following to your project's SCSS, such as `assets/scss/_styles_project.scss`:

```scss
.td-page-meta > a:nth-child(3) { display: none !important; }
```

This isn't a perfect solution, but it should allow you to achieve what you want without having to override any layout files. If you think that this will work for you, let us know.

(I'll still be giving thought to a cleaner, more flexible and less brittle solution.)

**Comment by jshaughn** [comment]
@chalin  I will try this workaround and get back to you, thanks.

**Comment by chalin** [comment]
You can now more easily do this as documented in [/docs/adding-content/lookandfeel/#styles](https://deploy-preview-771--docsydocs.netlify.app/docs/adding-content/repository-links/#disabling-links)

**Comment by jshaughn** [comment]
Great!  Sorry that I have not yet found the time to test the original workaround.

**Comment by chalin** [comment]
No worries. You now have a better solution to try when you're ready. Cheers!
