### ISSUE TITLE
Algolia Search: DocSearch API v3 doesn't seem to have 'inputSelector' any more

### ISSUE THREAD

**Issue by mhansen** [google/docsy#738]
Hi there, I'm trying to add Algolia Docsearch to www.graphviz.org.

The Docsy docs at https://www.docsy.dev/docs/adding-content/navigation/#adding-algolia-docsearch say

> Update the `inputSelector` field in the body end Javascript with the appropriate CSS selector (e.g. `.td-search-input` to use the default CSS from this theme).

I can't find an `inputSelector` option in the Docsearch API v3: https://docsearch.algolia.com/docs/api. It looks like this was a thing for Docsearch API v2: https://docsearch.algolia.com/docs/legacy/dropdown.

The DocSearch API v3 wants you to give a container that they render the searchbox into, it seems.

I'll probably just roll with API v2 for now (so this isn't an urgent issue or anything), just wanted to file it as FYI.

**Comment by insa-k** [comment]
Hey!
Is there some news if and when you would be able to update it?

**Comment by chalin** [comment]
For recent developments regarding this issue, see #845, where most of the discussion is.
