### ISSUE TITLE
Algolia: Search integration only works on full-width searchbox, not on narrow pages

### ISSUE THREAD

**Issue by mhansen** [google/docsy#739]
Hi there, I just integrated Algolia DocSearch v2 on www.graphviz.org, but I'm having some trouble.

The search works for the full-width page, where search is at the top right (note there are search results):

![image](https://user-images.githubusercontent.com/105529/138362211-9084cd02-3122-464e-aa6f-cdee5321135d.png)

But it doesn't work if the page is a little narrower, and the searchbox moves to above the sidenav (note no search results):

![image](https://user-images.githubusercontent.com/105529/138362095-77a24673-b78c-4607-9fb4-e11839b40212.png)

Nor do I get any results for the narrowest width:

![image](https://user-images.githubusercontent.com/105529/138362285-2f686cde-ae6c-4ff2-bcba-0bdaae2db575.png)

And if I press enter it takes me to /?q=attrs, which 404s:

![image](https://user-images.githubusercontent.com/105529/138362389-f39a61f0-4752-45ee-8fc8-121d06cda8a9.png)

Here's my config:

```
<script src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script>
  docsearch({
    // Your Search API Key
		apiKey: '647a549eb545415b94423d1dd2f17c07',
    // The index populated by the DocSearch scraper
		indexName: 'graphviz',
    // Your Algolia Application ID
		appId: 'BH4D9OD16A',
    // Replace inputSelector with a CSS selector
    // matching your search input
    inputSelector: '.td-search-input',
    // Set debug to true to inspect the dropdown
    debug: true,
  });
</script>
```

My guess is the event handlers are only being attached to a single `.td-search-input` element, but we have multiple of them. Let's check:

The full-width searchbox has event listeners:

![image](https://user-images.githubusercontent.com/105529/138362498-1fafb43a-34a7-42b9-b99f-9e6746ffe80b.png)

The medium-width searchbox has no event listeners:

![image](https://user-images.githubusercontent.com/105529/138362566-23f15b9d-5dad-4adf-92f7-8bce81a95150.png)

Nor does the smallest-width searchbox:

![image](https://user-images.githubusercontent.com/105529/138362629-c2407361-cda9-400b-b18e-c348f83af7a4.png)

So I think the practice of having multiple search boxes for responsive design isn't working well with DocSearch. Maybe we need to rethink how this integration works. Possibly we could move to DocSearch v3 at the same time (#738).

https://github.com/algolia/docsearch/issues/230 seems to be the same issue on DocSearch's repo. I'm not clear if https://github.com/algolia/docsearch/issues/230#issuecomment-527347956 means this is doable in v3 or not.

**Comment by mhansen** [comment]
I just realised maybe this is why you encourage setting

```
sidebar_search_disable = true
```

To avoid having multiple search elements.

I set that, and I'm still getting all the search elements in the screenshots above.

**Comment by mhansen** [comment]
The algolia branch of Graphviz is up here: https://gitlab.com/markhnsn/graphviz.gitlab.io/-/commits/algolia if it would help to reproduce.

**Comment by chalin** [comment]
We're migrating to Algolia Search v3 via https://github.com/google/docsy/pull/985, and besides, the Graphviz website seems to be using Lunr now, so I'll close this issue. @mhansen - if you feel that it is still relevant, let us know.
