### ISSUE TITLE
Bug: Markdown Rendering Error

### ISSUE THREAD

**Issue by Xu-Xihe** [google/docsy#748]
When I'm using Markdown to bulid my blogs, somethimes `**xxx**` can't be rendered.
I have found that it will happen when I use a LaTex block or a punctuation near it. 
Just like this one:
[![5O6mVJ.jpg](https://z3.ax1x.com/2021/10/28/5O6mVJ.jpg)](https://imgtu.com/i/5O6mVJ)

**Comment by LisaFC** [comment]
This looks like it was fixed by #790, please reopen if not.
