### ISSUE TITLE
Shallow clone submodules by default

### ISSUE THREAD

**Issue by chalin** [google/docsy#755]
Context:

- #269 
- https://github.com/google/docsy/pull/749#issuecomment-958990607

As I mentioned in https://github.com/google/docsy/pull/749#issuecomment-958990607, I'd vote to merge this change.

To do:

- [x] Add `shallow = true` via #269
- [ ] Update the User Guide, per https://github.com/google/docsy/pull/269#issuecomment-626995225, noting that the extra step is optional.
- [ ] Remove the `--depth 1` from the CI scripts -- assigned @chalin
- [ ] Follow through to make a similar to change to `docsy-example`, per https://github.com/google/docsy/pull/269#issuecomment-626995225

**Comment by chalin** [comment]
From https://github.com/google/docsy/pull/749#issuecomment-958992545:

> For the record: on other projects, I've encountered situations where shallow cloning causes some extra headaches if you try to submit changes to submodules via the submodules themselves. I don't foresee that happening here.

There's an option for ignoring the `shallow` config setting! See [--no-recommend-shallow](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---no-recommend-shallow).

**Comment by LisaFC** [comment]
So I *think* from discussions on #269 and #749 we can merge the change before updating the docs.

Do you have a preference for which of the above PRs (which do the same thing) we merge? :)

**Comment by chalin** [comment]
The general practice I've seen is to merge the earliest of two PRs when they are equivalent.

**Comment by johnpaulett** [comment]
I'm happy to rebase if needed, but #749 effectively already did that.  I won't be offended if my PR isn't the one to get in, as long as I get a smaller checkout, I'm happy!

**Comment by LisaFC** [comment]
Merged the earlier one!

**Comment by gwatts** [comment]
For anyone following along curious about what shallow cloning is, and what other cloning choices there are, I found this Github blog post to be a great read: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

To be clear, while the above post recommends caution against shallow clone in most circumstances, i don't think they intended that to be true for circumstances like this where you're really not working directly with the cloned submodule at all and really do just want the code associated with the submodule's referenced commit.  i.e. i think shallow clones here are a good idea.

People working on updating the Docsy theme itself probably still want a full clone (or one of the other options in the above post).

**Comment by chalin** [comment]
That looks like a great post! Thanks for sharing @gwatts!

**Comment by chalin** [comment]
@johnpaulett - I just tested this and if I exclude the `--depth 1` argument, then I get deep clones of the submodules even with `shallow = true` set. Any idea what might be doing on?

**Comment by ccwienk** [comment]
I would like to state that setting `shallow = true` will break recursive clones if using [Concourse's](https://concourse-ci.org/) [git resource](https://github.com/concourse/git-resource) (concourse's means of interacting with git-repositories), as it currently hard-codes both the `git clone` and `git submodule update` commands, and does not offer a hook for overwriting `shalllow`

**Comment by chalin** [comment]
Thanks for your feedback @ccwienk. This is reason enough for me to drop those config settings -- especially since we'll be dropping the submodules themselves soon (#948).

**Comment by ccwienk** [comment]
@chalin thank you so much for reacting so fast on my feedback

**Comment by chalin** [comment]
> @chalin thank you so much for reacting so fast on my feedback

👍
