### ISSUE TITLE
Add "View page source" repository link

### ISSUE THREAD

**Issue by chalin** [google/docsy#756]
Context: [Repository Links](https://www.docsy.dev/docs/adding-content/repository-links/)

A common workflow that I've encountered is for folks to view a page's source before they decide whether they'd like to submit an edit.

A problem with **Edit this page** is that is forces the user to login _and_ have a fork of the repo before submitting an edit (admittedly, GH will fork the repo for you). IMHO, user's should be forced to login before they can view a page.

**Comment by LisaFC** [comment]
Oh nice idea!

**Comment by petr-stupka** [comment]
Hi, GitHub now have "Web Editor" functionality if you press `.` on the file so you can edit it in VS code web instead of the simple `edit this file` in GitHub UI. However for that the page can not be in edit mode. So another point why not to open edit directly. Thanks!

**Comment by chalin** [comment]
Oh, very cool! Thanks for sharing, I didn't know about the GH web editor @petr-stupka!

Note that users who know about the web editor will be able to use the View link to get to the page and, as you pointed out earlier, drop into the web editor if they so choose. I'd keep the Edit link as is for now (certainly in the scope of this issue).

**Comment by mhansen** [comment]
I think this would be cool too, I'd enable it on the graphviz website.
