### ISSUE TITLE
.-bg-<color> and .-text-<color> not working as expected in forked project

### ISSUE THREAD

**Issue by amirootyet** [google/docsy#764]
I tried the following examples provided on this documentation [page](https://www.docsy.dev/docs/adding-content/lookandfeel/)

```
<div class="-bg-primary p-3 display-4">Background: Primary</div>
<div class="-bg-200 p-3 display-4">Background: Gray 200</div>
```

And

```
<div class="-text-blue pt-3 display-4">Text: Blue</div>
```

They don't work in my project. Nothing shows up -- it's as if those lines aren't there. They do, however, work in `docsy-example` project when I cloned it and tried it there. I don't know what the difference is since I have gone through all SCSS files I could think of and cannot spot the reason.

My project only has 2 override files for SCSS under the project's scss directory:
1. `_nav.scss` - commented a line to remove the search box from top right of navbar
2. `_variables_project.scss` - defined custom primary and secondary color values

Any clues as to why div classes I pointed out above are working when I try `docsy-example` but not in my project? (docsy theme under both project are on the same commit)

The documentation  [page](https://www.docsy.dev/docs/adding-content/lookandfeel/) says "However, we have added some color state CSS classes that can be useful..." but doesn't say _where_. Any ideas why these divs are not working for my project? Sorry if this is obvious (I'm new to Bootstrap4).

**Comment by LisaFC** [comment]
Can you have a look in dev tools in Chrome (if you're using it) - I have it working (but in a Docsy-example copy) and this is what I see when I have the element selected.
![Screen_Shot_2021-11-12_at_5_37_37_PM](https://user-images.githubusercontent.com/10744406/141510918-379baa74-cdba-4862-be06-64230d3e516a.png)

You can see the various Docsy scss files that the colour, padding, etc. comes from (_colors.scss, _spacing.scss...).

Is the div element there at all?

I'll see if I can reproduce the problem by poking at it a bit more.

**Comment by amirootyet** [comment]
thank you for looking into this!

When I "inspect" around the area, it shows me "raw HTML omitted" under the `<h1>` header (where I've placed those divs)

![image](https://user-images.githubusercontent.com/46239148/141512050-5f8716a8-d595-40a1-9bdf-1b5b56c08d13.png)


Further, looking at Styles, I notice that your version is loading `_colors.scss` and `_type.scss` and mine is not:

![image](https://user-images.githubusercontent.com/46239148/141512353-02e784e0-e657-441d-a3eb-48acc6ebadd8.png)

Mine only seems to load:
 - `_content.scss`
 - `_reboot.scss`
 - `_root.scss`

I'm surprised since I didn't think I changed anything in my project that would cause the other SCSS files to not load. Any ideas why `_colors.scss` and `_type.scss` is not loading at all?

**Comment by LisaFC** [comment]
AHA! Now I think I know what's going on. 

By default , Goldmark (which is the current default Hugo Markdown parser) runs in "safe" mode, which strips any non-Markdown content (ie raw HTML like <div> elements) from your generated pages. If you update your config.toml you can use HTML elements.

```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

**Comment by amirootyet** [comment]
thank you @LisaFC! that worked, I was using this alternate structure in my `config.toml` which wasn't working

```
# Code highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
# pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
```

appreciate you taking the time to look at it!
