### ISSUE TITLE
userguide/content/en/docs: rename mixed-case directory names and names containing spaces

### ISSUE THREAD

**Issue by chalin** [google/docsy#770]
It's usually a good idea to avoid mixed-case directory names and names containing spaces for content sections (or just in general for code or doc related projecqts). All of the directories under https://github.com/google/docsy/tree/master/userguide/content/en/docs fall into this category.

I propose that we rename these to correspond to the section-path names used by the deployed site. For example, rename

- `userguide/content/en/docs/Adding content` to 
- `userguide/content/en/docs/adding-content`, which corresponds to <https://www.docsy.dev/docs/adding-content/>

Thoughts @emckean @LisaFC?

- [x] Adding content - #1129
- [x] Get started - #1118

**Comment by emckean** [comment]
SGTM!
