### ISSUE TITLE
Github repo links presume a language even when none present

### ISSUE THREAD

**Issue by j00bar** [google/docsy#775]
Howdy!

I have a Docsy-themed project that is not and never will be translated. Our site index is `/content/_index.md` and no subpath of `/content` has a language identifier.

With the "View page source", "Edit this page", etc. links in the upper right of each page, however, the link is sending users to `/content/en/_index.md`, which does not exist.

Docsy should link to the actual proper source when no language codes are used.

Thanks!

**Comment by emckean** [comment]
Hi, this is something you should be able to configure yourself. :) Check out this Hugo documentation: https://discourse.gohugo.io/t/how-to-use-a-single-language-in-a-multilingual-theme/33622/2

You probably want to look into changing these settings in your config.toml, try removing the 'en' and setting defaultContentLanguageInSubdir to false?
````
# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
````

**Comment by vthaker-blu** [comment]
The settings doesn't seem to be working. If I set the values as follows

```
# Language settings
contentDir = "content"
defaultContentLanguage = "something"
defaultContentLanguageInSubdir = false
```

The resulted url becomes `.../content/something/docs..`

However if I set it to empty it still uses `en` as default

```
# Language settings
contentDir = "content"
defaultContentLanguage = ""
defaultContentLanguageInSubdir = false
```

The resulted url is `.../content/en/docs...`

It seems that it is checking if the value is empty and replacing it with `en`. I cannot find any workaround for it. Can you please help me.

**Comment by emckean** [comment]
It looks like you don't need either of the defaultContent* settings according to this (https://discourse.gohugo.io/t/how-to-use-a-single-language-in-a-multilingual-theme/33622/3)
