### ISSUE TITLE
Show breadcrumbs on mobile

### ISSUE THREAD

**Issue by chalin** [google/docsy#780]
I'm not sure if there was a reason to hide breadcrumbs on narrow displays. I'd argue that the navigational benefits of breadcrumbs can be even more useful on mobile, and they don't have (IMHO) a negative impact on the page display. Here's an example of a deeply nested page:

> <img src="https://user-images.githubusercontent.com/4140793/143495303-89c17717-9087-4739-b7f5-c894e0b84998.png" width=300>

This looks perfectly fine to me.

Thoughts @LisaFC @emckean?

**Comment by chalin** [comment]
Related: https://github.com/etcd-io/website/issues/498

**Comment by LisaFC** [comment]
Hmm, I'm not sure why we didn't show them originally! Let me have a quick dig around in case there was some issue with it, but otherwise I think adding them in works well.

**Comment by LisaFC** [comment]
No, no issue, and I agree with you that they're useful for context-setting when you can't see a nav. I wonder is it something people might like to be able to switch off for mobile for very deeply nested sites (or will just turning off breadcrumb navigation entirely be enough for that, which we already offer)?

**Comment by chalin** [comment]
> No, no issue, and I agree with you that they're useful for context-setting when you can't see a nav.

Great.

> I wonder is it something people might like to be able to switch off for mobile for very deeply nested sites (or will just turning off breadcrumb navigation entirely be enough for that, which we already offer)?

With #784, breadcrumbs can be turned off at any breakpoint, e.g.:

```scss
@include media-breakpoint-down(sm) {
  .td-breadcrumbs { display: none !important; }
}
```
