### ISSUE TITLE
Support hiding single/root-page breadcrumbs

### ISSUE THREAD

**Issue by chalin** [google/docsy#781]
Breadcrumbs on the root page just use up page real estate without adding any benefits:

> <img src="https://user-images.githubusercontent.com/4140793/143495583-b5faf2bc-a06a-47ce-8569-18eb2cb645ad.png" width=300>

One might argue uniformity of page design, but not all site pages have breadcrumbs anyway.

**Comment by chalin** [comment]
At a minimum, this should be configurable, if only via styling. If/once #784 is merged, I'll show you what I have in mind.

**Comment by LisaFC** [comment]
Yep, that makes sense to me.
