### ISSUE TITLE
Update to Mermaid 8.13.4

### ISSUE THREAD

**Issue by kimberleybrown** [google/docsy#787]
Hello,

I'm having an issue implementing the use of 'actors' in the Mermaid sequence diagrams. 

Generating their example code :

```
sequenceDiagram
    actor Alice
    actor Bob
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice
```
    

Results in the following error:
    
<img width="323" alt="mermaid" src="https://user-images.githubusercontent.com/25205867/143948227-358fde6d-91f4-431a-bc9d-1fd14b394089.png">

It appears from their releases in the 8.12.xx look at bug fixes for this, however Docsy is pulling in 8.11.2 in scripts.html partial.

Thank you.

**Comment by LisaFC** [comment]
That should be fixed by #790, can you check that it's resolved your problem?
