### ISSUE TITLE
Bootstrap: submodule and script are out of sync

### ISSUE THREAD

**Issue by deining** [google/docsy#793]
I just realized that with 498b85eb899c12 applied (#790), now the `bootstrap` submodule and https://github.com/google/docsy/blob/master/layouts/partials/scripts.html are not in sync any more (script: `v4.6.1`, repo: `v4.6.0`). This was an issue in the past (#632), and I want to avoid any confusion here. Therefore I prepared PR #795 which updates the `bootstrap` submodule to version `4.6.1`.

_Additional change:_ Since bootstrap 5 is out now, I add the branch `v4-dev` to `.gitmodules`:

**.gitmodules, amended:**

```
[submodule "assets/vendor/bootstrap"]
	path = assets/vendor/bootstrap
	url = https://github.com/twbs/bootstrap.git
	shallow = true
	branch = v4-dev
```

And while dealing with submodules, I also brought submodule `Font-Awesome`, which was at FortAwesome/Font-Awesome@fcec2d1b01ff069ac10500ac42e4478d20d21f4c  (translates to `Release 5.15.2`), to its latest stable version `Release 5.15.4` ( https://github.com/FortAwesome/Font-Awesome/commit/7d3d774145ac38663f6d1effc6def0334b68ab7e).
Thanks for considering my PR.

**Comment by LisaFC** [comment]
Well spotted, I'll take a look.

**Comment by deining** [comment]
Thanks for merging my PR!
