### ISSUE TITLE
Missing SCSS file

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#80]
When I tried to update to the latest version of Docsy, I got the following error when I tried to run `hugo server`:

`ERROR <date> error: failed to transform resource: SCSS processing failed: file "stdin", line 27, col 1: File to import not found or unreadable: section-index.`

It looks to me like section-index.scss is in the wrong directory for the import statement in `main.scss` to work:

```css
@import "section-index"; 
```

section-index is currently under the assets directory, while it looks like it should be under assets/scss

**Comment by LisaFC** [comment]
Argh, well spotted, I moved it from an override and obviously moved it to the wrong place.
