### ISSUE TITLE
executing "partials/breadcrumb.html" at <.Parent.IsHome>: nil pointer evaluating page.Page.IsHome

### ISSUE THREAD

**Issue by mhansen** [google/docsy#804]
Hi there, on https://gitlab.com/graphviz/graphviz.gitlab.io/, updating to the latest Docsy, I get this error:

```
git clone https://gitlab.com/graphviz/graphviz.gitlab.io.git
cd graphviz.gitlab.io
git submodule update --remote
hugo serve
Start building sites … 
hugo v0.89.4+extended darwin/amd64 BuildDate=unknown
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: docs/list.html:23:62: executing "docs/list.html" at <partial "breadcrumb.html" .>: error calling partial: "/Users/mark/projects/graphviz.gitlab.io/themes/docsy/layouts/partials/breadcrumb.html:2:18": execute of template failed: template: partials/breadcrumb.html:2:18: executing "partials/breadcrumb.html" at <.Parent.IsHome>: nil pointer evaluating page.Page.IsHome
```

Looks like we're trying to read `Parent.IsHome` in `breadcrumb.html` but not every page has a `.Parent`. 

https://github.com/google/docsy/blob/e7fd4d8c266182f28123364e0e40c882047ff4da/layouts/partials/breadcrumb.html#L2

In particular, looks like the `home` page doesn't have a parent.

Maybe this is specific to sites that use the `docs` layout for their root?

Looks like @chalin (tagging as FYI) updated breadcrumbs.html 7 days ago in https://github.com/google/docsy/pull/786.

**Comment by mhansen** [comment]
I would guess the fix here would be to somehow check if `.Parent` is `nil` before reading its fields. I forgot how to do this in hugo, is it using `{{ with .Parent }}` and that section only executes if Parent is non-nil?

**Comment by di9383** [comment]
I'm also getting this error when trying to render Docs only structure from here with the latest Docsy theme version
https://github.com/LisaFC/justdocs

**Comment by chalin** [comment]
Thanks for reporting the issue and sorry for the NPE; I'll be looking into this by tomorrow at the latest.

**Comment by chalin** [comment]
@mhansen @di9383 - if you could confirm whether this works for you, that would be grand.

**Comment by mhansen** [comment]
Thank you, I can confirm this works for me! Looks good

**Comment by chalin** [comment]
Great, thanks!

**Comment by di9383** [comment]
Works for me too, thanks!
