### ISSUE TITLE
failed to transform json/offline-search-index.json (json/offline-search-index.json:5: unclosed action)

### ISSUE THREAD

**Issue by johansenha** [google/docsy#808]
In a wsl2 environment I cannot built hugo with docsy addon due to the following error

```
Built in 541 ms
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "json/offline-search-index.json" (application/json): failed to parse Resource "json/offline-search-index.json" as Template:: template: json/offline-search-index.json:5: unclosed action
```
We are using exactly the version from docsy master branch. 

Anybody around with the same issue?

**Comment by LisaFC** [comment]
Huh, we had this problem before (#705) and it looked like it was fixed - can you check what version of Hugo you're using?

**Comment by johansenha** [comment]
Exactly. Sorry for that
