### ISSUE TITLE
Feature request: support gif as featured-background

### ISSUE THREAD

**Issue by spacefan** [google/docsy#817]
Is there possible to let docsy support gif format of `featured-background`?

**Comment by LisaFC** [comment]
You should be able to use a .gif as your featured-background, yes - Hugo's image processor supports bmp, gif, jpeg, jpg, png, tif, tiff, and webp

Let me know if it doesn't work and I'll do some experimenting.

**Comment by spacefan** [comment]
Yes, it doesn't work. When i use `featured-background.gif`, the animation cannot be played.

**Comment by LisaFC** [comment]
Ah right - the image processor (which we use for resizing etc.) doesn't currently support animated gifs. There's an open issue for Hugo here: https://github.com/gohugoio/hugo/issues/5030

(one comment on the issue suggests that animated PNG files might work, if you convert your file?)

**Comment by spacefan** [comment]
> Ah right - the image processor (which we use for resizing etc.) doesn't currently support animated gifs. There's an open issue for Hugo here: [gohugoio/hugo#5030](https://github.com/gohugoio/hugo/issues/5030)
> 
> (one comment on the issue suggests that animated PNG files might work, if you convert your file?)

APNG unfunctional

**Comment by LisaFC** [comment]
Right, I wasn't sure if it would work. You may need to add a custom version of the cover shortcode to handle gifs differently, as suggested in that Hugo issue (or wait until it's fixed in Hugo).

**Comment by spacefan** [comment]
> Right, I wasn't sure if it would work. You may need to add a custom version of the cover shortcode to handle gifs differently, as suggested in that Hugo issue (or wait until it's fixed in Hugo).

Ok, i'll try to address this problem.

**Comment by LisaFC** [comment]
Underlying Hugo issue seems to have been fixed so I'm closing this.
