### ISSUE TITLE
Search not activated

### ISSUE THREAD

**Issue by nauvane** [google/docsy#825]
I've been unable to activate search, having tried several options: no search box appears on the page. I've reinstalled the theme and updated, having had the same problem with a previous installation. Any enlightenment gratefully received.

**Code**
https://github.com/nauvane/babelish 

**Site**
https://www.babelish.ie/

**Comment by LisaFC** [comment]
Ok, I'll take a look - which search option are you trying to use (Google, Lunr, or Algolia)?

**Comment by nauvane** [comment]
Many thanks. Google. I've tried to follow the guidance here:

https://www.docsy.dev/docs/adding-content/navigation/#configure-search-with-a-google-custom-search-engine 

Search page seems to be present:

https://www.babelish.ie/search/?q=unicode

**Comment by LisaFC** [comment]
Aha, found it! (I think)

You're missing/have moved a `[params]` in your config file - if you look at the config file for the Docsy user guide all the general site parameters are under `[params]` ([here](https://github.com/google/docsy/blob/master/userguide/config.toml#L96)), then more specific parameters are under `[params.ui]`, etc.  At the moment all your search settings aren't under anything and hence Hugo is ignoring them, if you move them down to where the `[params]` section is (or move it back up) you should get your search box.

a)TOML is weird, b)nice to see a fellow Irish/Ireland-based Docsy community member!
