### ISSUE TITLE
Right hand TOC sidebar not using full screen height

### ISSUE THREAD

**Issue by at055612** [google/docsy#827]
As you can see in this screen grab (of the bottom right corner of the screen) the right hand TOC sidebar is not using all the available screen when not scrolled to the bottom, so the vertical divider is short of the bottom.

![image](https://user-images.githubusercontent.com/22818309/149137480-e9b39181-40dd-4d0a-85e5-39887f29b22a.png)

If you scroll all the way down it is fine as the footer takes up the space. 

![image](https://user-images.githubusercontent.com/22818309/149137684-7373b979-7aa6-4ddd-b5de-9b8b34ec8e72.png)

Will raise a PR for the fix.

**Comment by LisaFC** [comment]
Oh well spotted! Not sure how that happened...

**Comment by LisaFC** [comment]
Actually I think I do know how it happened - we initially didn't have nearly as many additional repo and print options at the top, now that they're there they take up a lot of sidebar real estate.

One thing I have noticed in your preview is that using the full height does make it look quite different on long pages with a lot of headings (but maybe that's not a bad thing?)
https://deploy-preview-828--docsydocs.netlify.app/docs/adding-content/navigation/

Anyone else have thoughts? @narrenfrei?

**Comment by chalin** [comment]
> One thing I have noticed in your preview is that using the full height does make it look quite different on long pages with a lot of headings (but maybe that's not a bad thing?)

It does look different, but I feel that it now looks correct IMHO.

**Comment by chalin** [comment]
@LisaFC - the fix LGTM. Shall I merge or do you want to do it?

**Comment by LisaFC** [comment]
Merge away!
