### ISSUE TITLE
Docker container error 255

### ISSUE THREAD

**Issue by ivancheban** [google/docsy#834]
I follow the steps [here](https://www.docsy.dev/docs/getting-started/quickstart-docker/). I get 255 error when I run docker-compose up.

![image](https://user-images.githubusercontent.com/47241364/149636171-6b448716-29db-49de-8a29-6273a78db47b.png)

**Comment by deining** [comment]
Inside your `config.toml, identify the following line:

```
theme = ["docsy"]
```

Remove this line and replace it with the code block given below:

```
[module]
path = "docsy"
```

Does this make the error go away?

**Comment by ivancheban** [comment]
Still got the error.

![image](https://user-images.githubusercontent.com/47241364/149655415-6c1ee6b5-a2b4-4c59-9dfa-980d047c2814.png)

**Comment by LisaFC** [comment]
@geriom can you see any problems there (other than the module update related issues)?

**Comment by deining** [comment]
The error message is:

```
Error: from config: failed to resolve output format "print" from site config
```

So that seem identical to what @nathlaroche reported [here](https://github.com/google/docsy/discussions/535#discussioncomment-1993300). We can't apply the workaround proposed by her since in this case we are dealing with an automated build.

**Comment by geriom** [comment]
So this error was related to the Docsy-as-a-module changes. Is this working correctly now?
