### ISSUE TITLE
docsy userguide: warning message when building with hugo 0.92.0 

### ISSUE THREAD

**Issue by deining** [google/docsy#835]
Excerpt from the netlify build log when building docsy userguide with latest hugo version 0.92.0

```
10:19:03 PM: hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
10:19:04 PM: WARN 2022/01/15 21:19:04 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct simlar to the below:
10:19:04 PM:   {{ $path := "" }}
10:19:04 PM:   {{ with .File }}
10:19:04 PM: 	{{ $path = .Path }}
10:19:04 PM:   {{ else }}
10:19:04 PM: 	{{ $path = .Path }}
10:19:04 PM:   {{ end }}
10:19:04 PM: Re-run Hugo with the flag --panicOnWarning to get a better error message.
10:19:06 PM:                    | EN
10:19:06 PM: -------------------+-----
10:19:06 PM:   Pages            | 74
10:19:06 PM:   Paginator pages  |  0
10:19:06 PM:   Non-page files   |  4
10:19:06 PM:   Static files     | 48
10:19:06 PM:   Processed images |  5
10:19:06 PM:   Aliases          |  0
10:19:06 PM:   Sitemaps         |  1
10:19:06 PM:   Cleaned          |  0
10:19:06 PM: Total in 18114 ms
```

We should identify the offending source file and fix it so that the warning disappears.
Unfortunately, flag `--panicOnWarning` is broken which makes it harder to identify this file.

**Comment by LisaFC** [comment]
I'll see if I can find it (also I bet if this is a new warning it's hit lots of other Hugo sites too so might get clues from other people's issues)

**Comment by LisaFC** [comment]
It looks like it's the partial with the GitHub links: https://github.com/google/docsy/blob/master/layouts/partials/page-meta-links.html

Let me see if I can figure out what bep means in the release notes about how to rewrite it....

**Comment by chalin** [comment]
Yes, that's were it's coming from. I'll be fixing this for another project (https://github.com/open-telemetry/opentelemetry.io/issues/1047), and will be glad to port the solution here if you'd like @LisaFC.
