### ISSUE TITLE
Error: module "github.com/FortAwesome/Font-Awesome" not found; 

### ISSUE THREAD

**Issue by strattonbrazil** [google/docsy#836]
I'm very new to hugo. I'm running hugo 0.92.0 and installed docsy as a submodule in the themes directory. When running most hugo commands I get an error about _Font-Awesome_ that seems to prevent any progress. It looks like a missing dependency, but I don't see any additional requirements called out in the docs. 

```
$ hugo server
Error: module "github.com/FortAwesome/Font-Awesome" not found; either add it as a Hugo Module or store it in "/home/user/Public/test/themes".: module does not exist
```

**Comment by deining** [comment]
Most likely this is due to errors introduced in #801. I just submitted a PR that addresses these errors.

Meanwhile you can work around this. Inside your `config.toml`, identify the following line:

```
theme = ["docsy"]
```

Remove this line and replace it with the settings given in the code box below:

```
[module]
replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
[[module.imports]]
path = "docsy"
```

Does this solve your issue?

**Comment by strattonbrazil** [comment]
I'll give it a shot. Thanks.

**Comment by LisaFC** [comment]
This should be fixed in #837

**Comment by iamsalmakolkari** [comment]
> Most likely this is due to errors introduced in #801. I just submitted a PR that addresses these errors.
> 
> Meanwhile you can work around this. Inside your `config.toml`, identify the following line:
> 
> ```
> theme = ["docsy"]
> ```
> 
> Remove this line and replace it with the settings given in the code box below:
> 
> ```
> [module]
> replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
> [[module.imports]]
> path = "docsy"
> ```
> 
> Does this solve your issue?

This resolved my issue. Thanks!!

**Comment by strattonbrazil** [comment]
That resolved it for me as well. Thanks! 

Is this placeholder code and eventually using the _theme_ attribute will work or is this the new format going forward?

**Comment by amirootyet** [comment]
I too had this error after updating Docsy submodule:

```
From https://github.com/google/docsy
   c9e8363..b6af369  master     -> origin/master
Submodule path 'themes/docsy': checked out 'b6af3699c65dd089f453700bee858c1de7d73dd7'
```

I tried to fix it using the advice by @strattonbrazil. However, I now have an issue where running the server now doesn't default to the `/en` (English) at the homepage. My documents are stored under `content/en/` and the following setting in my `config.toml` used to ensure that it defaults to English:

```
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
```

Any solutions for this? I would like the `localhost:1313` to treat the `content/en/` as the `contentDir`.

**Comment by chalin** [comment]
Can this issue be closed? 

@amirootyet, I _think_ that you're hitting the same problem I did. Can you try the solution documented here: https://discourse.gohugo.io/t/content-mount-problem-for-single-language-multilingual-site/37215/8?u=chalin, that is:

- Delete the `contentDir` entry from your config
- Add the following config:
  ```toml
  [[module.mounts]]
  source = "content/en"
  target = "content"
  ```

**Comment by chalin** [comment]
Closing. Create a new issue if the problem persists.
