### ISSUE TITLE
Issue connecting to hugo server. 

### ISSUE THREAD

**Issue by SamFlexicAgency** [google/docsy#854]
when using the command to open the localhost, I keep getting this error: Error: module "github.com/FortAwesome/Font-Awesome" not found; either add it as a Hugo Module or store it in "/desktop/clearmatics/docsy-theme/themes".: module does not exist. 
What is the best way to get around this?

**Comment by deining** [comment]
This is most likely related to #848. I'm just at the moment preparing #852, which will resolve this issue.

**Comment by chalin** [comment]
Can this be closed?

**Comment by deining** [comment]
Module implementation was imrpoved meanwhile, closing this ticket now. If the problem persists, feel free to reopen or address any other issues in a new ticket.
