### ISSUE TITLE
Font Awesome static files seem 3 years old?

### ISSUE THREAD

**Issue by hugonijmek** [google/docsy#872]
Good day to whoever reads this. I was trying to load the fab fa-discord icon from Font Awesome. However I was greeted with the old discord logo. I checked which logo they supplied and since the latest version it should be the new logo. So to be sure I updated the font awesome sub module but still got the old discord logo showing up. So I dug a bit deeper and at the moment I’m thinking it’s caused by the webfonts folder in the static folder that seems to have been updated 3 years ago for the last time. I also noticed these files don’t get updated when we bump the font awesome package. So 2 questions;

1. Should I manually update the files in the webfonts folder to be able to use the latest font awesome icons?
2. Should we think of a way to automatically update these files on a version bump?

**Comment by LisaFC** [comment]
Huh, that's strange - I didn't set up the original FontAwesome integration so I'm not sure why that static directory is there. Let me investigate.

**Comment by chalin** [comment]
FYI, the following PR proposed that we drop the webfonts. WDYT?

- #1164

Also related is:

- #1102
