### ISSUE TITLE
Docker Quickstart

### ISSUE THREAD

**Issue by eljessi** [google/docsy#874]
Test!

**Comment by davidhankinson** [comment]
I get the following when running docker build:

site_1  | Start building sites … 
site_1  | hugo v0.92.1-85E2E862 linux/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
site_1  | Error: Error building site: "/src/content/en/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
site_1  | Built in 23 ms
tech-blog_site_1 exited with code 255

**Comment by davidhankinson** [comment]
hello,  
I get the following issue when running docker up --build


Attaching to tech-blog_site_1
site_1  | Start building sites … 
site_1  | hugo v0.92.1-85E2E862+extended linux/amd64 BuildDate=2022-01-28T06:12:53z VendorInfo=hugoguru
site_1  | Built in 339 ms
site_1  | Error: Error building site: "/src/content/no/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
tech-blog_site_1 exited with code 255

**Comment by davidhankinson** [comment]
Attempted to fix with:

git submodule update --init --recursive

but there's no .git folder

```
Step 3/3 : RUN git submodule update --init --recursive
 ---> Running in 2d7823f4d6ab
fatal: not a git repository (or any of the parent directories): .git
ERROR: Service 'site' failed to build: The command '/bin/sh -c git submodule update --init --recursive' returned a non-zero code: 128
```
