### ISSUE TITLE
Documentation issues vs project issues

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#88]
Currently Docsy includes two links in the right-hand navigation (table of contents) to encourage open source contributions:

- Edit this page
- Create issue

Both of these links are configured using the `github_repo` site param in config.toml.

Arguably, 'Create issue' is somewhat ambiguous from a UX perspective, as without clicking on the link, it's not clear if the relates to creating a documentation / site issue, or a project issue. Many / most open source projects using Docsy will manage documentation in a dedicated git repo.

I propose to add a link to the open source contribution actions to encourage and make it clearer for contributors to add both project and documentation issues:

- Edit this page
- Create documentation issue
- Create project issue

I propose to keep the the `github_repo` site param for the documentation repo (so as not to impact existing sites) and add a site param `github_project_repo` (or similar) to configure an optional link to add issues to the project repo.

Here's an illustration of what this might look like:

<img width="279" alt="Screen Shot 2019-06-12 at 1 16 54 PM" src="https://user-images.githubusercontent.com/6339099/59351310-02f63e80-8d16-11e9-8f9b-6ba738d2d692.png">

I already have this working for my project, so it's fairly straightforward to contribute to Docsy. If there's enthusiasm for this proposal then I'm happy to create a PR to propose the changes myself.

**Comment by rionam** [comment]
I think this is a  good idea. We made a similar clarification for g3doc,
because of similar confusion.

**Comment by LisaFC** [comment]
Ooh I like it.

**Comment by LisaFC** [comment]
...and by that I mean I'd love you to implement it! :)

**Comment by sharifsalah** [comment]
Thanks both! I will send a PR in the next few days.

**Comment by sharifsalah** [comment]
Fixed in https://github.com/google/docsy/pull/90
