### ISSUE TITLE
Restore latest bootstrap version v4.6.1

### ISSUE THREAD

**Issue by deining** [google/docsy#880]
With #800, submodule bootstrap was set back to `v4.6.0`, while we were at latest current version `v4.6.1` already. As stated in this [comment](https://github.com/google/docsy/pull/800#issuecomment-1026657509) this change was done inadvertently, so we should restore latest version `v4.6.1` of bootstrap.

**Comment by chalin** [comment]
Thanks for noticing and filing an issue @deining.
