### ISSUE TITLE
How to use the /docs as homepage?

### ISSUE THREAD

**Issue by leoplct** [google/docsy#891]
Currently my documentation is at /docs but I want to have it as a landing page at /.
I have tried to move the entire /docs folder to / but I see a blank page with a top nav bar.

This is the content/_index.md
```
---
title: "Guides"
linkTitle: "Guides"
weight: 10
menu:
  main:
    weight: 10
cascade:
-type: docs
---
Here list of guides table of contents
```

**Comment by gwatts** [comment]
I had the same question some time back and created a "mostly docs" example/template repo that should help you out, I think: https://github.com/gwatts/mostlydocs

**Comment by leoplct** [comment]
Thank you. I was still having some issue but I solved adding this:

**netlify.toml**

```
[[redirects]]
  from = "/"
  to = "/docs"
  status = 301
  force = true
```
