### ISSUE TITLE
Finalize and add logo

### ISSUE THREAD

**Issue by jaredbhatti** [google/docsy#9]
Create, finalize, and add logo to Docsy.

**Comment by chenopis** [comment]
The logo is done.

[Docsy_BrandGuidelines.pdf](https://github.com/google/docsy/files/2846212/Docsy_BrandGuidelines.pdf)

![docsy_logo_maingrey_300ppi](https://user-images.githubusercontent.com/24798125/52495768-8d6f3b80-2b86-11e9-80d6-ca444b75963f.png)
![docsy_logo_mainwhite_300ppi](https://user-images.githubusercontent.com/24798125/52495795-96f8a380-2b86-11e9-9c32-614afc5eee87.png)
![docsy_logo_secondarygrey_300ppi](https://user-images.githubusercontent.com/24798125/52495824-a546bf80-2b86-11e9-9a5b-eebdd2f70ce0.png)
![docsy_logo_secondarywhite_300ppi](https://user-images.githubusercontent.com/24798125/52495836-abd53700-2b86-11e9-8e68-554340aa69fc.png)

**Comment by chenopis** [comment]
Done. The logo can be found here: https://github.com/google/docsy/tree/master/assets/icons

**Comment by rionam** [comment]
Yaaas
