### ISSUE TITLE
Repo HEAD: deploy on netlify fails

### ISSUE THREAD

**Issue by deining** [google/docsy#900]
As can be seen [here](https://app.netlify.com/sites/docsydocs/deploys), last 4 netlify deploys of the user guide failed:

Branch `master`:

438b56d702e57bffa7626e5ea739f377b6837469: deploy fails
eb4fcb062ac6f344d80169791d4593ffc4c6f615: last successful deploy

**Comment by chalin** [comment]
Yes, my bad! Fixed by #902.
