### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by chalin** [google/docsy#914]
@deining, can any of the following branches be deleted now that #871 has been merged?

> <img width="752" alt="image" src="https://user-images.githubusercontent.com/4140793/156885040-3b28f420-a4ed-4889-ba95-8a311eb7261b.png">

**Comment by deining** [comment]
> @deining, can any of the following branches be deleted?

Yes, all 4 branches are obsolete now and can be deleted. I don't have permission to do so, so @LisaFC could you delete them, pleaseß

**Comment by chalin** [comment]
@deining - can you try again? I've updated the branch protection rules (as @LisaFC and I had agreed to out-of-band) to apply to the default branch only.

**Comment by deining** [comment]
> @deining - can you try again

Thanks for your intervention, I could now delete all 4 obsolete branches. Closing this issue now.
