### ISSUE TITLE
Release cleanup: drop 0.1.0, and create pre-release 0.2.0-pre

### ISSUE THREAD

**Issue by chalin** [google/docsy#934]
As decided at 2022-03-14 PSC meeting:

- [x] Delete the v0.1.0 _release_, it was only meant to be a tag, not a release
- [x] Publish a first pre-release of 0.2.0-pre at HEAD
- [x] Delete https://github.com/google/docsy/releases/tag/v0.2.0-pre
- ~Delete https://github.com/google/docsy/releases/tag/dependencies%2Fv0.2.0-pre~ -- see https://github.com/google/docsy/issues/934#issuecomment-1086644507
- ~Optional: create a 0.1.0 tag, and consider dropping the v0.1.0 tag?~ Keeping it for now, for reasons similar to those given in https://github.com/google/docsy/issues/934#issuecomment-1086644507

**Comment by chalin** [comment]
@deining - ok with the creation of an "official" prerelease 0.2.0-pre?

**Comment by deining** [comment]
> @deining - ok with the creation of an "official" prerelease 0.2.0-pre?

Yes, sure. This tag already exists, and I'm referring to it in #802. Two people, one thought 😄.

**Comment by chalin** [comment]
@deining - yes, I had noticed the tags that you had created. FYI, we'd like to drop the "v" prefix from release ids right from the start (before the first releases are published). So I'll be creating the release using id `0.2.0-pre` from HEAD (whatever HEAD will be the day that I create it -- some time this week).

**Comment by deining** [comment]
> FYI, we'd like to drop the "v" prefix from release ids right from the start

That's fine for me. Go ahead with this.

> So I'll be creating the release using id `0.2.0-pre` from HEAD

I will adjust the links in the preliminary user guide once you are done.

**Comment by chalin** [comment]
@deining - I assume that you'll be creating a corresponding `dependencies` tag?  Once you are done updating the docs PR/notes, could you do the following?

- Delete tag https://github.com/google/docsy/releases/tag/v0.2.0-pre
- Delete tag https://github.com/google/docsy/releases/tag/dependencies%2Fv0.2.0-pre

**Comment by deining** [comment]
> @deining - I assume that you'll be creating a corresponding `dependencies` tag?

Yes, done.

> Once you are done updating the docs PR/notes, could you do the following?
> 
>     * Delete tag https://github.com/google/docsy/releases/tag/v0.2.0-pre

Done.

>     * Delete tag https://github.com/google/docsy/releases/tag/dependencies%2Fv0.2.0-pre

I would like to do so, but I doubt this is  a wise action, since we are referring to this version in `go.mod`:

https://github.com/google/docsy/blob/9733a5f72258a0446fb1c6de9908c402943e6ec7/go.mod#L5-L9

If we remove this tag, there is a fair chance that we break builds for users that switched to modules already.

**Comment by chalin** [comment]
After adjusting the subtask list, all items for this issue have been completed.
