### ISSUE TITLE
Publish release 0.2.0

### ISSUE THREAD

**Issue by chalin** [google/docsy#955]
Hopefully, we'll be able to close a few more of the [22Q1 milestone](https://github.com/google/docsy/milestone/2) items before the release.

- For items that need to be completed first, see #849
  - [x] Create extra tag `dependencies/v0.2.0`
- [x] #831
- [x] Update version in `package.json` - #961
- [x] #960

**Comment by chalin** [comment]
Done: https://github.com/google/docsy/releases/tag/v0.2.0

**Comment by chalin** [comment]
Also closing:

- https://github.com/google/docsy/milestone/2
- #954

**Comment by chalin** [comment]
@deining - I also created tag `dependencies/v0.2.0`

**Comment by chalin** [comment]
> @deining - I also created tag `dependencies/v0.2.0`

Oops, somehow I had the wrong commit. That is fixed now:

> <img width="454" alt="image" src="https://user-images.githubusercontent.com/4140793/161628328-9c4f3c14-740e-4746-849f-9fad6cbb9b77.png">

**Comment by deining** [comment]
> @deining - I also created tag `dependencies/v0.2.0`

Duhh, the `go.mod` of the commit with this tag still points to ´dependencies/v0.2.0`, which is a bit unfortunate:

https://github.com/google/docsy/blob/f7b37a0aca2ac23e6aab8acd3c9c36e5b7fddb75/go.mod#L5-L9

We should have corrected this first in a new commit and then tagged this commit, I guess. This way, the tags for modules `docsy` and `docsy/dependencies` are in sync.

Anyway, our actions crossed and I just updated #849. This issue mentions a few items that need to be addressed IMHO.

**Comment by chalin** [comment]
@deining - Thanks for the updated notes. We're still learning. I've deleted the release and will start again tomorrow or Wednesday (I don't have time tonight). Could you make the updates you mention in the previous comment? Sorry to all for the fuss. I'm sure that it'll go better the next time around.

**Comment by deining** [comment]
> @deining - Thanks for the updated notes. We're still learning.

That's very true!

> I've deleted the release and will start again tomorrow or Wednesday (I don't have time tonight). Could you make the updates you mention in the previous comment?

Done with #958.

I will go through the whole documented installation process tomorrow to make sure everything works as expected.

> I'm sure that it'll go better the next time around.

Yes, certainly!

**Comment by deining** [comment]
I double checked all module installation methods and made some minor improvements on the way, see #958. For me, everything ran smoothly and worked out as expected.
I also updated the checklist in #849, this tickets now lists everything that needs to be done to get `v0.2.0` out eventually.

Looking forward to the release of version `v0.2.0`!

**Comment by spacefan** [comment]
Looking forward to the release of version `v0.2.0` too!

**Comment by chalin** [comment]
@deining - wonderful! Thank you for #958 and for double checking the instructions. I've left some comments/questions in my review feedback.

**Comment by chalin** [comment]
Ok, I've merged #958 and other 0.2.0-release related PRs. Anything else to do before I create the release @deining?

**Comment by deining** [comment]
> Anything else to do before I create the release

No, there's nothing that I'm aware of. I think we are now ready to assign tags `v0.2.0` and `dependencies/v0.2.0` to commit ID 18a7df2a68c78a (created when #958 was merged). Then you can create the release based on tag `v0.2.0`.

**Comment by chalin** [comment]
Tags created (from the current HEAD).

**Comment by chalin** [comment]
Released: https://github.com/google/docsy/releases/tag/v0.2.0 🤞
