### ISSUE TITLE
Link to Getting-started page gives 404

### ISSUE THREAD

**Issue by chalin** [google/docsy#960]
It seems that #802 rendered the following link invalid (which is referred to by the README, among others: https://docsy.dev/docs/getting-started/

The new link is https://www.docsy.dev/docs/theme-installation/, but it still has a ** Get started** title.

There are a number of ways to fix this, but I suggest:

- Renaming the file so that the following URL is valid: https://docsy.dev/docs/get-started/
- In that file, declare an alias for https://docsy.dev/docs/getting-started/

/cc @LisaFC @deining

**Comment by deining** [comment]
> There are a number of ways to fix this, but I suggest:
> 
>     * Renaming the file so that the following URL is valid: https://docsy.dev/docs/get-started/
> 
>     * In that file, declare an alias for https://docsy.dev/docs/getting-started/
`
Agreed, implemented as suggested in PR #963.
