### ISSUE TITLE
Use different custom page templates within "docs" section?

### ISSUE THREAD

**Issue by jasonday** [google/docsy#978]
I have different kinds of documentation that requires different page content/formatting, but I want them all to live under the Documentation content section, and be added to the navigation.

So, for example, let's say I have two different types of documentation that should live under the same umbrella - A & B. 
Both of these documentation types have different metadata, requiring different/custom YAML. I want content authors to primarily edit YAML, and the page template consumes and outputs into the same format each time using a custom page template. How do I ensure that both A & B are both under "docs"?

My understanding is that currently, that if I create custom content types, that they would be treated separately?

**Comment by LisaFC** [comment]
So just to check that I understand your requirements - you want pages with different templates/layouts under the same directory (docs)? That's simple enough - you just put the source files into the `docs` directory and specify your custom layout as the page's `type` - see: https://www.docsy.dev/docs/adding-content/content/#custom-sections

(the example shows a page under a custom directory with a `docs` type but you can do it the other way round...)

Does that help?

**Comment by jasonday** [comment]
To spell out the process for anyone else:
* In the 'layouts' directory, create a new directory named for the template you want to create
* Copy at least single.html and baseof.html from themes > docsy > layouts >docs to this template directory
* Build your custom template in single.html using Hugo [templating](https://gohugo.io/templates/introduction/)
* In your markdown frontmatter add `type: my_template_directory` and hugo will render using that template for that content

**Comment by denalon** [comment]
old: In the 'layouts' directory, create a new directory named for the template you want to create

new: add `type: doc` in _index.md
