### ISSUE TITLE
Error: failed to download modules: binary with name "go" not found

### ISSUE THREAD

**Issue by Flashpok** [google/docsy#980]
Hi, 

I'm trying to publish my Docsy template with Gitlab Pages.
1. I pushed my local Docsy directory : https://gitlab.com/docsy1/docsy1.gitlab.io (it perfectly works in local hugo server)
2. I added the .gitlab-ci.yml file : https://gitlab.com/docsy1/docsy1.gitlab.io/-/blob/master/.gitlab-ci.yml
3. The pipeline refuse to pass : Error message : Error: failed to download modules: binary with name "go" not found.
Can you help me ?

**Comment by Flashpok** [comment]
With this .gitlab-ci.yml file, it works. But perhaps some scripts are not necessary ?


`image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production
 
default:
  before_script:
    - apk add --update --no-cache git go
    - git submodule update --init --recursive
    - apk add --update nodejs npm
    - npm install -D autoprefixer
    - npm install -D postcss-cli

test:
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH`

**Comment by deining** [comment]
> 3\. Error message : Error: failed to download modules: binary with name "go"

This error message is pretty clear: Executable `go` is missing on the CI/CD server.

Therefore

```
apk add --update --no-cache git go
```

is all that should be needed in your case.

Since your site works perfectly on your server, another approach could be:
In the root directory of your local instance run:

```
hugo mod vendor
```

This creates a directory `_vendor` in your site root. Recursively copy this directory to your GitLab repo, commit it, and everything should work, even without `go`installed.

**Comment by Flashpok** [comment]
Thank you. 

> Therefore
_apk add --update --no-cache git go_
is all that should be needed in your case.

Only "apk add --update --no-cache git go" doesn't work. It fails and returns this error : 

` Error building site: POSTCSS: failed to transform "scss/main.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version`

I don't understand because I use this image : 

`image: registry.gitlab.com/pages/hugo/hugo_extended:latest`

PostCSS isn't included in extended version of Hugo ?

thank you for your help !

**Comment by Flashpok** [comment]
> I will try the other method :
hugo mod vendor

It doesn't work : 
`Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli".`

Strange because the image used is Extended Hugo, no ?

**Comment by Flashpok** [comment]
one more information : 
If I use the "hugo mod vendor" method, only two scripts are required : 
`  - apk add --update nodejs npm`
` - npm install -D postcss-cli`
