### ISSUE TITLE
Algolia search support via config only?

### ISSUE THREAD

**Issue by chalin** [google/docsy#991]
We're already part-way to offering support for Algolia search via changes to config parameters only -- for example, see the conditional code in https://github.com/google/docsy/blob/main/layouts/partials/hooks/head-end.html. Why not go all the way?

I don't know how many projects use Algolia, or whether they'd find this useful. If so, please up/down-vote and/or add a comment below.

**Comment by snunez1** [comment]
Just wondering if this is likely to make it into 0.3? I'm going to upgrade a very old version of Docsy a few weeks after the 0.3 release and it would be nice to have a config-only way to support Algolia.
